// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: domains/console/initiatives/initiatives.proto

// Console v2 — initiatives + snapshots STORAGE wire contract (client side).
//
// Plain-protobuf mirror of console-app's GENERATED storage services
// (InitiativeQuery/Mutation, SnapshotQuery/Mutation), wire-compatible
// with the server (same package `console.initiatives`, same service +
// method names + field numbers). w17ctl calls these storage services
// DIRECTLY — there is no hand-written facade tier. The lifecycle glue
// (get-or-create, lazy push, head advance) is client-side orchestration
// in w17ctl; "one trunk per project" is a DB partial-unique index; the
// compat engine runs client-side. See the console's compat notes for the
// single-source-of-this-mirror question.

package initiativespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InitiativeQuery_Find_FullMethodName = "/console.initiatives.InitiativeQuery/Find"
	InitiativeQuery_List_FullMethodName = "/console.initiatives.InitiativeQuery/List"
	InitiativeQuery_Get_FullMethodName  = "/console.initiatives.InitiativeQuery/Get"
)

// InitiativeQueryClient is the client API for InitiativeQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InitiativeQueryClient interface {
	Find(ctx context.Context, in *FindInitiativeReq, opts ...grpc.CallOption) (*ListInitiativesResp, error)
	List(ctx context.Context, in *ListInitiativesReq, opts ...grpc.CallOption) (*ListInitiativesResp, error)
	Get(ctx context.Context, in *GetInitiativeReq, opts ...grpc.CallOption) (*Initiative, error)
}

type initiativeQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewInitiativeQueryClient(cc grpc.ClientConnInterface) InitiativeQueryClient {
	return &initiativeQueryClient{cc}
}

func (c *initiativeQueryClient) Find(ctx context.Context, in *FindInitiativeReq, opts ...grpc.CallOption) (*ListInitiativesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInitiativesResp)
	err := c.cc.Invoke(ctx, InitiativeQuery_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initiativeQueryClient) List(ctx context.Context, in *ListInitiativesReq, opts ...grpc.CallOption) (*ListInitiativesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInitiativesResp)
	err := c.cc.Invoke(ctx, InitiativeQuery_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initiativeQueryClient) Get(ctx context.Context, in *GetInitiativeReq, opts ...grpc.CallOption) (*Initiative, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Initiative)
	err := c.cc.Invoke(ctx, InitiativeQuery_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitiativeQueryServer is the server API for InitiativeQuery service.
// All implementations must embed UnimplementedInitiativeQueryServer
// for forward compatibility.
type InitiativeQueryServer interface {
	Find(context.Context, *FindInitiativeReq) (*ListInitiativesResp, error)
	List(context.Context, *ListInitiativesReq) (*ListInitiativesResp, error)
	Get(context.Context, *GetInitiativeReq) (*Initiative, error)
	mustEmbedUnimplementedInitiativeQueryServer()
}

// UnimplementedInitiativeQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInitiativeQueryServer struct{}

func (UnimplementedInitiativeQueryServer) Find(context.Context, *FindInitiativeReq) (*ListInitiativesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedInitiativeQueryServer) List(context.Context, *ListInitiativesReq) (*ListInitiativesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedInitiativeQueryServer) Get(context.Context, *GetInitiativeReq) (*Initiative, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedInitiativeQueryServer) mustEmbedUnimplementedInitiativeQueryServer() {}
func (UnimplementedInitiativeQueryServer) testEmbeddedByValue()                         {}

// UnsafeInitiativeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitiativeQueryServer will
// result in compilation errors.
type UnsafeInitiativeQueryServer interface {
	mustEmbedUnimplementedInitiativeQueryServer()
}

func RegisterInitiativeQueryServer(s grpc.ServiceRegistrar, srv InitiativeQueryServer) {
	// If the following call pancis, it indicates UnimplementedInitiativeQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InitiativeQuery_ServiceDesc, srv)
}

func _InitiativeQuery_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindInitiativeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiativeQueryServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitiativeQuery_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiativeQueryServer).Find(ctx, req.(*FindInitiativeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitiativeQuery_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInitiativesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiativeQueryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitiativeQuery_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiativeQueryServer).List(ctx, req.(*ListInitiativesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitiativeQuery_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInitiativeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiativeQueryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitiativeQuery_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiativeQueryServer).Get(ctx, req.(*GetInitiativeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InitiativeQuery_ServiceDesc is the grpc.ServiceDesc for InitiativeQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitiativeQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.initiatives.InitiativeQuery",
	HandlerType: (*InitiativeQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _InitiativeQuery_Find_Handler,
		},
		{
			MethodName: "List",
			Handler:    _InitiativeQuery_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _InitiativeQuery_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domains/console/initiatives/initiatives.proto",
}

const (
	InitiativeMutation_Create_FullMethodName    = "/console.initiatives.InitiativeMutation/Create"
	InitiativeMutation_SetHead_FullMethodName   = "/console.initiatives.InitiativeMutation/SetHead"
	InitiativeMutation_SetStatus_FullMethodName = "/console.initiatives.InitiativeMutation/SetStatus"
)

// InitiativeMutationClient is the client API for InitiativeMutation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InitiativeMutationClient interface {
	Create(ctx context.Context, in *CreateInitiativeReq, opts ...grpc.CallOption) (*CreateInitiativeResp, error)
	SetHead(ctx context.Context, in *SetHeadReq, opts ...grpc.CallOption) (*SetHeadResp, error)
	SetStatus(ctx context.Context, in *SetStatusReq, opts ...grpc.CallOption) (*SetStatusResp, error)
}

type initiativeMutationClient struct {
	cc grpc.ClientConnInterface
}

func NewInitiativeMutationClient(cc grpc.ClientConnInterface) InitiativeMutationClient {
	return &initiativeMutationClient{cc}
}

func (c *initiativeMutationClient) Create(ctx context.Context, in *CreateInitiativeReq, opts ...grpc.CallOption) (*CreateInitiativeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInitiativeResp)
	err := c.cc.Invoke(ctx, InitiativeMutation_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initiativeMutationClient) SetHead(ctx context.Context, in *SetHeadReq, opts ...grpc.CallOption) (*SetHeadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetHeadResp)
	err := c.cc.Invoke(ctx, InitiativeMutation_SetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initiativeMutationClient) SetStatus(ctx context.Context, in *SetStatusReq, opts ...grpc.CallOption) (*SetStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStatusResp)
	err := c.cc.Invoke(ctx, InitiativeMutation_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitiativeMutationServer is the server API for InitiativeMutation service.
// All implementations must embed UnimplementedInitiativeMutationServer
// for forward compatibility.
type InitiativeMutationServer interface {
	Create(context.Context, *CreateInitiativeReq) (*CreateInitiativeResp, error)
	SetHead(context.Context, *SetHeadReq) (*SetHeadResp, error)
	SetStatus(context.Context, *SetStatusReq) (*SetStatusResp, error)
	mustEmbedUnimplementedInitiativeMutationServer()
}

// UnimplementedInitiativeMutationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInitiativeMutationServer struct{}

func (UnimplementedInitiativeMutationServer) Create(context.Context, *CreateInitiativeReq) (*CreateInitiativeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedInitiativeMutationServer) SetHead(context.Context, *SetHeadReq) (*SetHeadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHead not implemented")
}
func (UnimplementedInitiativeMutationServer) SetStatus(context.Context, *SetStatusReq) (*SetStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedInitiativeMutationServer) mustEmbedUnimplementedInitiativeMutationServer() {}
func (UnimplementedInitiativeMutationServer) testEmbeddedByValue()                            {}

// UnsafeInitiativeMutationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitiativeMutationServer will
// result in compilation errors.
type UnsafeInitiativeMutationServer interface {
	mustEmbedUnimplementedInitiativeMutationServer()
}

func RegisterInitiativeMutationServer(s grpc.ServiceRegistrar, srv InitiativeMutationServer) {
	// If the following call pancis, it indicates UnimplementedInitiativeMutationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InitiativeMutation_ServiceDesc, srv)
}

func _InitiativeMutation_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInitiativeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiativeMutationServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitiativeMutation_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiativeMutationServer).Create(ctx, req.(*CreateInitiativeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitiativeMutation_SetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHeadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiativeMutationServer).SetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitiativeMutation_SetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiativeMutationServer).SetHead(ctx, req.(*SetHeadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitiativeMutation_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiativeMutationServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitiativeMutation_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiativeMutationServer).SetStatus(ctx, req.(*SetStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InitiativeMutation_ServiceDesc is the grpc.ServiceDesc for InitiativeMutation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitiativeMutation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.initiatives.InitiativeMutation",
	HandlerType: (*InitiativeMutationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _InitiativeMutation_Create_Handler,
		},
		{
			MethodName: "SetHead",
			Handler:    _InitiativeMutation_SetHead_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _InitiativeMutation_SetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domains/console/initiatives/initiatives.proto",
}

const (
	SnapshotQuery_Get_FullMethodName = "/console.initiatives.SnapshotQuery/Get"
)

// SnapshotQueryClient is the client API for SnapshotQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotQueryClient interface {
	Get(ctx context.Context, in *GetSnapshotReq, opts ...grpc.CallOption) (*Snapshot, error)
}

type snapshotQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotQueryClient(cc grpc.ClientConnInterface) SnapshotQueryClient {
	return &snapshotQueryClient{cc}
}

func (c *snapshotQueryClient) Get(ctx context.Context, in *GetSnapshotReq, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, SnapshotQuery_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotQueryServer is the server API for SnapshotQuery service.
// All implementations must embed UnimplementedSnapshotQueryServer
// for forward compatibility.
type SnapshotQueryServer interface {
	Get(context.Context, *GetSnapshotReq) (*Snapshot, error)
	mustEmbedUnimplementedSnapshotQueryServer()
}

// UnimplementedSnapshotQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotQueryServer struct{}

func (UnimplementedSnapshotQueryServer) Get(context.Context, *GetSnapshotReq) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSnapshotQueryServer) mustEmbedUnimplementedSnapshotQueryServer() {}
func (UnimplementedSnapshotQueryServer) testEmbeddedByValue()                       {}

// UnsafeSnapshotQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotQueryServer will
// result in compilation errors.
type UnsafeSnapshotQueryServer interface {
	mustEmbedUnimplementedSnapshotQueryServer()
}

func RegisterSnapshotQueryServer(s grpc.ServiceRegistrar, srv SnapshotQueryServer) {
	// If the following call pancis, it indicates UnimplementedSnapshotQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotQuery_ServiceDesc, srv)
}

func _SnapshotQuery_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotQueryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotQuery_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotQueryServer).Get(ctx, req.(*GetSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotQuery_ServiceDesc is the grpc.ServiceDesc for SnapshotQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.initiatives.SnapshotQuery",
	HandlerType: (*SnapshotQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SnapshotQuery_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domains/console/initiatives/initiatives.proto",
}

const (
	SnapshotMutation_PushSnapshot_FullMethodName = "/console.initiatives.SnapshotMutation/PushSnapshot"
)

// SnapshotMutationClient is the client API for SnapshotMutation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotMutationClient interface {
	PushSnapshot(ctx context.Context, in *PushSnapshotReq, opts ...grpc.CallOption) (*PushSnapshotResp, error)
}

type snapshotMutationClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotMutationClient(cc grpc.ClientConnInterface) SnapshotMutationClient {
	return &snapshotMutationClient{cc}
}

func (c *snapshotMutationClient) PushSnapshot(ctx context.Context, in *PushSnapshotReq, opts ...grpc.CallOption) (*PushSnapshotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushSnapshotResp)
	err := c.cc.Invoke(ctx, SnapshotMutation_PushSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotMutationServer is the server API for SnapshotMutation service.
// All implementations must embed UnimplementedSnapshotMutationServer
// for forward compatibility.
type SnapshotMutationServer interface {
	PushSnapshot(context.Context, *PushSnapshotReq) (*PushSnapshotResp, error)
	mustEmbedUnimplementedSnapshotMutationServer()
}

// UnimplementedSnapshotMutationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotMutationServer struct{}

func (UnimplementedSnapshotMutationServer) PushSnapshot(context.Context, *PushSnapshotReq) (*PushSnapshotResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushSnapshot not implemented")
}
func (UnimplementedSnapshotMutationServer) mustEmbedUnimplementedSnapshotMutationServer() {}
func (UnimplementedSnapshotMutationServer) testEmbeddedByValue()                          {}

// UnsafeSnapshotMutationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotMutationServer will
// result in compilation errors.
type UnsafeSnapshotMutationServer interface {
	mustEmbedUnimplementedSnapshotMutationServer()
}

func RegisterSnapshotMutationServer(s grpc.ServiceRegistrar, srv SnapshotMutationServer) {
	// If the following call pancis, it indicates UnimplementedSnapshotMutationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotMutation_ServiceDesc, srv)
}

func _SnapshotMutation_PushSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotMutationServer).PushSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotMutation_PushSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotMutationServer).PushSnapshot(ctx, req.(*PushSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotMutation_ServiceDesc is the grpc.ServiceDesc for SnapshotMutation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotMutation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.initiatives.SnapshotMutation",
	HandlerType: (*SnapshotMutationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushSnapshot",
			Handler:    _SnapshotMutation_PushSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domains/console/initiatives/initiatives.proto",
}
