// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: common/distx/distributed_tx.proto

package distxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Isolation mirrors `(w17.db.method).tx_isolation`
// (`w17.db.TxIsolation`) on the distributed-tx wire — same
// names, same numbers — so a caller can open the transaction at
// exactly the level the method it is about to call declares.
// Duplicated rather than imported because this contract is the
// public runtime surface and must not drag the compiler's
// annotation vocabulary into every client.
type Isolation int32

const (
	Isolation_ISOLATION_UNSPECIFIED Isolation = 0 // driver default
	Isolation_READ_UNCOMMITTED      Isolation = 1
	Isolation_READ_COMMITTED        Isolation = 2
	Isolation_REPEATABLE_READ       Isolation = 3
	Isolation_SERIALIZABLE          Isolation = 4
)

// Enum value maps for Isolation.
var (
	Isolation_name = map[int32]string{
		0: "ISOLATION_UNSPECIFIED",
		1: "READ_UNCOMMITTED",
		2: "READ_COMMITTED",
		3: "REPEATABLE_READ",
		4: "SERIALIZABLE",
	}
	Isolation_value = map[string]int32{
		"ISOLATION_UNSPECIFIED": 0,
		"READ_UNCOMMITTED":      1,
		"READ_COMMITTED":        2,
		"REPEATABLE_READ":       3,
		"SERIALIZABLE":          4,
	}
)

func (x Isolation) Enum() *Isolation {
	p := new(Isolation)
	*p = x
	return p
}

func (x Isolation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Isolation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_distx_distributed_tx_proto_enumTypes[0].Descriptor()
}

func (Isolation) Type() protoreflect.EnumType {
	return &file_common_distx_distributed_tx_proto_enumTypes[0]
}

func (x Isolation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Isolation.Descriptor instead.
func (Isolation) EnumDescriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{0}
}

type BeginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ConnectionName names a connection declared in the domain's
	// schema (D26 unique identifier). Single-instance ignores
	// this until M2 multi-connection lands; multi-instance
	// domains route Begin to the replica owning that connection.
	ConnectionName string `protobuf:"bytes,1,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	// TxTimeoutMs — long-running transaction deadline in
	// milliseconds (slice 6Q-F Tier 2). When > 0, the distx
	// server wraps the tx's ctx with `context.WithTimeout`; on
	// expiry the sql package auto-rolls back the underlying
	// transaction. 0 (default) leaves the tx with the
	// long-living `context.WithoutCancel(grpcCtx)` semantics
	// documented on Begin's doc-comment.
	//
	// Two-tier model (`docs/archive/iteration-2-multidb.md` §M2-F):
	//   - Tier 1 = `(w17.db.method).timeout_ms` — per-method
	//     deadline applied to the storage handler's own ctx;
	//     bounds individual statement work.
	//   - Tier 2 (this field) = tx-wide deadline applied to the
	//     long-running distributed-tx itself; bounds the tx
	//     entity across multiple method calls. Typically the
	//     facade caller propagates its own deadline-budget
	//     here.
	//
	// Negative values are rejected at the gRPC boundary.
	TxTimeoutMs int32 `protobuf:"varint,2,opt,name=tx_timeout_ms,json=txTimeoutMs,proto3" json:"tx_timeout_ms,omitempty"`
	// Isolation pins the transaction's isolation level at Begin —
	// the ONLY moment at which it can be pinned, since no engine
	// lets a running transaction change level.
	//
	// It exists because `(w17.db.method).tx_isolation` is a
	// property of the METHOD, and a method that is CALLED inside
	// someone else's transaction cannot open one. Before this
	// field, such a method's declaration was silently dropped:
	// the generated preamble applied the declared level only on
	// its own fresh-tx branch, and the distributed-tx branch ran
	// at whatever the driver default was (T3-7 pass #9 D-F7). The
	// caller now states the level up front, and a method whose
	// declaration the open transaction cannot satisfy REFUSES to
	// adopt it (`txregistry.ErrIsolationTooWeak`) rather than
	// running weaker than declared.
	//
	// Unspecified (the default) keeps the driver default, so
	// every existing caller is unchanged.
	Isolation     Isolation `protobuf:"varint,3,opt,name=isolation,proto3,enum=w17.common.distx.Isolation" json:"isolation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_common_distx_distributed_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_distx_distributed_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{0}
}

func (x *BeginRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

func (x *BeginRequest) GetTxTimeoutMs() int32 {
	if x != nil {
		return x.TxTimeoutMs
	}
	return 0
}

func (x *BeginRequest) GetIsolation() Isolation {
	if x != nil {
		return x.Isolation
	}
	return Isolation_ISOLATION_UNSPECIFIED
}

type BeginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ConnId is the routing token the multi-instance grpcproxy
	// uses to pin every subsequent RPC in this tx to the same
	// backend replica. Single-instance returns empty — every RPC
	// already lands on the sole live binary.
	ConnId string `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// TxId uniquely identifies the open tx within the binary
	// (or, with the proxy, within the cluster). Caller threads
	// this into the `w17-tx-id` gRPC metadata header on every
	// subsequent storage RPC that should run inside this tx.
	TxId          string `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginResponse) Reset() {
	*x = BeginResponse{}
	mi := &file_common_distx_distributed_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResponse) ProtoMessage() {}

func (x *BeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_distx_distributed_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResponse.ProtoReflect.Descriptor instead.
func (*BeginResponse) Descriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{1}
}

func (x *BeginResponse) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *BeginResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_common_distx_distributed_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_distx_distributed_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_common_distx_distributed_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_distx_distributed_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{3}
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_common_distx_distributed_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_distx_distributed_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_common_distx_distributed_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_distx_distributed_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_common_distx_distributed_tx_proto_rawDescGZIP(), []int{5}
}

var File_common_distx_distributed_tx_proto protoreflect.FileDescriptor

const file_common_distx_distributed_tx_proto_rawDesc = "" +
	"\n" +
	"!common/distx/distributed_tx.proto\x12\x10w17.common.distx\"\x96\x01\n" +
	"\fBeginRequest\x12'\n" +
	"\x0fconnection_name\x18\x01 \x01(\tR\x0econnectionName\x12\"\n" +
	"\rtx_timeout_ms\x18\x02 \x01(\x05R\vtxTimeoutMs\x129\n" +
	"\tisolation\x18\x03 \x01(\x0e2\x1b.w17.common.distx.IsolationR\tisolation\"=\n" +
	"\rBeginResponse\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\"$\n" +
	"\rCommitRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\x10\n" +
	"\x0eCommitResponse\"&\n" +
	"\x0fRollbackRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\x12\n" +
	"\x10RollbackResponse*w\n" +
	"\tIsolation\x12\x19\n" +
	"\x15ISOLATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10READ_UNCOMMITTED\x10\x01\x12\x12\n" +
	"\x0eREAD_COMMITTED\x10\x02\x12\x13\n" +
	"\x0fREPEATABLE_READ\x10\x03\x12\x10\n" +
	"\fSERIALIZABLE\x10\x042\x85\x02\n" +
	"\x19W17DistributedTransaction\x12H\n" +
	"\x05Begin\x12\x1e.w17.common.distx.BeginRequest\x1a\x1f.w17.common.distx.BeginResponse\x12K\n" +
	"\x06Commit\x12\x1f.w17.common.distx.CommitRequest\x1a .w17.common.distx.CommitResponse\x12Q\n" +
	"\bRollback\x12!.w17.common.distx.RollbackRequest\x1a\".w17.common.distx.RollbackResponseB>Z<github.com/wandering-compiler/sdk/go/pb/common/distx;distxpbb\x06proto3"

var (
	file_common_distx_distributed_tx_proto_rawDescOnce sync.Once
	file_common_distx_distributed_tx_proto_rawDescData []byte
)

func file_common_distx_distributed_tx_proto_rawDescGZIP() []byte {
	file_common_distx_distributed_tx_proto_rawDescOnce.Do(func() {
		file_common_distx_distributed_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_distx_distributed_tx_proto_rawDesc), len(file_common_distx_distributed_tx_proto_rawDesc)))
	})
	return file_common_distx_distributed_tx_proto_rawDescData
}

var file_common_distx_distributed_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_distx_distributed_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_distx_distributed_tx_proto_goTypes = []any{
	(Isolation)(0),           // 0: w17.common.distx.Isolation
	(*BeginRequest)(nil),     // 1: w17.common.distx.BeginRequest
	(*BeginResponse)(nil),    // 2: w17.common.distx.BeginResponse
	(*CommitRequest)(nil),    // 3: w17.common.distx.CommitRequest
	(*CommitResponse)(nil),   // 4: w17.common.distx.CommitResponse
	(*RollbackRequest)(nil),  // 5: w17.common.distx.RollbackRequest
	(*RollbackResponse)(nil), // 6: w17.common.distx.RollbackResponse
}
var file_common_distx_distributed_tx_proto_depIdxs = []int32{
	0, // 0: w17.common.distx.BeginRequest.isolation:type_name -> w17.common.distx.Isolation
	1, // 1: w17.common.distx.W17DistributedTransaction.Begin:input_type -> w17.common.distx.BeginRequest
	3, // 2: w17.common.distx.W17DistributedTransaction.Commit:input_type -> w17.common.distx.CommitRequest
	5, // 3: w17.common.distx.W17DistributedTransaction.Rollback:input_type -> w17.common.distx.RollbackRequest
	2, // 4: w17.common.distx.W17DistributedTransaction.Begin:output_type -> w17.common.distx.BeginResponse
	4, // 5: w17.common.distx.W17DistributedTransaction.Commit:output_type -> w17.common.distx.CommitResponse
	6, // 6: w17.common.distx.W17DistributedTransaction.Rollback:output_type -> w17.common.distx.RollbackResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_distx_distributed_tx_proto_init() }
func file_common_distx_distributed_tx_proto_init() {
	if File_common_distx_distributed_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_distx_distributed_tx_proto_rawDesc), len(file_common_distx_distributed_tx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_distx_distributed_tx_proto_goTypes,
		DependencyIndexes: file_common_distx_distributed_tx_proto_depIdxs,
		EnumInfos:         file_common_distx_distributed_tx_proto_enumTypes,
		MessageInfos:      file_common_distx_distributed_tx_proto_msgTypes,
	}.Build()
	File_common_distx_distributed_tx_proto = out.File
	file_common_distx_distributed_tx_proto_goTypes = nil
	file_common_distx_distributed_tx_proto_depIdxs = nil
}
