// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: common/distx/distributed_tx.proto

package distxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	W17DistributedTransaction_Begin_FullMethodName    = "/w17.common.distx.W17DistributedTransaction/Begin"
	W17DistributedTransaction_Commit_FullMethodName   = "/w17.common.distx.W17DistributedTransaction/Commit"
	W17DistributedTransaction_Rollback_FullMethodName = "/w17.common.distx.W17DistributedTransaction/Rollback"
)

// W17DistributedTransactionClient is the client API for W17DistributedTransaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// W17DistributedTransaction is the distributed-transaction
// coordination surface every w17 storage binary registers per
// `docs/archive/iteration-2-dql.md` §"W17DistributedTransaction".
//
// A caller drives a logical multi-RPC transaction by:
//
//	resp = stub.Begin({connection_name: "main"})  // → tx_id
//	stub.SomeStorageMethod(req, metadata={"w17-tx-id": resp.tx_id})
//	stub.AnotherStorageMethod(req, metadata={"w17-tx-id": resp.tx_id})
//	stub.Commit({tx_id: resp.tx_id})  // or Rollback
//
// Storage handlers see the metadata, look up tx_id in the
// running binary's tx registry, and run their queries inside
// the open *sql.Tx. If the metadata is absent (caller didn't
// open a tx, or the id resolves to nothing), the handler opens
// a per-method tx — the slice 6H "always-fresh-tx" fallback.
//
// **Single-instance default (D-iter2-dql-11).** In the common
// case of one storage binary per domain, `conn_id` is a
// redundant axis — every `tx_id` resolves on the sole live
// binary. The single-instance impl returns conn_id as an empty
// string and ignores it on subsequent calls. Multi-instance
// scale-out routes via `conn_id` through a future Rust
// `grpcproxy` daemon (parked).
type W17DistributedTransactionClient interface {
	// Begin opens a fresh transaction on the named connection
	// and returns the (conn_id, tx_id) pair the caller threads
	// into subsequent storage RPCs. Single-instance leaves
	// conn_id empty.
	Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error)
	// Commit finalises the tx for tx_id. Returns NotFound when
	// the id doesn't resolve (already closed / never opened /
	// binary restarted between Begin and Commit).
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// Rollback discards the tx for tx_id. Same NotFound on
	// unknown id.
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
}

type w17DistributedTransactionClient struct {
	cc grpc.ClientConnInterface
}

func NewW17DistributedTransactionClient(cc grpc.ClientConnInterface) W17DistributedTransactionClient {
	return &w17DistributedTransactionClient{cc}
}

func (c *w17DistributedTransactionClient) Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginResponse)
	err := c.cc.Invoke(ctx, W17DistributedTransaction_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *w17DistributedTransactionClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, W17DistributedTransaction_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *w17DistributedTransactionClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, W17DistributedTransaction_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// W17DistributedTransactionServer is the server API for W17DistributedTransaction service.
// All implementations must embed UnimplementedW17DistributedTransactionServer
// for forward compatibility.
//
// W17DistributedTransaction is the distributed-transaction
// coordination surface every w17 storage binary registers per
// `docs/archive/iteration-2-dql.md` §"W17DistributedTransaction".
//
// A caller drives a logical multi-RPC transaction by:
//
//	resp = stub.Begin({connection_name: "main"})  // → tx_id
//	stub.SomeStorageMethod(req, metadata={"w17-tx-id": resp.tx_id})
//	stub.AnotherStorageMethod(req, metadata={"w17-tx-id": resp.tx_id})
//	stub.Commit({tx_id: resp.tx_id})  // or Rollback
//
// Storage handlers see the metadata, look up tx_id in the
// running binary's tx registry, and run their queries inside
// the open *sql.Tx. If the metadata is absent (caller didn't
// open a tx, or the id resolves to nothing), the handler opens
// a per-method tx — the slice 6H "always-fresh-tx" fallback.
//
// **Single-instance default (D-iter2-dql-11).** In the common
// case of one storage binary per domain, `conn_id` is a
// redundant axis — every `tx_id` resolves on the sole live
// binary. The single-instance impl returns conn_id as an empty
// string and ignores it on subsequent calls. Multi-instance
// scale-out routes via `conn_id` through a future Rust
// `grpcproxy` daemon (parked).
type W17DistributedTransactionServer interface {
	// Begin opens a fresh transaction on the named connection
	// and returns the (conn_id, tx_id) pair the caller threads
	// into subsequent storage RPCs. Single-instance leaves
	// conn_id empty.
	Begin(context.Context, *BeginRequest) (*BeginResponse, error)
	// Commit finalises the tx for tx_id. Returns NotFound when
	// the id doesn't resolve (already closed / never opened /
	// binary restarted between Begin and Commit).
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// Rollback discards the tx for tx_id. Same NotFound on
	// unknown id.
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	mustEmbedUnimplementedW17DistributedTransactionServer()
}

// UnimplementedW17DistributedTransactionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedW17DistributedTransactionServer struct{}

func (UnimplementedW17DistributedTransactionServer) Begin(context.Context, *BeginRequest) (*BeginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedW17DistributedTransactionServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedW17DistributedTransactionServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedW17DistributedTransactionServer) mustEmbedUnimplementedW17DistributedTransactionServer() {
}
func (UnimplementedW17DistributedTransactionServer) testEmbeddedByValue() {}

// UnsafeW17DistributedTransactionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to W17DistributedTransactionServer will
// result in compilation errors.
type UnsafeW17DistributedTransactionServer interface {
	mustEmbedUnimplementedW17DistributedTransactionServer()
}

func RegisterW17DistributedTransactionServer(s grpc.ServiceRegistrar, srv W17DistributedTransactionServer) {
	// If the following call pancis, it indicates UnimplementedW17DistributedTransactionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&W17DistributedTransaction_ServiceDesc, srv)
}

func _W17DistributedTransaction_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(W17DistributedTransactionServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: W17DistributedTransaction_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(W17DistributedTransactionServer).Begin(ctx, req.(*BeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _W17DistributedTransaction_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(W17DistributedTransactionServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: W17DistributedTransaction_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(W17DistributedTransactionServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _W17DistributedTransaction_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(W17DistributedTransactionServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: W17DistributedTransaction_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(W17DistributedTransactionServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// W17DistributedTransaction_ServiceDesc is the grpc.ServiceDesc for W17DistributedTransaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var W17DistributedTransaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "w17.common.distx.W17DistributedTransaction",
	HandlerType: (*W17DistributedTransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _W17DistributedTransaction_Begin_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _W17DistributedTransaction_Commit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _W17DistributedTransaction_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/distx/distributed_tx.proto",
}
