// PUBLIC APPLY CONTRACT — the flattened, verified, decoration-stripped
// migration set the thin client (w17ctl's own module) fetches from the console
// and applies to its target stores. Homed under the dedicated `w17apply/`
// namespace (next to dev_plan.proto) so the public client imports ONLY this
// irpb-free shape, never the IR-laden compiler registry pb
// (MigrationRegistry) package.
//
// Public-split boundary (docs/specs/w17ctl/public-split-architecture.md §4/§8.1
// + the w17migrate-absorption): the prod apply path moves into w17ctl, which
// must do ZERO crypto. The console (which signed every migration body via the
// registry's signer) VERIFIES the signature server-side and STRIPS the
// decoration here, returning clean SQL the client just executes. So the client
// holds no signing/verifier key and no decorate/registrypb dependency — it
// fetches vouched, clean migrations and applies them online (the boundary's
// "nothing offline; codegen is online anyway"). Local integrity of the fetched
// set is a plain content_sha256 check (hashing, not crypto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17apply/fetch.proto

package applyfetchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchMigrationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectID is the registry project key (the lock's project_id).
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Targets enumerate the connections to fetch + each one's pinned ceiling
	// (the lock connection's target_migration_id). The client reads these from
	// its local lock; connections with no pinned target are simply omitted.
	Targets       []*Target `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMigrationsRequest) Reset() {
	*x = FetchMigrationsRequest{}
	mi := &file_w17apply_fetch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMigrationsRequest) ProtoMessage() {}

func (x *FetchMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMigrationsRequest.ProtoReflect.Descriptor instead.
func (*FetchMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchMigrationsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FetchMigrationsRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type Target struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Connection      string                 `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	UpToMigrationId string                 `protobuf:"bytes,2,opt,name=up_to_migration_id,json=upToMigrationId,proto3" json:"up_to_migration_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_w17apply_fetch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *Target) GetUpToMigrationId() string {
	if x != nil {
		return x.UpToMigrationId
	}
	return ""
}

type FetchMigrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*Migration           `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMigrationsResponse) Reset() {
	*x = FetchMigrationsResponse{}
	mi := &file_w17apply_fetch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMigrationsResponse) ProtoMessage() {}

func (x *FetchMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMigrationsResponse.ProtoReflect.Descriptor instead.
func (*FetchMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{2}
}

func (x *FetchMigrationsResponse) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

// Migration is one connection's apply payload, flattened from the registry's
// IR-laden `registrypb.Migration` to its irpb-free string fields, with the
// up/down bodies already decoration-stripped (clean executable SQL).
type Migration struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connection string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// up_sql / down_sql — the transactional bodies (BEGIN…COMMIT wrapped for
	// transactional dialects), decoration stripped.
	UpSql   string `protobuf:"bytes,3,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	DownSql string `protobuf:"bytes,4,opt,name=down_sql,json=downSql,proto3" json:"down_sql,omitempty"`
	// up_post_tx / down_pre_tx — the non-transactional skirts (CONCURRENTLY
	// index builds etc.). Empty for the common case.
	UpPostTx  string `protobuf:"bytes,5,opt,name=up_post_tx,json=upPostTx,proto3" json:"up_post_tx,omitempty"`
	DownPreTx string `protobuf:"bytes,6,opt,name=down_pre_tx,json=downPreTx,proto3" json:"down_pre_tx,omitempty"`
	// content_sha256 — the registry's content hash, for a keyless local
	// integrity check of the fetched set (corruption detection).
	ContentSha256 string `protobuf:"bytes,7,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_w17apply_fetch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{3}
}

func (x *Migration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *Migration) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *Migration) GetDownSql() string {
	if x != nil {
		return x.DownSql
	}
	return ""
}

func (x *Migration) GetUpPostTx() string {
	if x != nil {
		return x.UpPostTx
	}
	return ""
}

func (x *Migration) GetDownPreTx() string {
	if x != nil {
		return x.DownPreTx
	}
	return ""
}

func (x *Migration) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

type RenderFixtureSeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ir is the opaque compiled-IR blob (the bytes CompileIR returned) — the
	// server decodes it with its own irpb.Schema, the client never does.
	Ir     []byte `protobuf:"bytes,1,opt,name=ir,proto3" json:"ir,omitempty"`
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// json is the local fixture's raw canonical JSON body.
	Json          []byte `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderFixtureSeedRequest) Reset() {
	*x = RenderFixtureSeedRequest{}
	mi := &file_w17apply_fetch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderFixtureSeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderFixtureSeedRequest) ProtoMessage() {}

func (x *RenderFixtureSeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderFixtureSeedRequest.ProtoReflect.Descriptor instead.
func (*RenderFixtureSeedRequest) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{4}
}

func (x *RenderFixtureSeedRequest) GetIr() []byte {
	if x != nil {
		return x.Ir
	}
	return nil
}

func (x *RenderFixtureSeedRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RenderFixtureSeedRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type FetchFixtureSeedRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Domain    string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// name is the fixture name (the registry key within the domain).
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFixtureSeedRequest) Reset() {
	*x = FetchFixtureSeedRequest{}
	mi := &file_w17apply_fetch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFixtureSeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFixtureSeedRequest) ProtoMessage() {}

func (x *FetchFixtureSeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFixtureSeedRequest.ProtoReflect.Descriptor instead.
func (*FetchFixtureSeedRequest) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{5}
}

func (x *FetchFixtureSeedRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FetchFixtureSeedRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FetchFixtureSeedRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FetchFixtureSeedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// statements run in order (FK targets before referrers), each in the same
	// transaction client-side.
	Statements    []*SeedStmt `protobuf:"bytes,1,rep,name=statements,proto3" json:"statements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFixtureSeedResponse) Reset() {
	*x = FetchFixtureSeedResponse{}
	mi := &file_w17apply_fetch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFixtureSeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFixtureSeedResponse) ProtoMessage() {}

func (x *FetchFixtureSeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFixtureSeedResponse.ProtoReflect.Descriptor instead.
func (*FetchFixtureSeedResponse) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{6}
}

func (x *FetchFixtureSeedResponse) GetStatements() []*SeedStmt {
	if x != nil {
		return x.Statements
	}
	return nil
}

// SeedStmt is one parameterized upsert: a SQL string with $1..$N placeholders
// and the ordered, pre-bound argument values. The client binds each arg
// (structpb.Value → its scalar / JSON-string form) straight into a
// parameterized Exec — values are NEVER interpolated into the SQL text.
type SeedStmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Args          []*structpb.Value      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedStmt) Reset() {
	*x = SeedStmt{}
	mi := &file_w17apply_fetch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedStmt) ProtoMessage() {}

func (x *SeedStmt) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedStmt.ProtoReflect.Descriptor instead.
func (*SeedStmt) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{7}
}

func (x *SeedStmt) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *SeedStmt) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

type FetchFixtureFilesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// domain scopes the download; empty = every domain's fixtures.
	Domain        string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFixtureFilesRequest) Reset() {
	*x = FetchFixtureFilesRequest{}
	mi := &file_w17apply_fetch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFixtureFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFixtureFilesRequest) ProtoMessage() {}

func (x *FetchFixtureFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFixtureFilesRequest.ProtoReflect.Descriptor instead.
func (*FetchFixtureFilesRequest) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{8}
}

func (x *FetchFixtureFilesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FetchFixtureFilesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type FetchFixtureFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FixtureFile         `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFixtureFilesResponse) Reset() {
	*x = FetchFixtureFilesResponse{}
	mi := &file_w17apply_fetch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFixtureFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFixtureFilesResponse) ProtoMessage() {}

func (x *FetchFixtureFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFixtureFilesResponse.ProtoReflect.Descriptor instead.
func (*FetchFixtureFilesResponse) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{9}
}

func (x *FetchFixtureFilesResponse) GetFiles() []*FixtureFile {
	if x != nil {
		return x.Files
	}
	return nil
}

// FixtureFile is one stored fixture as editable JSON (the server-encoded
// canonical form), plus its identity + a row-count hint.
type FixtureFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	RowCount      int32                  `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureFile) Reset() {
	*x = FixtureFile{}
	mi := &file_w17apply_fetch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureFile) ProtoMessage() {}

func (x *FixtureFile) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_fetch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureFile.ProtoReflect.Descriptor instead.
func (*FixtureFile) Descriptor() ([]byte, []int) {
	return file_w17apply_fetch_proto_rawDescGZIP(), []int{10}
}

func (x *FixtureFile) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FixtureFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FixtureFile) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *FixtureFile) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

var File_w17apply_fetch_proto protoreflect.FileDescriptor

const file_w17apply_fetch_proto_rawDesc = "" +
	"\n" +
	"\x14w17apply/fetch.proto\x12\tw17.apply\x1a\x1cgoogle/protobuf/struct.proto\"d\n" +
	"\x16FetchMigrationsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12+\n" +
	"\atargets\x18\x02 \x03(\v2\x11.w17.apply.TargetR\atargets\"U\n" +
	"\x06Target\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\x12+\n" +
	"\x12up_to_migration_id\x18\x02 \x01(\tR\x0fupToMigrationId\"O\n" +
	"\x17FetchMigrationsResponse\x124\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x14.w17.apply.MigrationR\n" +
	"migrations\"\xd2\x01\n" +
	"\tMigration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12\x15\n" +
	"\x06up_sql\x18\x03 \x01(\tR\x05upSql\x12\x19\n" +
	"\bdown_sql\x18\x04 \x01(\tR\adownSql\x12\x1c\n" +
	"\n" +
	"up_post_tx\x18\x05 \x01(\tR\bupPostTx\x12\x1e\n" +
	"\vdown_pre_tx\x18\x06 \x01(\tR\tdownPreTx\x12%\n" +
	"\x0econtent_sha256\x18\a \x01(\tR\rcontentSha256\"V\n" +
	"\x18RenderFixtureSeedRequest\x12\x0e\n" +
	"\x02ir\x18\x01 \x01(\fR\x02ir\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\"d\n" +
	"\x17FetchFixtureSeedRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"O\n" +
	"\x18FetchFixtureSeedResponse\x123\n" +
	"\n" +
	"statements\x18\x01 \x03(\v2\x13.w17.apply.SeedStmtR\n" +
	"statements\"H\n" +
	"\bSeedStmt\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12*\n" +
	"\x04args\x18\x02 \x03(\v2\x16.google.protobuf.ValueR\x04args\"Q\n" +
	"\x18FetchFixtureFilesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"I\n" +
	"\x19FetchFixtureFilesResponse\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.w17.apply.FixtureFileR\x05files\"j\n" +
	"\vFixtureFile\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x05R\browCount2j\n" +
	"\x0eMigrationFetch\x12X\n" +
	"\x0fFetchMigrations\x12!.w17.apply.FetchMigrationsRequest\x1a\".w17.apply.FetchMigrationsResponse2\xaa\x02\n" +
	"\fFixtureFetch\x12[\n" +
	"\x10FetchFixtureSeed\x12\".w17.apply.FetchFixtureSeedRequest\x1a#.w17.apply.FetchFixtureSeedResponse\x12^\n" +
	"\x11FetchFixtureFiles\x12#.w17.apply.FetchFixtureFilesRequest\x1a$.w17.apply.FetchFixtureFilesResponse\x12]\n" +
	"\x11RenderFixtureSeed\x12#.w17.apply.RenderFixtureSeedRequest\x1a#.w17.apply.FetchFixtureSeedResponseBAZ?github.com/wandering-compiler/sdk/go/pb/applyfetch;applyfetchpbb\x06proto3"

var (
	file_w17apply_fetch_proto_rawDescOnce sync.Once
	file_w17apply_fetch_proto_rawDescData []byte
)

func file_w17apply_fetch_proto_rawDescGZIP() []byte {
	file_w17apply_fetch_proto_rawDescOnce.Do(func() {
		file_w17apply_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17apply_fetch_proto_rawDesc), len(file_w17apply_fetch_proto_rawDesc)))
	})
	return file_w17apply_fetch_proto_rawDescData
}

var file_w17apply_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_w17apply_fetch_proto_goTypes = []any{
	(*FetchMigrationsRequest)(nil),    // 0: w17.apply.FetchMigrationsRequest
	(*Target)(nil),                    // 1: w17.apply.Target
	(*FetchMigrationsResponse)(nil),   // 2: w17.apply.FetchMigrationsResponse
	(*Migration)(nil),                 // 3: w17.apply.Migration
	(*RenderFixtureSeedRequest)(nil),  // 4: w17.apply.RenderFixtureSeedRequest
	(*FetchFixtureSeedRequest)(nil),   // 5: w17.apply.FetchFixtureSeedRequest
	(*FetchFixtureSeedResponse)(nil),  // 6: w17.apply.FetchFixtureSeedResponse
	(*SeedStmt)(nil),                  // 7: w17.apply.SeedStmt
	(*FetchFixtureFilesRequest)(nil),  // 8: w17.apply.FetchFixtureFilesRequest
	(*FetchFixtureFilesResponse)(nil), // 9: w17.apply.FetchFixtureFilesResponse
	(*FixtureFile)(nil),               // 10: w17.apply.FixtureFile
	(*structpb.Value)(nil),            // 11: google.protobuf.Value
}
var file_w17apply_fetch_proto_depIdxs = []int32{
	1,  // 0: w17.apply.FetchMigrationsRequest.targets:type_name -> w17.apply.Target
	3,  // 1: w17.apply.FetchMigrationsResponse.migrations:type_name -> w17.apply.Migration
	7,  // 2: w17.apply.FetchFixtureSeedResponse.statements:type_name -> w17.apply.SeedStmt
	11, // 3: w17.apply.SeedStmt.args:type_name -> google.protobuf.Value
	10, // 4: w17.apply.FetchFixtureFilesResponse.files:type_name -> w17.apply.FixtureFile
	0,  // 5: w17.apply.MigrationFetch.FetchMigrations:input_type -> w17.apply.FetchMigrationsRequest
	5,  // 6: w17.apply.FixtureFetch.FetchFixtureSeed:input_type -> w17.apply.FetchFixtureSeedRequest
	8,  // 7: w17.apply.FixtureFetch.FetchFixtureFiles:input_type -> w17.apply.FetchFixtureFilesRequest
	4,  // 8: w17.apply.FixtureFetch.RenderFixtureSeed:input_type -> w17.apply.RenderFixtureSeedRequest
	2,  // 9: w17.apply.MigrationFetch.FetchMigrations:output_type -> w17.apply.FetchMigrationsResponse
	6,  // 10: w17.apply.FixtureFetch.FetchFixtureSeed:output_type -> w17.apply.FetchFixtureSeedResponse
	9,  // 11: w17.apply.FixtureFetch.FetchFixtureFiles:output_type -> w17.apply.FetchFixtureFilesResponse
	6,  // 12: w17.apply.FixtureFetch.RenderFixtureSeed:output_type -> w17.apply.FetchFixtureSeedResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_w17apply_fetch_proto_init() }
func file_w17apply_fetch_proto_init() {
	if File_w17apply_fetch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17apply_fetch_proto_rawDesc), len(file_w17apply_fetch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_w17apply_fetch_proto_goTypes,
		DependencyIndexes: file_w17apply_fetch_proto_depIdxs,
		MessageInfos:      file_w17apply_fetch_proto_msgTypes,
	}.Build()
	File_w17apply_fetch_proto = out.File
	file_w17apply_fetch_proto_goTypes = nil
	file_w17apply_fetch_proto_depIdxs = nil
}
