// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: w17/admin.proto

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminActionTarget int32

const (
	AdminActionTarget_ADMIN_ACTION_TARGET_UNSPECIFIED AdminActionTarget = 0
	// LIST — bulk action button above the list. Applies to
	// selected rows OR all filtered rows.
	AdminActionTarget_ADMIN_ACTION_TARGET_LIST AdminActionTarget = 1
	// DETAIL — action button on the detail view. Applies to
	// the current row only.
	AdminActionTarget_ADMIN_ACTION_TARGET_DETAIL AdminActionTarget = 2
	// BOTH — renders in both places.
	AdminActionTarget_ADMIN_ACTION_TARGET_BOTH AdminActionTarget = 3
)

// Enum value maps for AdminActionTarget.
var (
	AdminActionTarget_name = map[int32]string{
		0: "ADMIN_ACTION_TARGET_UNSPECIFIED",
		1: "ADMIN_ACTION_TARGET_LIST",
		2: "ADMIN_ACTION_TARGET_DETAIL",
		3: "ADMIN_ACTION_TARGET_BOTH",
	}
	AdminActionTarget_value = map[string]int32{
		"ADMIN_ACTION_TARGET_UNSPECIFIED": 0,
		"ADMIN_ACTION_TARGET_LIST":        1,
		"ADMIN_ACTION_TARGET_DETAIL":      2,
		"ADMIN_ACTION_TARGET_BOTH":        3,
	}
)

func (x AdminActionTarget) Enum() *AdminActionTarget {
	p := new(AdminActionTarget)
	*p = x
	return p
}

func (x AdminActionTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminActionTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_admin_proto_enumTypes[0].Descriptor()
}

func (AdminActionTarget) Type() protoreflect.EnumType {
	return &file_w17_admin_proto_enumTypes[0]
}

func (x AdminActionTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminActionTarget.Descriptor instead.
func (AdminActionTarget) EnumDescriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{0}
}

type AdminInlineLayout int32

const (
	AdminInlineLayout_ADMIN_INLINE_LAYOUT_UNSPECIFIED AdminInlineLayout = 0
	// TABULAR — embedded table with columns inherited from
	// the inline page's `list.columns`. Default.
	AdminInlineLayout_ADMIN_INLINE_LAYOUT_TABULAR AdminInlineLayout = 1
	// STACKED — each child row as a card with detail fields.
	// Useful for one-to-few relationships with rich child
	// detail.
	AdminInlineLayout_ADMIN_INLINE_LAYOUT_STACKED AdminInlineLayout = 2
)

// Enum value maps for AdminInlineLayout.
var (
	AdminInlineLayout_name = map[int32]string{
		0: "ADMIN_INLINE_LAYOUT_UNSPECIFIED",
		1: "ADMIN_INLINE_LAYOUT_TABULAR",
		2: "ADMIN_INLINE_LAYOUT_STACKED",
	}
	AdminInlineLayout_value = map[string]int32{
		"ADMIN_INLINE_LAYOUT_UNSPECIFIED": 0,
		"ADMIN_INLINE_LAYOUT_TABULAR":     1,
		"ADMIN_INLINE_LAYOUT_STACKED":     2,
	}
)

func (x AdminInlineLayout) Enum() *AdminInlineLayout {
	p := new(AdminInlineLayout)
	*p = x
	return p
}

func (x AdminInlineLayout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminInlineLayout) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_admin_proto_enumTypes[1].Descriptor()
}

func (AdminInlineLayout) Type() protoreflect.EnumType {
	return &file_w17_admin_proto_enumTypes[1]
}

func (x AdminInlineLayout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminInlineLayout.Descriptor instead.
func (AdminInlineLayout) EnumDescriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{1}
}

// AdminWidgetKind selects an AdminWidget's rendering.
type AdminWidgetKind int32

const (
	// Unspecified = CUSTOM (a widget with only slot+size).
	AdminWidgetKind_ADMIN_WIDGET_KIND_UNSPECIFIED AdminWidgetKind = 0
	// CUSTOM — a custom JS slot at `overview:widget:<slot>`.
	AdminWidgetKind_ADMIN_WIDGET_KIND_CUSTOM AdminWidgetKind = 1
	// STAT — a declarative aggregated-values panel backed by
	// the `source` query method.
	AdminWidgetKind_ADMIN_WIDGET_KIND_STAT AdminWidgetKind = 2
	// CHART — a declarative chart backed by the `source` query
	// method's repeated rows.
	AdminWidgetKind_ADMIN_WIDGET_KIND_CHART AdminWidgetKind = 3
)

// Enum value maps for AdminWidgetKind.
var (
	AdminWidgetKind_name = map[int32]string{
		0: "ADMIN_WIDGET_KIND_UNSPECIFIED",
		1: "ADMIN_WIDGET_KIND_CUSTOM",
		2: "ADMIN_WIDGET_KIND_STAT",
		3: "ADMIN_WIDGET_KIND_CHART",
	}
	AdminWidgetKind_value = map[string]int32{
		"ADMIN_WIDGET_KIND_UNSPECIFIED": 0,
		"ADMIN_WIDGET_KIND_CUSTOM":      1,
		"ADMIN_WIDGET_KIND_STAT":        2,
		"ADMIN_WIDGET_KIND_CHART":       3,
	}
)

func (x AdminWidgetKind) Enum() *AdminWidgetKind {
	p := new(AdminWidgetKind)
	*p = x
	return p
}

func (x AdminWidgetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminWidgetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_admin_proto_enumTypes[2].Descriptor()
}

func (AdminWidgetKind) Type() protoreflect.EnumType {
	return &file_w17_admin_proto_enumTypes[2]
}

func (x AdminWidgetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminWidgetKind.Descriptor instead.
func (AdminWidgetKind) EnumDescriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{2}
}

// AdminChartKind selects the form a CHART widget draws.
// Trend over an ordered X (time) reads best as LINE / AREA;
// magnitude across categories as BAR; a part-of-whole split
// as DONUT.
type AdminChartKind int32

const (
	// Unspecified — refused on a CHART widget (pick a form
	// deliberately; there is no sensible default).
	AdminChartKind_ADMIN_CHART_KIND_UNSPECIFIED AdminChartKind = 0
	// LINE — one line per series over the X axis.
	AdminChartKind_ADMIN_CHART_KIND_LINE AdminChartKind = 1
	// BAR — one bar group per X value.
	AdminChartKind_ADMIN_CHART_KIND_BAR AdminChartKind = 2
	// AREA — LINE with the area below it filled.
	AdminChartKind_ADMIN_CHART_KIND_AREA AdminChartKind = 3
	// DONUT — one slice per row; exactly one series.
	AdminChartKind_ADMIN_CHART_KIND_DONUT AdminChartKind = 4
)

// Enum value maps for AdminChartKind.
var (
	AdminChartKind_name = map[int32]string{
		0: "ADMIN_CHART_KIND_UNSPECIFIED",
		1: "ADMIN_CHART_KIND_LINE",
		2: "ADMIN_CHART_KIND_BAR",
		3: "ADMIN_CHART_KIND_AREA",
		4: "ADMIN_CHART_KIND_DONUT",
	}
	AdminChartKind_value = map[string]int32{
		"ADMIN_CHART_KIND_UNSPECIFIED": 0,
		"ADMIN_CHART_KIND_LINE":        1,
		"ADMIN_CHART_KIND_BAR":         2,
		"ADMIN_CHART_KIND_AREA":        3,
		"ADMIN_CHART_KIND_DONUT":       4,
	}
)

func (x AdminChartKind) Enum() *AdminChartKind {
	p := new(AdminChartKind)
	*p = x
	return p
}

func (x AdminChartKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminChartKind) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_admin_proto_enumTypes[3].Descriptor()
}

func (AdminChartKind) Type() protoreflect.EnumType {
	return &file_w17_admin_proto_enumTypes[3]
}

func (x AdminChartKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminChartKind.Descriptor instead.
func (AdminChartKind) EnumDescriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{3}
}

type AdminWidgetSize int32

const (
	AdminWidgetSize_ADMIN_WIDGET_SIZE_UNSPECIFIED AdminWidgetSize = 0
	// SMALL — one grid cell (1/3 row width on desktop).
	AdminWidgetSize_ADMIN_WIDGET_SIZE_SMALL AdminWidgetSize = 1
	// MEDIUM — two grid cells (2/3 row width).
	AdminWidgetSize_ADMIN_WIDGET_SIZE_MEDIUM AdminWidgetSize = 2
	// LARGE — full row width.
	AdminWidgetSize_ADMIN_WIDGET_SIZE_LARGE AdminWidgetSize = 3
)

// Enum value maps for AdminWidgetSize.
var (
	AdminWidgetSize_name = map[int32]string{
		0: "ADMIN_WIDGET_SIZE_UNSPECIFIED",
		1: "ADMIN_WIDGET_SIZE_SMALL",
		2: "ADMIN_WIDGET_SIZE_MEDIUM",
		3: "ADMIN_WIDGET_SIZE_LARGE",
	}
	AdminWidgetSize_value = map[string]int32{
		"ADMIN_WIDGET_SIZE_UNSPECIFIED": 0,
		"ADMIN_WIDGET_SIZE_SMALL":       1,
		"ADMIN_WIDGET_SIZE_MEDIUM":      2,
		"ADMIN_WIDGET_SIZE_LARGE":       3,
	}
)

func (x AdminWidgetSize) Enum() *AdminWidgetSize {
	p := new(AdminWidgetSize)
	*p = x
	return p
}

func (x AdminWidgetSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminWidgetSize) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_admin_proto_enumTypes[4].Descriptor()
}

func (AdminWidgetSize) Type() protoreflect.EnumType {
	return &file_w17_admin_proto_enumTypes[4]
}

func (x AdminWidgetSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminWidgetSize.Descriptor instead.
func (AdminWidgetSize) EnumDescriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{4}
}

// AdminApi declares one admin surface — one logical admin
// exposed at one URL prefix, with its own auth wiring + page
// tree + optional nav grouping + optional overview page.
type AdminApi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name of the surface. snake_case identifier;
	// typically "admin". Surfaces in tooling + error
	// diagnostics. Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL prefix the admin SPA + REST surface mount under.
	// Convention: "/admin". Empty = "/admin" default.
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Authentication wiring. ALWAYS required — an admin surface is
	// the privileged CRUD plane over the project's data and must not
	// ship unauthenticated (a network perimeter is not authentication;
	// authenticate + authorize, fail-closed). The gateway parser
	// rejects an admin surface with no auth at parse time. Usually you
	// write nothing here: activating the auth plugin auto-wires
	// login_method + user_lookup via its admin preset (presetinject).
	// Set an explicit block only to point at non-plugin methods.
	// (Authorization — per-endpoint ACL, REV-146 — is layered on top;
	// a superadmin/wildcard role grants the whole catalogue.)
	Auth *AdminAuth `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// Path (relative to the consumer's repo root) to a
	// developer-owned custom JS source directory. Vite picks
	// it up at admin bundle build time; slot keys validated
	// against the spec at codegen. Empty = no custom JS.
	CustomJs string `protobuf:"bytes,4,opt,name=custom_js,json=customJs,proto3" json:"custom_js,omitempty"`
	// i18n default locale — same shape as
	// `RestApi.default_language`. Empty = "en". Must be in
	// the lock-declared `languages[]` (parser-enforced).
	DefaultLanguage string `protobuf:"bytes,5,opt,name=default_language,json=defaultLanguage,proto3" json:"default_language,omitempty"`
	// Admin pages. Order = declaration order; renders flat in
	// nav when `nav[]` is empty, otherwise nav grouping
	// controls display order. At least one page expected
	// (parser warns on empty admin).
	Pages []*AdminPage `protobuf:"bytes,10,rep,name=pages,proto3" json:"pages,omitempty"`
	// Optional nav grouping. When empty, pages render flat in
	// declaration order. When non-empty, every page must be
	// referenced by exactly one group (parser-enforced).
	Nav []*AdminNavGroup `protobuf:"bytes,11,rep,name=nav,proto3" json:"nav,omitempty"`
	// Overview page — landing screen. v1 renders a grid of
	// custom JS slot widgets; generic pre-built widgets
	// (counter / chart / mini-table) parked v2.
	Overview      *AdminOverview `protobuf:"bytes,12,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminApi) Reset() {
	*x = AdminApi{}
	mi := &file_w17_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminApi) ProtoMessage() {}

func (x *AdminApi) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminApi.ProtoReflect.Descriptor instead.
func (*AdminApi) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminApi) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AdminApi) GetAuth() *AdminAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *AdminApi) GetCustomJs() string {
	if x != nil {
		return x.CustomJs
	}
	return ""
}

func (x *AdminApi) GetDefaultLanguage() string {
	if x != nil {
		return x.DefaultLanguage
	}
	return ""
}

func (x *AdminApi) GetPages() []*AdminPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *AdminApi) GetNav() []*AdminNavGroup {
	if x != nil {
		return x.Nav
	}
	return nil
}

func (x *AdminApi) GetOverview() *AdminOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

// AdminAuth declares the thin shim over hand-written storage
// authentication. Admin doesn't generate password hashing or
// JWT issuance — both stay in storage where they belong.
//
// At admin bundle runtime:
//
//	POST /admin/api/authenticate
//	  → delegates to `login_method` (storage owns hashing + JWT)
//	GET  /admin/api/whoami
//	  → delegates to `user_lookup` (returns identity + perms + scopes)
//	every other admin endpoint
//	  → middleware calls `user_lookup`, threads perms + scopes into
//	    gRPC metadata, REV-146 / REV-147 enforce as usual
type AdminAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the gRPC method that authenticates a caller.
	// "<module>.<Service>.<Method>" — same resolution rules as
	// `RestApi.auth_methods[*].ref`. The method must:
	//   - take a request with username + password (or arbitrary
	//     credential — the admin's login form only collects
	//     username + password, but the storage method can map
	//     them onto a richer credential shape internally),
	//   - return a response carrying a JWT-shaped token the SPA
	//     stores in localStorage.
	//
	// Required.
	LoginMethod string `protobuf:"bytes,1,opt,name=login_method,json=loginMethod,proto3" json:"login_method,omitempty"`
	// Reference to the gRPC method that resolves a token back to
	// the caller's identity + permissions + scopes. Called by
	// the admin middleware on every request (cached for the
	// request's lifetime). Response must carry
	// `repeated string permissions` (REV-146) and `map<string,
	// string> scopes` (REV-147) when those features are active.
	// Required.
	UserLookup string `protobuf:"bytes,2,opt,name=user_lookup,json=userLookup,proto3" json:"user_lookup,omitempty"`
	// Optional path (relative to consumer's repo root) to a
	// bootstrap fixture YAML. Applied once at first admin bundle
	// start (idempotent via the `wc_admin_fixture` table in the
	// storage's primary DB). Empty = no fixture, operator
	// creates the first admin user manually via storage RPCs.
	Fixture       string `protobuf:"bytes,3,opt,name=fixture,proto3" json:"fixture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuth) Reset() {
	*x = AdminAuth{}
	mi := &file_w17_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuth) ProtoMessage() {}

func (x *AdminAuth) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuth.ProtoReflect.Descriptor instead.
func (*AdminAuth) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminAuth) GetLoginMethod() string {
	if x != nil {
		return x.LoginMethod
	}
	return ""
}

func (x *AdminAuth) GetUserLookup() string {
	if x != nil {
		return x.UserLookup
	}
	return ""
}

func (x *AdminAuth) GetFixture() string {
	if x != nil {
		return x.Fixture
	}
	return ""
}

// AdminPage declares one administrative page over one model:
// a list view + a detail view + optional bulk actions +
// optional nested inlines.
type AdminPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page identity. CamelCase identifier; surfaces as the URL
	// segment (`/admin/<Name>`) and the spec key. Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Model reference, "<module>.<Type>". Resolves to any
	// top-level message; it is the page's NAMING / TITLE anchor
	// and the source of the PK field-name for `{id}` URL stamping
	// (`id` or `<modelSnake>_id`). It need NOT be a `(w17.db.table)`
	// and need NOT equal the list/detail method item types — list
	// columns come from `list.source`'s response item, detail form
	// fields from the detail method messages (see AdminList.source).
	// Drives the title fallback + FK-picker/inline label rendering.
	// Required.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Per-page title format string override. Empty = inherit
	// model-level `(w17.admin_title)`. Applies only to THIS
	// page's chrome (breadcrumb + list row heading + detail
	// heading); FK pickers + inline labels referencing this
	// page's model continue to use the model-level annotation.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// List view. Optional — pages without a list render the
	// detail directly (useful for singleton resources like
	// "site settings").
	List *AdminList `protobuf:"bytes,10,opt,name=list,proto3" json:"list,omitempty"`
	// Detail view. Required (at minimum a read method) —
	// pages without a detail are filter-only and don't justify
	// the admin tooling overhead.
	Detail *AdminDetail `protobuf:"bytes,11,opt,name=detail,proto3" json:"detail,omitempty"`
	// Bulk actions exposed above the list / on the detail
	// view. v1 supports ids-only and ids+bulk-extras shapes;
	// per-row-input shape parked v2.
	Actions []*AdminAction `protobuf:"bytes,12,rep,name=actions,proto3" json:"actions,omitempty"`
	// Nested inlines — child rows belonging to the current
	// detail row. Layout = embedded table (default) or stacked
	// cards. Read-only by default; write requires explicit
	// create/update/delete method references with parent-id
	// binding owned by the storage method's DQL.
	Inlines       []*AdminInline `protobuf:"bytes,13,rep,name=inlines,proto3" json:"inlines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPage) Reset() {
	*x = AdminPage{}
	mi := &file_w17_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPage) ProtoMessage() {}

func (x *AdminPage) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPage.ProtoReflect.Descriptor instead.
func (*AdminPage) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminPage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminPage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AdminPage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminPage) GetList() *AdminList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AdminPage) GetDetail() *AdminDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *AdminPage) GetActions() []*AdminAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AdminPage) GetInlines() []*AdminInline {
	if x != nil {
		return x.Inlines
	}
	return nil
}

// AdminList declares the list view of one admin page.
type AdminList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage method ref, "<module>.<Service>.<Method>". Must
	// return `repeated <item>` (or a paged carrier per REV-148),
	// where `<item>` is the list's RESPONSE-ITEM message. `<item>`
	// is validated for shape only — it is NEVER compared to
	// `AdminPage.model`, so it may be a read-only PROJECTION message
	// distinct from the page model (and need not be a
	// `(w17.db.table)`). `columns` and `refs` are sourced from
	// `<item>`'s fields, so joined / computed display values — a DQL
	// `LEFT JOIN ... o.name AS organization_name`, a `CONCAT`/`CASE`
	// projection — belong on `<item>` as plain fields: no table
	// column, no `exclude`. (Only when `<item>` IS a `(w17.db.table)`
	// model does a display-only field need `(w17.db.column) = {
	// exclude: true }`; a dedicated projection item avoids that.)
	// The method's request signature determines the filter / search UI
	// (via `(w17.admin_filter)` / `(w17.admin_search)` tags). Column
	// SORT is not tag-driven: it is auto-derived from this method's DQL
	// SELECT projection (plain-column projections on NOT NULL columns
	// are sortable), overridable per column via `AdminColumn.sortable` /
	// `sort_key`. Required.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Columns to render, in declared order — one AdminColumn per
	// column. Each column names a response-item field and optionally
	// carries a header `label` override and/or a foreign-key `ref`.
	// Default (when empty) = all scalar fields of the response item,
	// in proto declaration order (Django `list_display` default). A
	// bare `{ name: "field" }` behaves exactly like the old plain
	// column: humanized header, raw scalar cell.
	Columns []*AdminColumn `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Which column carries the click-through link to the
	// detail page. Must match a column `name` (or a default
	// column when `columns` is empty). Empty = first column.
	DetailLinkColumn string `protobuf:"bytes,3,opt,name=detail_link_column,json=detailLinkColumn,proto3" json:"detail_link_column,omitempty"`
	// Default sort field — must match a sortable field of the
	// source request. Empty = storage method's default
	// (per its proto default value).
	DefaultSort   string `protobuf:"bytes,4,opt,name=default_sort,json=defaultSort,proto3" json:"default_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminList) Reset() {
	*x = AdminList{}
	mi := &file_w17_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminList) ProtoMessage() {}

func (x *AdminList) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminList.ProtoReflect.Descriptor instead.
func (*AdminList) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminList) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AdminList) GetColumns() []*AdminColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *AdminList) GetDetailLinkColumn() string {
	if x != nil {
		return x.DetailLinkColumn
	}
	return ""
}

func (x *AdminList) GetDefaultSort() string {
	if x != nil {
		return x.DefaultSort
	}
	return ""
}

// AdminColumn declares one list column: the response-item field to
// render, plus optional presentation. It unifies what used to be the
// plain `columns` string, the per-column `column_labels` header
// override, and the `refs` foreign-key annotation into a single
// declaration — so everything about a column lives in one place.
//
//	{ name: "created_at" }                                  // plain
//	{ name: "owner", label: "Account owner" }               // header override
//	{ name: "org_id", label: "Organization",                // FK link
//	  ref: { title: "org_name", page: "Organizations" } }
type AdminColumn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response-item field this column renders. Carries the raw scalar
	// (or, with `ref`, the foreign-key id). Must exist on the list
	// method's response item type; unique within `columns`. Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Header text rendered verbatim (no humanization). Django
	// `verbose_name` analog — use it when the projected field is named
	// for the query (`owner`, `org_id`) but the human header wants
	// different words ("Account owner", "Organization"). Must be
	// non-empty when set. Empty (default) = header humanized from
	// `name` (`org_id` → "Org ID").
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Foreign-key reference — promotes this column to a human-readable,
	// click-through link to another admin page. When set, the cell
	// renders the referenced row's human title (read ROW-LOCALLY via
	// `ref.title`) instead of the raw id, and links to `ref.page`'s
	// detail view. Absent (default) = the column renders its raw
	// scalar. See AdminColumnRef.
	Ref *AdminColumnRef `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	// Column sortability override. DQL is the single source of truth:
	// the admin codegen auto-derives sortability from the list method's
	// SELECT projection — a column that maps to a PLAIN column reference
	// (no expression / CASE / concat / function) on a NOT NULL column is
	// auto-sortable; a computed / nullable projection is not. This
	// tri-state field overrides that default:
	//   - unset (default) → auto-derive from the DQL projection.
	//   - false           → force NOT sortable (e.g. an unindexed big
	//     string on a huge table where a sort scan is
	//     undesirable even though it's a plain column).
	//   - true            → force sortable; REQUIRES `sort_key` to name
	//     the underlying ORDER BY column (the codegen
	//     cannot infer a fragment for a projection it
	//     did not classify as a plain column).
	//
	// The (w17.admin_sortable) field tag is superseded by this DQL-driven
	// derivation and is no longer consulted.
	Sortable *bool `protobuf:"varint,4,opt,name=sortable,proto3,oneof" json:"sortable,omitempty"`
	// Explicit ORDER BY column fragment for this column, in
	// `<alias>.<column>` form (e.g. "u.created_at"). Normally derived
	// automatically from the DQL projection; set it only to (a) satisfy
	// `sortable: true` on a column the codegen could not classify, or
	// (b) redirect a display column to sort by a different underlying
	// column — the canonical case is an FK column whose cell shows a
	// joined display alias (`organization_name`) but should sort by the
	// real joined column (`o.name`). Empty (default) = use the derived
	// fragment. Ignored when the column resolves to not-sortable.
	SortKey       string `protobuf:"bytes,5,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminColumn) Reset() {
	*x = AdminColumn{}
	mi := &file_w17_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminColumn) ProtoMessage() {}

func (x *AdminColumn) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminColumn.ProtoReflect.Descriptor instead.
func (*AdminColumn) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminColumn) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminColumn) GetRef() *AdminColumnRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *AdminColumn) GetSortable() bool {
	if x != nil && x.Sortable != nil {
		return *x.Sortable
	}
	return false
}

func (x *AdminColumn) GetSortKey() string {
	if x != nil {
		return x.SortKey
	}
	return ""
}

// AdminColumnRef promotes the column carrying it to a foreign-key
// link: the cell renders the referenced row's human title (in place
// of the raw id held by the column's `name` field) and links to the
// target page's detail view.
//
// Resolution is ROW-LOCAL: the title is read from a field the SAME
// list method already returns (a denormalized projection — e.g. a
// DQL JOIN yielding `organization_name` next to `org_id`). The
// runtime does not fetch the referenced row — there is no id→row
// resolver and no cross-page N+1. When `title` is empty the cell
// shows the raw id value; the link (when `page` is set) still works.
type AdminColumnRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field (or dotted path) on the SAME list item carrying the
	// referenced row's human title — e.g. "organization_name" or
	// "organization.name". Resolved row-locally against the list
	// response (curly braces optional; a bare path is treated as
	// "{path}"). The list method must project it. Empty = render
	// the raw id value of the column's `name` field. Optional.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Target admin page to link the cell to (its detail view,
	// `/<page>/<id>` where id is the value of the column's `name`
	// field). Must match an AdminPage.name in the same admin_api.
	// Empty = no link (title / id renders as plain text). Optional.
	//
	// Explicit by design: the referenced page is NOT inferred
	// from DQL foreign-key metadata. FK annotations live on
	// `(w17.db.column).fk` at the storage-model layer as
	// `<table>.<column>`, and admin list responses are commonly
	// denormalized projections (DTOs) that carry no
	// `(w17.db.column)` at all — so there is frequently nothing
	// to infer from. Naming the page directly is also unambiguous
	// when two pages render the same model.
	Page          string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminColumnRef) Reset() {
	*x = AdminColumnRef{}
	mi := &file_w17_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminColumnRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminColumnRef) ProtoMessage() {}

func (x *AdminColumnRef) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminColumnRef.ProtoReflect.Descriptor instead.
func (*AdminColumnRef) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminColumnRef) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminColumnRef) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

// AdminDetail declares the detail view of one admin page.
type AdminDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage method ref — read one row. Returns a single
	// <model> instance. Required.
	Read string `protobuf:"bytes,1,opt,name=read,proto3" json:"read,omitempty"`
	// Storage method ref — update. Optional; absent = detail
	// is read-only (no edit form, no save button).
	Update string `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	// Storage method ref — delete. Optional; absent = no
	// delete button on the detail view.
	Delete string `protobuf:"bytes,3,opt,name=delete,proto3" json:"delete,omitempty"`
	// Subset of update-request fields rendered as editable
	// form fields. Default (when both `fields` and `fieldsets`
	// are empty) = all fields of the update request in proto
	// declaration order (Django ModelForm default). Authors
	// prune by listing `fields` once they decide what's
	// relevant.
	Fields []string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	// Fields rendered as disabled inputs, sourced from the
	// `read` response. NOT sent in update requests. A field
	// listed here does not need to be in the update request
	// message — it only needs to be in the read response.
	// A field both in `fields` and `readonly_fields` is a
	// parse error.
	ReadonlyFields []string `protobuf:"bytes,5,rep,name=readonly_fields,json=readonlyFields,proto3" json:"readonly_fields,omitempty"`
	// Grouped fieldsets. When non-empty, replaces flat
	// `fields` rendering with sections (title + collapsible).
	// `readonly_fields` continues to apply orthogonally.
	// Every field in fieldsets must exist in the update
	// request message.
	Fieldsets []*AdminFieldset `protobuf:"bytes,6,rep,name=fieldsets,proto3" json:"fieldsets,omitempty"`
	// Storage method ref — create a new root row. Optional;
	// absent = no "Add" button on the list view and no create
	// form (the Django "add permission absent" shape).
	//
	// Form shape (v1): the create form renders every
	// client-settable field of the CREATE request, in proto
	// declaration order. `fields` / `fieldsets` /
	// `readonly_fields` describe the UPDATE form and do NOT
	// narrow create — they are validated against the update
	// request and the read response, which are different
	// messages (a create request has no `id`, and may require
	// fields the update path never touches).
	//
	// That is deliberate rather than incidental: narrowing a
	// create form to a subset while the mutation still
	// persists the omitted fields is exactly the
	// mass-assignment shape Q46-admin-1 / Q65-admin-1 refuse
	// for update. Rendering the full create request keeps the
	// form and the mutation in agreement by construction. A
	// separate `create_fields` can narrow it later, with the
	// matching guard.
	//
	// ACL: gated like any other admin write. The cascade
	// derives the model-axis action from the method-name
	// prefix, so name the method `Create*` or `Add*` to get a
	// `<Model>#add` permission allocated.
	Create        string `protobuf:"bytes,7,opt,name=create,proto3" json:"create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDetail) Reset() {
	*x = AdminDetail{}
	mi := &file_w17_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDetail) ProtoMessage() {}

func (x *AdminDetail) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDetail.ProtoReflect.Descriptor instead.
func (*AdminDetail) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminDetail) GetRead() string {
	if x != nil {
		return x.Read
	}
	return ""
}

func (x *AdminDetail) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *AdminDetail) GetDelete() string {
	if x != nil {
		return x.Delete
	}
	return ""
}

func (x *AdminDetail) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminDetail) GetReadonlyFields() []string {
	if x != nil {
		return x.ReadonlyFields
	}
	return nil
}

func (x *AdminDetail) GetFieldsets() []*AdminFieldset {
	if x != nil {
		return x.Fieldsets
	}
	return nil
}

func (x *AdminDetail) GetCreate() string {
	if x != nil {
		return x.Create
	}
	return ""
}

// AdminFieldset is one grouped section of fields in an
// AdminDetail.
type AdminFieldset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Section title (rendered as a section heading). Empty =
	// unnamed section (renders fields with no heading).
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Fields in this section, in declared order.
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// Render collapsed by default. Default false.
	Collapsed     bool `protobuf:"varint,3,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFieldset) Reset() {
	*x = AdminFieldset{}
	mi := &file_w17_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFieldset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFieldset) ProtoMessage() {}

func (x *AdminFieldset) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFieldset.ProtoReflect.Descriptor instead.
func (*AdminFieldset) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminFieldset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminFieldset) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminFieldset) GetCollapsed() bool {
	if x != nil {
		return x.Collapsed
	}
	return false
}

// AdminAction declares a bulk action over an admin list /
// detail row.
//
// Wire contract: the bound source method's request must have
// a `repeated string ids` field (matched by name). Additional
// fields beyond `ids` are bulk extras and must be enumerated
// in `fields[]`.
type AdminAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action identifier. snake_case. URL fragment + slot key
	// root.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Storage method ref. Request must have `repeated string
	// ids`; response is empty / status only (action result is
	// not displayed in v1, only success / failure).
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Subset of action-request extras (everything beyond
	// `ids`) to render in the bulk modal. Required (no
	// default) — defaulting to "all" would surface internal
	// fields in bulk modals. Empty list = action takes only
	// `ids[]`.
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Button label. Empty = humanized `name` (e.g. "mark_paid"
	// → "Mark paid").
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// Confirmation modal message. Empty = no confirmation
	// (button submits directly).
	Confirm string `protobuf:"bytes,5,opt,name=confirm,proto3" json:"confirm,omitempty"`
	// Where the action appears in the UI. Default LIST.
	Target        AdminActionTarget `protobuf:"varint,6,opt,name=target,proto3,enum=w17.AdminActionTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAction) Reset() {
	*x = AdminAction{}
	mi := &file_w17_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAction) ProtoMessage() {}

func (x *AdminAction) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAction.ProtoReflect.Descriptor instead.
func (*AdminAction) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminAction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminAction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AdminAction) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminAction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminAction) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *AdminAction) GetTarget() AdminActionTarget {
	if x != nil {
		return x.Target
	}
	return AdminActionTarget_ADMIN_ACTION_TARGET_UNSPECIFIED
}

// AdminInline declares a nested list of related rows under
// the parent detail view.
type AdminInline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to another AdminPage by `name`. Must exist in
	// the same admin_api.
	Page string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// Storage method ref — lists child rows for the current
	// parent row. Accepts the parent's id (or a richer DQL
	// relation embedded in the storage method) and returns
	// child rows of the referenced page's model.
	Link string `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	// Render layout. Default TABULAR.
	Layout AdminInlineLayout `protobuf:"varint,3,opt,name=layout,proto3,enum=w17.AdminInlineLayout" json:"layout,omitempty"`
	// Section label above the inline. Empty = inherit child
	// page's plural title.
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// Storage method ref — create a child row. Request must
	// accept the parent's id. Optional; absent = inline does
	// not support row creation.
	Create string `protobuf:"bytes,10,opt,name=create,proto3" json:"create,omitempty"`
	// Storage method ref — update one inline row. Optional.
	Update string `protobuf:"bytes,11,opt,name=update,proto3" json:"update,omitempty"`
	// Storage method ref — delete one inline row. Optional.
	Delete_       string `protobuf:"bytes,12,opt,name=delete_,json=delete,proto3" json:"delete_,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInline) Reset() {
	*x = AdminInline{}
	mi := &file_w17_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInline) ProtoMessage() {}

func (x *AdminInline) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInline.ProtoReflect.Descriptor instead.
func (*AdminInline) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminInline) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *AdminInline) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *AdminInline) GetLayout() AdminInlineLayout {
	if x != nil {
		return x.Layout
	}
	return AdminInlineLayout_ADMIN_INLINE_LAYOUT_UNSPECIFIED
}

func (x *AdminInline) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminInline) GetCreate() string {
	if x != nil {
		return x.Create
	}
	return ""
}

func (x *AdminInline) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *AdminInline) GetDelete_() string {
	if x != nil {
		return x.Delete_
	}
	return ""
}

// AdminNavGroup buckets pages under a labeled section in
// the left nav.
type AdminNavGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group title (UI label). Required.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Page names referenced from this group. Each must match
	// an AdminPage.name in the same admin_api. Order =
	// display order within the group.
	Pages         []string `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminNavGroup) Reset() {
	*x = AdminNavGroup{}
	mi := &file_w17_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNavGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNavGroup) ProtoMessage() {}

func (x *AdminNavGroup) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNavGroup.ProtoReflect.Descriptor instead.
func (*AdminNavGroup) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminNavGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminNavGroup) GetPages() []string {
	if x != nil {
		return x.Pages
	}
	return nil
}

// AdminOverview declares the overview / landing page of
// the admin. Widgets render as a grid, in declared order.
// When NO overview is declared the runtime still shows a
// default landing: a tile per nav group listing its pages
// (with a row count for paged lists). Declaring >=1 widget
// replaces those default tiles with the widget grid.
type AdminOverview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Widgets rendered on the overview, in declared order.
	// Empty = the default group tiles render instead.
	Widgets       []*AdminWidget `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminOverview) Reset() {
	*x = AdminOverview{}
	mi := &file_w17_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOverview) ProtoMessage() {}

func (x *AdminOverview) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOverview.ProtoReflect.Descriptor instead.
func (*AdminOverview) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminOverview) GetWidgets() []*AdminWidget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

// AdminWidget is one overview card. Its `kind` selects the
// behavior:
//   - CUSTOM (default): a custom JS slot the runtime calls
//     at `overview:widget:<slot>`; the project supplies the
//     implementation. Missing slot at runtime = the card is
//     dropped (warns in dev).
//   - STAT: a declarative aggregated-values panel — the
//     runtime fetches the `source` query method and renders
//     each `values` entry as a stat cell. Zero project JS.
//   - CHART: a declarative chart — the runtime fetches the
//     `source` query method, reads its repeated rows and
//     plots `series` (Y) against `x_field` (X). Zero project
//     JS.
type AdminWidget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slot id — the widget's unique identifier on the overview
	// (snake_case). For CUSTOM it is the JS slot key; for STAT
	// it names the generated data route `/api/widget/<slot>`.
	Slot string `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Layout size hint.
	Size AdminWidgetSize `protobuf:"varint,2,opt,name=size,proto3,enum=w17.AdminWidgetSize" json:"size,omitempty"`
	// Widget kind. Unspecified = CUSTOM (back-compat: a widget
	// declared with only slot+size stays a custom JS slot).
	Kind AdminWidgetKind `protobuf:"varint,3,opt,name=kind,proto3,enum=w17.AdminWidgetKind" json:"kind,omitempty"`
	// Card title shown above the widget (STAT/CHART). Ignored
	// for CUSTOM, whose component owns its own chrome.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Backing query method ref `<module>.<Service>.<Method>`
	// for a declarative widget (STAT/CHART) — resolved like a
	// page's `list.source`. The generated data route calls it
	// and returns its response as JSON. Empty for CUSTOM.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// STAT: the scalar values to show, in order. Each names a
	// field on the `source` response; the runtime reads it and
	// renders one stat cell (label + value). Empty for other
	// kinds.
	Values []*AdminWidgetValue `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty"`
	// CHART: the chart form. Required for CHART, ignored
	// otherwise.
	ChartKind AdminChartKind `protobuf:"varint,7,opt,name=chart_kind,json=chartKind,proto3,enum=w17.AdminChartKind" json:"chart_kind,omitempty"`
	// CHART: the row field plotted on the category / time axis
	// (X). Names a field on the ROW message — the one
	// `repeated <Msg>` field of the `source` response.
	XField string `protobuf:"bytes,8,opt,name=x_field,json=xField,proto3" json:"x_field,omitempty"`
	// CHART: the numeric row fields plotted as series (Y), in
	// order. Each names a field on the same ROW message. A
	// DONUT takes exactly one series (the slice value, sliced
	// by `x_field`).
	Series        []*AdminWidgetValue `protobuf:"bytes,9,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminWidget) Reset() {
	*x = AdminWidget{}
	mi := &file_w17_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminWidget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminWidget) ProtoMessage() {}

func (x *AdminWidget) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminWidget.ProtoReflect.Descriptor instead.
func (*AdminWidget) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminWidget) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *AdminWidget) GetSize() AdminWidgetSize {
	if x != nil {
		return x.Size
	}
	return AdminWidgetSize_ADMIN_WIDGET_SIZE_UNSPECIFIED
}

func (x *AdminWidget) GetKind() AdminWidgetKind {
	if x != nil {
		return x.Kind
	}
	return AdminWidgetKind_ADMIN_WIDGET_KIND_UNSPECIFIED
}

func (x *AdminWidget) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminWidget) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AdminWidget) GetValues() []*AdminWidgetValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *AdminWidget) GetChartKind() AdminChartKind {
	if x != nil {
		return x.ChartKind
	}
	return AdminChartKind_ADMIN_CHART_KIND_UNSPECIFIED
}

func (x *AdminWidget) GetXField() string {
	if x != nil {
		return x.XField
	}
	return ""
}

func (x *AdminWidget) GetSeries() []*AdminWidgetValue {
	if x != nil {
		return x.Series
	}
	return nil
}

// AdminWidgetValue is one named field projection: a field read
// off the widget's data (a scalar on the STAT response, a
// column on a CHART row) plus an optional display label
// (humanized from the field name when empty).
type AdminWidgetValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field name on the source response message.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Display label. Empty = humanized from `field`.
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminWidgetValue) Reset() {
	*x = AdminWidgetValue{}
	mi := &file_w17_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminWidgetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminWidgetValue) ProtoMessage() {}

func (x *AdminWidgetValue) ProtoReflect() protoreflect.Message {
	mi := &file_w17_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminWidgetValue.ProtoReflect.Descriptor instead.
func (*AdminWidgetValue) Descriptor() ([]byte, []int) {
	return file_w17_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminWidgetValue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AdminWidgetValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var file_w17_admin_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*AdminApi)(nil),
		Field:         50160,
		Name:          "w17.admin_api",
		Tag:           "bytes,50160,opt,name=admin_api",
		Filename:      "w17/admin.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50161,
		Name:          "w17.admin_title",
		Tag:           "bytes,50161,opt,name=admin_title",
		Filename:      "w17/admin.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50162,
		Name:          "w17.admin_filter",
		Tag:           "varint,50162,opt,name=admin_filter",
		Filename:      "w17/admin.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50163,
		Name:          "w17.admin_search",
		Tag:           "varint,50163,opt,name=admin_search",
		Filename:      "w17/admin.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50164,
		Name:          "w17.admin_sortable",
		Tag:           "varint,50164,opt,name=admin_sortable",
		Filename:      "w17/admin.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50165,
		Name:          "w17.admin_bypass_acl",
		Tag:           "varint,50165,opt,name=admin_bypass_acl",
		Filename:      "w17/admin.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// (w17.admin_api) — file-level admin registry. Carries the
	// complete admin surface declaration (auth + pages + nav +
	// overview). A parse with two files carrying `admin_api` is
	// a hard error — one admin surface per domain.
	//
	// optional w17.AdminApi admin_api = 50160;
	E_AdminApi = &file_w17_admin_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// (w17.admin_title) — model-level title format string. Curly-
	// brace field references; e.g. "{first_name} {last_name}
	// ({email})". Field references must match the message's own
	// fields. No expressions, no functions, no extraction to .po
	// (title text contains dynamic data, not msgids).
	//
	// Per-page override sits inside `AdminPage.title` and applies
	// only to that page's own chrome (breadcrumb + heading); FK
	// pickers and inline labels referencing the same model
	// continue to use this annotation.
	//
	// optional string admin_title = 50161;
	E_AdminTitle = &file_w17_admin_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// (w17.admin_filter) — storage request field eligible for
	// filter UI on admin lists. The admin SPA renders the filter
	// input shape from the field's proto type (enum → select,
	// string → text, timestamp → range, bool → checkbox, …).
	// Field is forwarded into the bound list method's request.
	//
	// optional bool admin_filter = 50162;
	E_AdminFilter = &file_w17_admin_proto_extTypes[2]
	// (w17.admin_search) — storage request field eligible for
	// search UI on admin lists. Renders as a single search
	// textbox above the list (debounced); multiple fields tagged
	// search land as the same textbox value (storage method
	// owns the OR semantics).
	//
	// optional bool admin_search = 50163;
	E_AdminSearch = &file_w17_admin_proto_extTypes[3]
	// (w17.admin_sortable) — DEPRECATED / no longer consulted.
	// Sortability is now derived from the list method's DQL SELECT
	// projection (a plain-column projection on a NOT NULL column is
	// auto-sortable), with a per-column `AdminColumn.sortable` /
	// `sort_key` override. The tag is retained only so existing
	// descriptors that still carry it keep parsing; the codegen ignores
	// its value. Do not add new uses.
	//
	// optional bool admin_sortable = 50164;
	//
	// Deprecated: Marked as deprecated in w17/admin.proto.
	E_AdminSortable = &file_w17_admin_proto_extTypes[4]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// (w17.admin_bypass_acl) — admin endpoint opts out of the
	// ACL gate (REV-146). Equivalent to declaring the method
	// exempt from permission checks; the gateway still threads
	// scopes (REV-147) unless those are also bypassed via
	// `(w17.db.bypass_scope)` on the storage side.
	//
	// Use sparingly — admin endpoints that need bypass typically
	// also need scope bypass (super-admin "see everything"
	// shape). The default for admin is fail-closed.
	//
	// optional bool admin_bypass_acl = 50165;
	E_AdminBypassAcl = &file_w17_admin_proto_extTypes[5]
)

var File_w17_admin_proto protoreflect.FileDescriptor

const file_w17_admin_proto_rawDesc = "" +
	"\n" +
	"\x0fw17/admin.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\"\x9e\x02\n" +
	"\bAdminApi\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\"\n" +
	"\x04auth\x18\x03 \x01(\v2\x0e.w17.AdminAuthR\x04auth\x12\x1b\n" +
	"\tcustom_js\x18\x04 \x01(\tR\bcustomJs\x12)\n" +
	"\x10default_language\x18\x05 \x01(\tR\x0fdefaultLanguage\x12$\n" +
	"\x05pages\x18\n" +
	" \x03(\v2\x0e.w17.AdminPageR\x05pages\x12$\n" +
	"\x03nav\x18\v \x03(\v2\x12.w17.AdminNavGroupR\x03nav\x12.\n" +
	"\boverview\x18\f \x01(\v2\x12.w17.AdminOverviewR\boverview\"i\n" +
	"\tAdminAuth\x12!\n" +
	"\flogin_method\x18\x01 \x01(\tR\vloginMethod\x12\x1f\n" +
	"\vuser_lookup\x18\x02 \x01(\tR\n" +
	"userLookup\x12\x18\n" +
	"\afixture\x18\x03 \x01(\tR\afixture\"\xf1\x01\n" +
	"\tAdminPage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\"\n" +
	"\x04list\x18\n" +
	" \x01(\v2\x0e.w17.AdminListR\x04list\x12(\n" +
	"\x06detail\x18\v \x01(\v2\x10.w17.AdminDetailR\x06detail\x12*\n" +
	"\aactions\x18\f \x03(\v2\x10.w17.AdminActionR\aactions\x12*\n" +
	"\ainlines\x18\r \x03(\v2\x10.w17.AdminInlineR\ainlines\"\xc1\x01\n" +
	"\tAdminList\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12*\n" +
	"\acolumns\x18\x02 \x03(\v2\x10.w17.AdminColumnR\acolumns\x12,\n" +
	"\x12detail_link_column\x18\x03 \x01(\tR\x10detailLinkColumn\x12!\n" +
	"\fdefault_sort\x18\x04 \x01(\tR\vdefaultSortJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\x04refsR\rcolumn_labels\"\xa7\x01\n" +
	"\vAdminColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12%\n" +
	"\x03ref\x18\x03 \x01(\v2\x13.w17.AdminColumnRefR\x03ref\x12\x1f\n" +
	"\bsortable\x18\x04 \x01(\bH\x00R\bsortable\x88\x01\x01\x12\x19\n" +
	"\bsort_key\x18\x05 \x01(\tR\asortKeyB\v\n" +
	"\t_sortable\":\n" +
	"\x0eAdminColumnRef\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04page\x18\x02 \x01(\tR\x04page\"\xdc\x01\n" +
	"\vAdminDetail\x12\x12\n" +
	"\x04read\x18\x01 \x01(\tR\x04read\x12\x16\n" +
	"\x06update\x18\x02 \x01(\tR\x06update\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\tR\x06delete\x12\x16\n" +
	"\x06fields\x18\x04 \x03(\tR\x06fields\x12'\n" +
	"\x0freadonly_fields\x18\x05 \x03(\tR\x0ereadonlyFields\x120\n" +
	"\tfieldsets\x18\x06 \x03(\v2\x12.w17.AdminFieldsetR\tfieldsets\x12\x16\n" +
	"\x06create\x18\a \x01(\tR\x06create\"[\n" +
	"\rAdminFieldset\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12\x1c\n" +
	"\tcollapsed\x18\x03 \x01(\bR\tcollapsed\"\xb1\x01\n" +
	"\vAdminAction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x18\n" +
	"\aconfirm\x18\x05 \x01(\tR\aconfirm\x12.\n" +
	"\x06target\x18\x06 \x01(\x0e2\x16.w17.AdminActionTargetR\x06target\"\xc4\x01\n" +
	"\vAdminInline\x12\x12\n" +
	"\x04page\x18\x01 \x01(\tR\x04page\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12.\n" +
	"\x06layout\x18\x03 \x01(\x0e2\x16.w17.AdminInlineLayoutR\x06layout\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x16\n" +
	"\x06create\x18\n" +
	" \x01(\tR\x06create\x12\x16\n" +
	"\x06update\x18\v \x01(\tR\x06update\x12\x17\n" +
	"\adelete_\x18\f \x01(\tR\x06delete\";\n" +
	"\rAdminNavGroup\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05pages\x18\x02 \x03(\tR\x05pages\";\n" +
	"\rAdminOverview\x12*\n" +
	"\awidgets\x18\x01 \x03(\v2\x10.w17.AdminWidgetR\awidgets\"\xce\x02\n" +
	"\vAdminWidget\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12(\n" +
	"\x04size\x18\x02 \x01(\x0e2\x14.w17.AdminWidgetSizeR\x04size\x12(\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x14.w17.AdminWidgetKindR\x04kind\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12-\n" +
	"\x06values\x18\x06 \x03(\v2\x15.w17.AdminWidgetValueR\x06values\x122\n" +
	"\n" +
	"chart_kind\x18\a \x01(\x0e2\x13.w17.AdminChartKindR\tchartKind\x12\x17\n" +
	"\ax_field\x18\b \x01(\tR\x06xField\x12-\n" +
	"\x06series\x18\t \x03(\v2\x15.w17.AdminWidgetValueR\x06series\">\n" +
	"\x10AdminWidgetValue\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label*\x94\x01\n" +
	"\x11AdminActionTarget\x12#\n" +
	"\x1fADMIN_ACTION_TARGET_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ADMIN_ACTION_TARGET_LIST\x10\x01\x12\x1e\n" +
	"\x1aADMIN_ACTION_TARGET_DETAIL\x10\x02\x12\x1c\n" +
	"\x18ADMIN_ACTION_TARGET_BOTH\x10\x03*z\n" +
	"\x11AdminInlineLayout\x12#\n" +
	"\x1fADMIN_INLINE_LAYOUT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bADMIN_INLINE_LAYOUT_TABULAR\x10\x01\x12\x1f\n" +
	"\x1bADMIN_INLINE_LAYOUT_STACKED\x10\x02*\x8b\x01\n" +
	"\x0fAdminWidgetKind\x12!\n" +
	"\x1dADMIN_WIDGET_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ADMIN_WIDGET_KIND_CUSTOM\x10\x01\x12\x1a\n" +
	"\x16ADMIN_WIDGET_KIND_STAT\x10\x02\x12\x1b\n" +
	"\x17ADMIN_WIDGET_KIND_CHART\x10\x03*\x9e\x01\n" +
	"\x0eAdminChartKind\x12 \n" +
	"\x1cADMIN_CHART_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ADMIN_CHART_KIND_LINE\x10\x01\x12\x18\n" +
	"\x14ADMIN_CHART_KIND_BAR\x10\x02\x12\x19\n" +
	"\x15ADMIN_CHART_KIND_AREA\x10\x03\x12\x1a\n" +
	"\x16ADMIN_CHART_KIND_DONUT\x10\x04*\x8c\x01\n" +
	"\x0fAdminWidgetSize\x12!\n" +
	"\x1dADMIN_WIDGET_SIZE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ADMIN_WIDGET_SIZE_SMALL\x10\x01\x12\x1c\n" +
	"\x18ADMIN_WIDGET_SIZE_MEDIUM\x10\x02\x12\x1b\n" +
	"\x17ADMIN_WIDGET_SIZE_LARGE\x10\x03:J\n" +
	"\tadmin_api\x12\x1c.google.protobuf.FileOptions\x18\xf0\x87\x03 \x01(\v2\r.w17.AdminApiR\badminApi:E\n" +
	"\vadmin_title\x12\x1f.google.protobuf.MessageOptions\x18\xf1\x87\x03 \x01(\tR\n" +
	"adminTitle\x88\x01\x01:E\n" +
	"\fadmin_filter\x12\x1d.google.protobuf.FieldOptions\x18\xf2\x87\x03 \x01(\bR\vadminFilter\x88\x01\x01:E\n" +
	"\fadmin_search\x12\x1d.google.protobuf.FieldOptions\x18\xf3\x87\x03 \x01(\bR\vadminSearch\x88\x01\x01:M\n" +
	"\x0eadmin_sortable\x12\x1d.google.protobuf.FieldOptions\x18\xf4\x87\x03 \x01(\bB\x02\x18\x01R\radminSortable\x88\x01\x01:M\n" +
	"\x10admin_bypass_acl\x12\x1e.google.protobuf.MethodOptions\x18\xf5\x87\x03 \x01(\bR\x0eadminBypassAcl\x88\x01\x01B3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_admin_proto_rawDescOnce sync.Once
	file_w17_admin_proto_rawDescData []byte
)

func file_w17_admin_proto_rawDescGZIP() []byte {
	file_w17_admin_proto_rawDescOnce.Do(func() {
		file_w17_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_admin_proto_rawDesc), len(file_w17_admin_proto_rawDesc)))
	})
	return file_w17_admin_proto_rawDescData
}

var file_w17_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_w17_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_w17_admin_proto_goTypes = []any{
	(AdminActionTarget)(0),              // 0: w17.AdminActionTarget
	(AdminInlineLayout)(0),              // 1: w17.AdminInlineLayout
	(AdminWidgetKind)(0),                // 2: w17.AdminWidgetKind
	(AdminChartKind)(0),                 // 3: w17.AdminChartKind
	(AdminWidgetSize)(0),                // 4: w17.AdminWidgetSize
	(*AdminApi)(nil),                    // 5: w17.AdminApi
	(*AdminAuth)(nil),                   // 6: w17.AdminAuth
	(*AdminPage)(nil),                   // 7: w17.AdminPage
	(*AdminList)(nil),                   // 8: w17.AdminList
	(*AdminColumn)(nil),                 // 9: w17.AdminColumn
	(*AdminColumnRef)(nil),              // 10: w17.AdminColumnRef
	(*AdminDetail)(nil),                 // 11: w17.AdminDetail
	(*AdminFieldset)(nil),               // 12: w17.AdminFieldset
	(*AdminAction)(nil),                 // 13: w17.AdminAction
	(*AdminInline)(nil),                 // 14: w17.AdminInline
	(*AdminNavGroup)(nil),               // 15: w17.AdminNavGroup
	(*AdminOverview)(nil),               // 16: w17.AdminOverview
	(*AdminWidget)(nil),                 // 17: w17.AdminWidget
	(*AdminWidgetValue)(nil),            // 18: w17.AdminWidgetValue
	(*descriptorpb.FileOptions)(nil),    // 19: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 20: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 21: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),  // 22: google.protobuf.MethodOptions
}
var file_w17_admin_proto_depIdxs = []int32{
	6,  // 0: w17.AdminApi.auth:type_name -> w17.AdminAuth
	7,  // 1: w17.AdminApi.pages:type_name -> w17.AdminPage
	15, // 2: w17.AdminApi.nav:type_name -> w17.AdminNavGroup
	16, // 3: w17.AdminApi.overview:type_name -> w17.AdminOverview
	8,  // 4: w17.AdminPage.list:type_name -> w17.AdminList
	11, // 5: w17.AdminPage.detail:type_name -> w17.AdminDetail
	13, // 6: w17.AdminPage.actions:type_name -> w17.AdminAction
	14, // 7: w17.AdminPage.inlines:type_name -> w17.AdminInline
	9,  // 8: w17.AdminList.columns:type_name -> w17.AdminColumn
	10, // 9: w17.AdminColumn.ref:type_name -> w17.AdminColumnRef
	12, // 10: w17.AdminDetail.fieldsets:type_name -> w17.AdminFieldset
	0,  // 11: w17.AdminAction.target:type_name -> w17.AdminActionTarget
	1,  // 12: w17.AdminInline.layout:type_name -> w17.AdminInlineLayout
	17, // 13: w17.AdminOverview.widgets:type_name -> w17.AdminWidget
	4,  // 14: w17.AdminWidget.size:type_name -> w17.AdminWidgetSize
	2,  // 15: w17.AdminWidget.kind:type_name -> w17.AdminWidgetKind
	18, // 16: w17.AdminWidget.values:type_name -> w17.AdminWidgetValue
	3,  // 17: w17.AdminWidget.chart_kind:type_name -> w17.AdminChartKind
	18, // 18: w17.AdminWidget.series:type_name -> w17.AdminWidgetValue
	19, // 19: w17.admin_api:extendee -> google.protobuf.FileOptions
	20, // 20: w17.admin_title:extendee -> google.protobuf.MessageOptions
	21, // 21: w17.admin_filter:extendee -> google.protobuf.FieldOptions
	21, // 22: w17.admin_search:extendee -> google.protobuf.FieldOptions
	21, // 23: w17.admin_sortable:extendee -> google.protobuf.FieldOptions
	22, // 24: w17.admin_bypass_acl:extendee -> google.protobuf.MethodOptions
	5,  // 25: w17.admin_api:type_name -> w17.AdminApi
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	25, // [25:26] is the sub-list for extension type_name
	19, // [19:25] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_w17_admin_proto_init() }
func file_w17_admin_proto_init() {
	if File_w17_admin_proto != nil {
		return
	}
	file_w17_admin_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_admin_proto_rawDesc), len(file_w17_admin_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_w17_admin_proto_goTypes,
		DependencyIndexes: file_w17_admin_proto_depIdxs,
		EnumInfos:         file_w17_admin_proto_enumTypes,
		MessageInfos:      file_w17_admin_proto_msgTypes,
		ExtensionInfos:    file_w17_admin_proto_extTypes,
	}.Build()
	File_w17_admin_proto = out.File
	file_w17_admin_proto_goTypes = nil
	file_w17_admin_proto_depIdxs = nil
}
