// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17/cli.proto

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cli declares one CLI command derived from a gRPC method. The
// request / response message types are reused verbatim: request
// fields are bound to positional args + flags, the response is
// printed (JSON by default).
type Cli struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command — the command PATH: whitespace-separated namespace
	// segments, then the action, then optional `<field>`
	// placeholders binding request fields as POSITIONAL arguments.
	//
	// Example: `command: "task project create <name>"` produces
	//
	//	<domain>-cli task project create <name> [--other-field ...]
	//
	// where `name` is taken positionally and every other request
	// field becomes a `--flag`. Repeated positionals (only the last
	// placeholder may bind a `repeated` field) are variadic.
	//
	// Rules (enforced at parse time):
	//   - At least one non-placeholder segment (the action).
	//   - Segments are kebab-or-snake identifiers; placeholders are
	//     `<field>` naming an existing request field.
	//   - Only the last placeholder may bind a `repeated` field.
	//   - The full command path must be unique across the surface;
	//     a token that is a namespace for one command and a leaf
	//     action for another is a collision (hard error).
	//
	// Empty = derive the action from the method name (snake_case)
	// with no namespace and no positional bindings.
	Command       string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cli) Reset() {
	*x = Cli{}
	mi := &file_w17_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cli) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cli) ProtoMessage() {}

func (x *Cli) ProtoReflect() protoreflect.Message {
	mi := &file_w17_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cli.ProtoReflect.Descriptor instead.
func (*Cli) Descriptor() ([]byte, []int) {
	return file_w17_cli_proto_rawDescGZIP(), []int{0}
}

func (x *Cli) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// CliApi declares the CLI surface — the binary-level metadata for
// the generated command-line tools. The picked commands are marked
// inline via `(w17.cli)`; this message carries only surface-level
// identity + knobs.
type CliApi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name of the surface — "default" / "admin". Surfaces in
	// tooling + diagnostics. Must be a snake_case identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of this surface — "v1" / "0.0.0". Free-form string;
	// surfaces in the generated `--version` output. Empty = "v1".
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Human-readable description of the CLI surface. Surfaces in the
	// root `--help` text of both generated binaries. Empty = no
	// description.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CliApi) Reset() {
	*x = CliApi{}
	mi := &file_w17_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CliApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliApi) ProtoMessage() {}

func (x *CliApi) ProtoReflect() protoreflect.Message {
	mi := &file_w17_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliApi.ProtoReflect.Descriptor instead.
func (*CliApi) Descriptor() ([]byte, []int) {
	return file_w17_cli_proto_rawDescGZIP(), []int{1}
}

func (x *CliApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CliApi) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CliApi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_w17_cli_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Cli)(nil),
		Field:         50114,
		Name:          "w17.cli",
		Tag:           "bytes,50114,opt,name=cli",
		Filename:      "w17/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*CliApi)(nil),
		Field:         50115,
		Name:          "w17.cli_api",
		Tag:           "bytes,50115,opt,name=cli_api",
		Filename:      "w17/cli.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// (w17.cli) — expose this RPC as a CLI command. The `command`
	// path declares where the command lands in the namespace tree
	// and which request fields bind as positional arguments; the
	// remaining request fields become `--flags`. Sibling-message
	// shape (vs the bare-bool `(w17.mcp)` / `(w17.rpc)` picks)
	// because the pick must carry the command path.
	//
	// optional w17.Cli cli = 50114;
	E_Cli = &file_w17_cli_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// (w17.cli_api) — file-level option declaring this file as the
	// CLI surface registry. A sentinel carrying the surface's
	// identity + binary metadata; the per-method `(w17.cli)` picks
	// do the wiring. The file declares ZERO messages, like
	// `(w17.rest_api)` (REV-017), `(w17.mcp_api)` (REV-018) and
	// `(w17.rpc_api)` (REV-152).
	//
	// One CLI surface per parse; two files carrying `(w17.cli_api)`
	// is a hard error.
	//
	// optional w17.CliApi cli_api = 50115;
	E_CliApi = &file_w17_cli_proto_extTypes[1]
)

var File_w17_cli_proto protoreflect.FileDescriptor

const file_w17_cli_proto_rawDesc = "" +
	"\n" +
	"\rw17/cli.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\"\x1f\n" +
	"\x03Cli\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"X\n" +
	"\x06CliApi\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription:<\n" +
	"\x03cli\x12\x1e.google.protobuf.MethodOptions\x18\u0087\x03 \x01(\v2\b.w17.CliR\x03cli:D\n" +
	"\acli_api\x12\x1c.google.protobuf.FileOptions\x18Ç\x03 \x01(\v2\v.w17.CliApiR\x06cliApiB3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_cli_proto_rawDescOnce sync.Once
	file_w17_cli_proto_rawDescData []byte
)

func file_w17_cli_proto_rawDescGZIP() []byte {
	file_w17_cli_proto_rawDescOnce.Do(func() {
		file_w17_cli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_cli_proto_rawDesc), len(file_w17_cli_proto_rawDesc)))
	})
	return file_w17_cli_proto_rawDescData
}

var file_w17_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_w17_cli_proto_goTypes = []any{
	(*Cli)(nil),                        // 0: w17.Cli
	(*CliApi)(nil),                     // 1: w17.CliApi
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
	(*descriptorpb.FileOptions)(nil),   // 3: google.protobuf.FileOptions
}
var file_w17_cli_proto_depIdxs = []int32{
	2, // 0: w17.cli:extendee -> google.protobuf.MethodOptions
	3, // 1: w17.cli_api:extendee -> google.protobuf.FileOptions
	0, // 2: w17.cli:type_name -> w17.Cli
	1, // 3: w17.cli_api:type_name -> w17.CliApi
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_w17_cli_proto_init() }
func file_w17_cli_proto_init() {
	if File_w17_cli_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_cli_proto_rawDesc), len(file_w17_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_w17_cli_proto_goTypes,
		DependencyIndexes: file_w17_cli_proto_depIdxs,
		MessageInfos:      file_w17_cli_proto_msgTypes,
		ExtensionInfos:    file_w17_cli_proto_extTypes,
	}.Build()
	File_w17_cli_proto = out.File
	file_w17_cli_proto_goTypes = nil
	file_w17_cli_proto_depIdxs = nil
}
