// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17/client.proto

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvalidateEvent is the wire payload of the reserved
// `w17.invalidate` eventbus topic (C4.4). Storage mutation
// handlers with `(w17.touches_entities)` emit one per success;
// the gateway's `/w17-events` SSE route forwards it as a JSON
// frame; every connected PageClient auto-subscribes (per
// C4.3) and drops cache entries tagged with the matching
// `(group, message)` family.
//
// Wire flow:
//
//	bus.Dispatch(ctx, channel, "w17.invalidate", &InvalidateEvent{
//	    Group: "accounts", Message: "Account", Ids: []string{"acc-1"}})
//	→ gateway forwards as: event: w17.invalidate
//	                       data: {"group":"accounts","message":"Account","ids":["acc-1"]}
//	→ client cache.invalidateByEntityType([{group, message}])
//
// **ids** is informational — the FE client today drops by
// (group, message) family without consulting it. Future
// polish may narrow drops to specific ids when populated.
type InvalidateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateEvent) Reset() {
	*x = InvalidateEvent{}
	mi := &file_w17_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateEvent) ProtoMessage() {}

func (x *InvalidateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_w17_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateEvent.ProtoReflect.Descriptor instead.
func (*InvalidateEvent) Descriptor() ([]byte, []int) {
	return file_w17_client_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidateEvent) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *InvalidateEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvalidateEvent) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var file_w17_client_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50140,
		Name:          "w17.returns_entities",
		Tag:           "bytes,50140,rep,name=returns_entities",
		Filename:      "w17/client.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50141,
		Name:          "w17.touches_entities",
		Tag:           "bytes,50141,rep,name=touches_entities",
		Filename:      "w17/client.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50142,
		Name:          "w17.entity_id",
		Tag:           "varint,50142,opt,name=entity_id",
		Filename:      "w17/client.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// repeated string returns_entities = 50140;
	E_ReturnsEntities = &file_w17_client_proto_extTypes[0]
	// repeated string touches_entities = 50141;
	E_TouchesEntities = &file_w17_client_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool entity_id = 50142;
	E_EntityId = &file_w17_client_proto_extTypes[2]
)

var File_w17_client_proto protoreflect.FileDescriptor

const file_w17_client_proto_rawDesc = "" +
	"\n" +
	"\x10w17/client.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\"S\n" +
	"\x0fInvalidateEvent\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids:K\n" +
	"\x10returns_entities\x12\x1e.google.protobuf.MethodOptions\x18܇\x03 \x03(\tR\x0freturnsEntities:K\n" +
	"\x10touches_entities\x12\x1e.google.protobuf.MethodOptions\x18݇\x03 \x03(\tR\x0ftouchesEntities:<\n" +
	"\tentity_id\x12\x1d.google.protobuf.FieldOptions\x18އ\x03 \x01(\bR\bentityIdB3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_client_proto_rawDescOnce sync.Once
	file_w17_client_proto_rawDescData []byte
)

func file_w17_client_proto_rawDescGZIP() []byte {
	file_w17_client_proto_rawDescOnce.Do(func() {
		file_w17_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_client_proto_rawDesc), len(file_w17_client_proto_rawDesc)))
	})
	return file_w17_client_proto_rawDescData
}

var file_w17_client_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_w17_client_proto_goTypes = []any{
	(*InvalidateEvent)(nil),            // 0: w17.InvalidateEvent
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),  // 2: google.protobuf.FieldOptions
}
var file_w17_client_proto_depIdxs = []int32{
	1, // 0: w17.returns_entities:extendee -> google.protobuf.MethodOptions
	1, // 1: w17.touches_entities:extendee -> google.protobuf.MethodOptions
	2, // 2: w17.entity_id:extendee -> google.protobuf.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_w17_client_proto_init() }
func file_w17_client_proto_init() {
	if File_w17_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_client_proto_rawDesc), len(file_w17_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_w17_client_proto_goTypes,
		DependencyIndexes: file_w17_client_proto_depIdxs,
		MessageInfos:      file_w17_client_proto_msgTypes,
		ExtensionInfos:    file_w17_client_proto_extTypes,
	}.Build()
	File_w17_client_proto = out.File
	file_w17_client_proto_goTypes = nil
	file_w17_client_proto_depIdxs = nil
}
