// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17/domain.proto

// Domain-level configuration option (Phase D of the plugin-system
// implementation plan — `docs/specs/plugins/implementation-plan.md`).
//
// `(w17.domain)` is the cascade sentinel for DOMAIN-scoped settings
// — operations that apply uniformly across every module in a
// domain. Today's surface: plugin activations.
//
// Distinction from `(w17.module)` (in module.proto):
//
//   - `(w17.module)` carries module/domain config that cascades
//     through the standard domain → module → file precedence
//     chain (schema, table_prefix, connection, channels,
//     event_defaults). Loader rejects it outside w17.proto.
//   - `(w17.domain)` carries DOMAIN-ONLY settings that have no
//     module-level analog. Plugin activations are deliberately
//     domain-scoped (per-domain activation lets the same plugin
//     materialize as independent slots in multiple domains —
//     see docs/specs/plugins/activation.md). Loader rejects it
//     anywhere outside `proto/domains/<domain>/w17.proto`.
//
// Why a separate option (rather than rolling into `Module`):
// activation is a domain primitive (a domain ACTIVATES a plugin),
// not a module primitive. Keeping it on a separate option makes
// the "where does this belong?" question answer itself + leaves
// `Module` focused on cascading config.

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain carries every domain-scoped setting. Today: plugin
// activations. Future fields (cross-domain re-exports, domain-
// level observability hooks, …) land here.
type Domain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugins activated for this domain. Each entry materializes
	// the plugin's tables, services, and pb stubs as a synthetic
	// module in this domain. Same plugin may be activated under
	// different domains with different `registered_as` values —
	// each activation is independent.
	//
	// Spec: docs/specs/plugins/activation.md.
	Plugins       []*PluginActivation `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_w17_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_w17_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_w17_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetPlugins() []*PluginActivation {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// PluginActivation is one row of (w17.domain).plugins.
// Identifies WHICH plugin to materialize + WHAT NAME to give
// its module slot in the activating domain.
type PluginActivation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source plugin name — must match an installed plugin in
	// `<proto_dir>/plugins/<source_name>/` (recorded in
	// `lock.plugins[]` by `w17ctl plugin install`). Required.
	SourceName string `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// Local rename of the plugin slot. Defaults to `source_name`
	// when empty. Drives table prefix, Go package alias, pb
	// output dir, and the synthetic module's name in the IR.
	//
	// Does NOT rename the plugin's proto package — the wire
	// identity (derived from `plugin.yaml.name` as
	// `w17.contrib.<name>`) is stable across activations.
	// `registered_as` is the PLACEMENT-layer rename only (see
	// docs/specs/plugins/activation.md §"Naming + paths").
	RegisteredAs string `protobuf:"bytes,2,opt,name=registered_as,json=registeredAs,proto3" json:"registered_as,omitempty"`
	// Connection alias → project connection name. Every alias
	// declared in `plugin.yaml.connections` MUST appear as a key
	// here; every value MUST name a connection declared in
	// `lock.connections[]`. Staging substitutes
	// `(w17.module).connection = "<alias>"` in the plugin's
	// staged proto with the mapped value before IR build.
	//
	// Empty when the plugin's `connections:` list is empty
	// (plugin binds tables to the project's default connection).
	// Spec: docs/specs/plugins/activation.md §"Connection
	// binding via aliases".
	Connections map[string]string `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Channel alias → project channel name. Every alias declared
	// in `plugin.yaml.channels` MUST appear as a key here; every
	// value MUST name a channel declared in this domain's
	// `(w17.module).channels[]` catalogue. Staging substitutes
	// `(w17.event).channel = "<alias>"` in the plugin's staged
	// event proto with the mapped value before IR build.
	//
	// Empty when the plugin's `channels:` list is empty (plugin
	// emits no events). Spec: docs/specs/plugins/activation.md
	// §"Channel binding via aliases".
	Channels map[string]string `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional configuration for plugins shipping a turnkey
	// AuthService.Authenticate RPC. The plugin codegen reads
	// `auth_input.header_name` + `auth_input.scheme` to emit the
	// bearer-token extraction body that drives the auth lookup.
	// Plugins that don't ship an AuthService ignore the field;
	// the orchestrator applies defaults (Authorization / Bearer)
	// when the activation omits it.
	//
	// Spec: docs/specs/plugins/activation.md §"Turnkey auth
	// configuration"; Phase F2 of the auth+acl track.
	AuthInput *AuthInput `protobuf:"bytes,5,opt,name=auth_input,json=authInput,proto3" json:"auth_input,omitempty"`
	// Feature-tag set this activation enables (Phase G2). Wrapper
	// semantics distinguish three states proto3's bare repeated
	// can't:
	//
	//   - field absent: use the plugin's `default: true`
	//     catalogue entries (implicit defaults flow);
	//   - field present, names empty: explicit "nothing tagged"
	//     — emit only untagged baseline;
	//   - field present, names listed: emit exactly these tags.
	//
	// Every listed name MUST appear in the plugin's `plugin.yaml`
	// `features:` catalogue (typo guard at staging time). The
	// staging-time filter drops proto entities (services /
	// methods / messages) whose `(w17.contrib.plugin_feature*)`
	// tag isn't in the resolved set — untagged entities always
	// emit.
	//
	// Spec: docs/specs/plugins/feature-tags.md.
	Features *PluginFeatureSet `protobuf:"bytes,6,opt,name=features,proto3" json:"features,omitempty"`
	// Per-surface controls for the plugin's ADMIN preset. The admin
	// surface (overview widgets, contributed pages, auth auto-wire) is
	// injected by default when the plugin is active — the admin is an
	// internal, auth-required surface, so it stays turnkey. Declare
	// `admin.enabled = false` to opt out and wire the plugin's admin
	// slots by hand.
	//
	// REST and MCP are NOT controlled here: a plugin's `presets.rest` /
	// `presets.mcp` are OFF by default and opted in from the CONSUMING
	// surface's own registry (`(w17.rest_api).include` /
	// `(w17.mcp_api).include`), so the registry stays the single source
	// of truth for what is exposed. See
	// docs/decisions/plugin-surfaces-opt-in.md.
	//
	// Spec: docs/specs/plugins/presets.md.
	Presets       *PresetControls `protobuf:"bytes,7,opt,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginActivation) Reset() {
	*x = PluginActivation{}
	mi := &file_w17_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginActivation) ProtoMessage() {}

func (x *PluginActivation) ProtoReflect() protoreflect.Message {
	mi := &file_w17_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginActivation.ProtoReflect.Descriptor instead.
func (*PluginActivation) Descriptor() ([]byte, []int) {
	return file_w17_domain_proto_rawDescGZIP(), []int{1}
}

func (x *PluginActivation) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *PluginActivation) GetRegisteredAs() string {
	if x != nil {
		return x.RegisteredAs
	}
	return ""
}

func (x *PluginActivation) GetConnections() map[string]string {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *PluginActivation) GetChannels() map[string]string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *PluginActivation) GetAuthInput() *AuthInput {
	if x != nil {
		return x.AuthInput
	}
	return nil
}

func (x *PluginActivation) GetFeatures() *PluginFeatureSet {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PluginActivation) GetPresets() *PresetControls {
	if x != nil {
		return x.Presets
	}
	return nil
}

// PresetControls is the per-surface control for a plugin activation's
// presets. Only the admin surface is controlled here (default-on,
// opt-out); REST/MCP publication is opt-in from the consuming
// registry — see PluginActivation.presets. Spec:
// docs/specs/plugins/presets.md.
type PresetControls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *PresetSurface         `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetControls) Reset() {
	*x = PresetControls{}
	mi := &file_w17_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetControls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetControls) ProtoMessage() {}

func (x *PresetControls) ProtoReflect() protoreflect.Message {
	mi := &file_w17_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetControls.ProtoReflect.Descriptor instead.
func (*PresetControls) Descriptor() ([]byte, []int) {
	return file_w17_domain_proto_rawDescGZIP(), []int{2}
}

func (x *PresetControls) GetAdmin() *PresetSurface {
	if x != nil {
		return x.Admin
	}
	return nil
}

// PresetSurface controls one generated surface's preset injection
// for a plugin activation. Used only for admin today.
type PresetSurface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this surface's preset is injected. Uses field presence
	// (proto3 optional):
	//   - surface message absent  → enabled (default-on);
	//   - present, enabled unset  → enabled;
	//   - present, enabled = false → disabled (opt out + wire by hand).
	Enabled       *bool `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetSurface) Reset() {
	*x = PresetSurface{}
	mi := &file_w17_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetSurface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetSurface) ProtoMessage() {}

func (x *PresetSurface) ProtoReflect() protoreflect.Message {
	mi := &file_w17_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetSurface.ProtoReflect.Descriptor instead.
func (*PresetSurface) Descriptor() ([]byte, []int) {
	return file_w17_domain_proto_rawDescGZIP(), []int{3}
}

func (x *PresetSurface) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// PluginFeatureSet wraps the activation's feature-tag selection
// so callers can distinguish "use defaults" (absent message)
// from "explicit empty" (message present, names empty).
type PluginFeatureSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names — feature tags to enable. The plugin author's
	// `plugin.yaml` `features:` catalogue lists every legal
	// value; staging rejects names absent from the catalogue.
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginFeatureSet) Reset() {
	*x = PluginFeatureSet{}
	mi := &file_w17_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginFeatureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginFeatureSet) ProtoMessage() {}

func (x *PluginFeatureSet) ProtoReflect() protoreflect.Message {
	mi := &file_w17_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginFeatureSet.ProtoReflect.Descriptor instead.
func (*PluginFeatureSet) Descriptor() ([]byte, []int) {
	return file_w17_domain_proto_rawDescGZIP(), []int{4}
}

func (x *PluginFeatureSet) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// AuthInput configures the bearer-token extraction the plugin's
// generated Authenticate handler performs against the request
// headers map. The two knobs cover the two parts of an HTTP
// `Authorization` header: the header NAME (defaults
// "Authorization") and the credential SCHEME stripped off the
// value (defaults "Bearer"). Both have safe defaults so the
// activation can omit the field entirely for the standard
// `Authorization: Bearer <token>` shape.
type AuthInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP header name carrying the credentials. Case-insensitive
	// at runtime (the generated handler lowercases on lookup —
	// gateway convention is lower-case keys in the headers map).
	// Empty defaults to "Authorization".
	HeaderName string `protobuf:"bytes,1,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	// Credential scheme stripped off the header value before the
	// bearer-token resolution runs. Empty defaults to "Bearer".
	// The space separator between scheme and token is implicit:
	// the handler trims `<scheme> ` (with a single space) off the
	// header value's prefix. Set to a literal empty value via
	// explicit `scheme: ""` to disable scheme-stripping (the raw
	// header value becomes the token).
	Scheme        string `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInput) Reset() {
	*x = AuthInput{}
	mi := &file_w17_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInput) ProtoMessage() {}

func (x *AuthInput) ProtoReflect() protoreflect.Message {
	mi := &file_w17_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInput.ProtoReflect.Descriptor instead.
func (*AuthInput) Descriptor() ([]byte, []int) {
	return file_w17_domain_proto_rawDescGZIP(), []int{5}
}

func (x *AuthInput) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *AuthInput) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

var file_w17_domain_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Domain)(nil),
		Field:         51021,
		Name:          "w17.domain",
		Tag:           "bytes,51021,opt,name=domain",
		Filename:      "w17/domain.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional w17.Domain domain = 51021;
	E_Domain = &file_w17_domain_proto_extTypes[0]
)

var File_w17_domain_proto protoreflect.FileDescriptor

const file_w17_domain_proto_rawDesc = "" +
	"\n" +
	"\x10w17/domain.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\"9\n" +
	"\x06Domain\x12/\n" +
	"\aplugins\x18\x01 \x03(\v2\x15.w17.PluginActivationR\aplugins\"\xf1\x03\n" +
	"\x10PluginActivation\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12#\n" +
	"\rregistered_as\x18\x02 \x01(\tR\fregisteredAs\x12H\n" +
	"\vconnections\x18\x03 \x03(\v2&.w17.PluginActivation.ConnectionsEntryR\vconnections\x12?\n" +
	"\bchannels\x18\x04 \x03(\v2#.w17.PluginActivation.ChannelsEntryR\bchannels\x12-\n" +
	"\n" +
	"auth_input\x18\x05 \x01(\v2\x0e.w17.AuthInputR\tauthInput\x121\n" +
	"\bfeatures\x18\x06 \x01(\v2\x15.w17.PluginFeatureSetR\bfeatures\x12-\n" +
	"\apresets\x18\a \x01(\v2\x13.w17.PresetControlsR\apresets\x1a>\n" +
	"\x10ConnectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rChannelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x0ePresetControls\x12(\n" +
	"\x05admin\x18\x03 \x01(\v2\x12.w17.PresetSurfaceR\x05adminJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04restR\x03mcp\"G\n" +
	"\rPresetSurface\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledJ\x04\b\x02\x10\x03R\x05mount\"(\n" +
	"\x10PluginFeatureSet\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"D\n" +
	"\tAuthInput\x12\x1f\n" +
	"\vheader_name\x18\x01 \x01(\tR\n" +
	"headerName\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme:C\n" +
	"\x06domain\x12\x1c.google.protobuf.FileOptions\x18͎\x03 \x01(\v2\v.w17.DomainR\x06domainB3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_domain_proto_rawDescOnce sync.Once
	file_w17_domain_proto_rawDescData []byte
)

func file_w17_domain_proto_rawDescGZIP() []byte {
	file_w17_domain_proto_rawDescOnce.Do(func() {
		file_w17_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_domain_proto_rawDesc), len(file_w17_domain_proto_rawDesc)))
	})
	return file_w17_domain_proto_rawDescData
}

var file_w17_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_w17_domain_proto_goTypes = []any{
	(*Domain)(nil),                   // 0: w17.Domain
	(*PluginActivation)(nil),         // 1: w17.PluginActivation
	(*PresetControls)(nil),           // 2: w17.PresetControls
	(*PresetSurface)(nil),            // 3: w17.PresetSurface
	(*PluginFeatureSet)(nil),         // 4: w17.PluginFeatureSet
	(*AuthInput)(nil),                // 5: w17.AuthInput
	nil,                              // 6: w17.PluginActivation.ConnectionsEntry
	nil,                              // 7: w17.PluginActivation.ChannelsEntry
	(*descriptorpb.FileOptions)(nil), // 8: google.protobuf.FileOptions
}
var file_w17_domain_proto_depIdxs = []int32{
	1, // 0: w17.Domain.plugins:type_name -> w17.PluginActivation
	6, // 1: w17.PluginActivation.connections:type_name -> w17.PluginActivation.ConnectionsEntry
	7, // 2: w17.PluginActivation.channels:type_name -> w17.PluginActivation.ChannelsEntry
	5, // 3: w17.PluginActivation.auth_input:type_name -> w17.AuthInput
	4, // 4: w17.PluginActivation.features:type_name -> w17.PluginFeatureSet
	2, // 5: w17.PluginActivation.presets:type_name -> w17.PresetControls
	3, // 6: w17.PresetControls.admin:type_name -> w17.PresetSurface
	8, // 7: w17.domain:extendee -> google.protobuf.FileOptions
	0, // 8: w17.domain:type_name -> w17.Domain
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	8, // [8:9] is the sub-list for extension type_name
	7, // [7:8] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_w17_domain_proto_init() }
func file_w17_domain_proto_init() {
	if File_w17_domain_proto != nil {
		return
	}
	file_w17_domain_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_domain_proto_rawDesc), len(file_w17_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_w17_domain_proto_goTypes,
		DependencyIndexes: file_w17_domain_proto_depIdxs,
		MessageInfos:      file_w17_domain_proto_msgTypes,
		ExtensionInfos:    file_w17_domain_proto_extTypes,
	}.Build()
	File_w17_domain_proto = out.File
	file_w17_domain_proto_goTypes = nil
	file_w17_domain_proto_depIdxs = nil
}
