// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17/event_subscribers.proto

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventSubscribers — the file-level registry body.
//
// One sentinel file = one logical subscriber surface. By
// default the surface generates a standalone binary at
// `cmd/<domain>-subscribers[-<surface>]/`; set `colocated:
// true` to instead generate a `Register<...>` helper that
// hooks the dispatch arms onto a caller-supplied bus in the
// same process as the emitter. The surface name derives from
// the sentinel filename: `subscribers.proto` → no suffix
// (default surface), `subscribers_audit.proto` → `-audit`,
// etc.
//
// Empty `subscriptions` list = parser warning (a surface with
// no subscriptions ships a binary / Register that immediately
// returns; usually authoring oversight).
type EventSubscribers struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The subscriptions this surface ships. Order is irrelevant
	// at runtime (the dispatcher keys on envelope oneof tag, not
	// list order) but preserved in generated source for
	// diffability.
	Subscriptions []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// Co-located surface — the generated subscriber dispatch
	// runs in-process inside the emit binary rather than as a
	// standalone `cmd/<domain>-subscribers/` binary. The
	// generator emits a `Register<Domain>Subscribers(ctx,
	// factory, invoker) error` helper that wires every channel
	// onto the caller-supplied SubscriberFactory; main() in the
	// emit binary calls Register once at boot.
	//
	// Co-located surfaces unlock MEMORY-channel subscriptions
	// (per spec in-memory-transport.md): emit + handler share
	// one process so the MemoryBus's goroutine fan-out works
	// end-to-end. Standalone surfaces still refuse MEMORY
	// channels at parse time (the binary would be a separate
	// process with no shared bus to dispatch through).
	//
	// Default false (standalone). True flips both the codegen
	// shape + the Phase-5 MEMORY-channel acceptance rule.
	Colocated     bool `protobuf:"varint,2,opt,name=colocated,proto3" json:"colocated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscribers) Reset() {
	*x = EventSubscribers{}
	mi := &file_w17_event_subscribers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscribers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscribers) ProtoMessage() {}

func (x *EventSubscribers) ProtoReflect() protoreflect.Message {
	mi := &file_w17_event_subscribers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscribers.ProtoReflect.Descriptor instead.
func (*EventSubscribers) Descriptor() ([]byte, []int) {
	return file_w17_event_subscribers_proto_rawDescGZIP(), []int{0}
}

func (x *EventSubscribers) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *EventSubscribers) GetColocated() bool {
	if x != nil {
		return x.Colocated
	}
	return false
}

// Subscription — one (event, channel, topic_filter, handler)
// tuple. Resolution rules:
//
//   - event         — ref into the enclosing domain's event index
//     (`<module>.<file>.<message>` or bare-name if
//     unambiguous). Cross-domain = diag.
//   - channel       — direct match against `(w17.module).channels[].name`
//     in the enclosing domain. Unknown channel = diag.
//   - topic_filter  — glob with `*` (single segment) and `**`
//     (multi-segment). Default `**` = match every
//     topic on the channel. Matches against the
//     emitted event's `topic` at delivery time;
//     NATS / REDIS_STREAMS push the filter down
//     to the transport when supported.
//   - handler       — `<module>.<Service>.<Method>` ref into the
//     domain's gRPC service catalogue. Handler's
//     request type must match the event message
//     type (or a supertype the runtime can decode
//     into).
type Subscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ref — see resolution rules above.
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Channel name — see resolution rules above.
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Topic glob — default `**` if empty.
	TopicFilter string `protobuf:"bytes,3,opt,name=topic_filter,json=topicFilter,proto3" json:"topic_filter,omitempty"`
	// Handler ref — see resolution rules above. Subscriber binary
	// invokes this RPC over loopback gRPC for each matched
	// delivery; the same handler may receive calls from non-bus
	// clients too (it's just a normal gRPC method).
	Handler string `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	// Optional subscriber-side retry override. When set, applies
	// ON TOP OF the channel + per-event retry cascade for this
	// specific subscription — useful when one subscriber needs
	// a more aggressive retry tail than its peers consuming the
	// same channel.
	//
	// Presence-aware merge: unset fields fall through to the
	// channel/event/domain cascade (see `Event.retry`).
	Retry         *RetryPolicy `protobuf:"bytes,5,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_w17_event_subscribers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_w17_event_subscribers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_w17_event_subscribers_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Subscription) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Subscription) GetTopicFilter() string {
	if x != nil {
		return x.TopicFilter
	}
	return ""
}

func (x *Subscription) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *Subscription) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

var file_w17_event_subscribers_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*EventSubscribers)(nil),
		Field:         50132,
		Name:          "w17.event_subscribers",
		Tag:           "bytes,50132,opt,name=event_subscribers",
		Filename:      "w17/event_subscribers.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// (w17.event_subscribers) — file-level option declaring this
	// file as a subscriber registry. The compiler reads the
	// subscription list, validates each entry against the
	// enclosing domain's event index + gRPC service catalogue,
	// and generates a standalone subscriber binary for the
	// surface. Other contents of the file are ignored (registry
	// is a pure sentinel, no messages of its own).
	//
	// optional w17.EventSubscribers event_subscribers = 50132;
	E_EventSubscribers = &file_w17_event_subscribers_proto_extTypes[0]
)

var File_w17_event_subscribers_proto protoreflect.FileDescriptor

const file_w17_event_subscribers_proto_rawDesc = "" +
	"\n" +
	"\x1bw17/event_subscribers.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\x1a\x0fw17/event.proto\"i\n" +
	"\x10EventSubscribers\x127\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x11.w17.SubscriptionR\rsubscriptions\x12\x1c\n" +
	"\tcolocated\x18\x02 \x01(\bR\tcolocated\"\xa3\x01\n" +
	"\fSubscription\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12!\n" +
	"\ftopic_filter\x18\x03 \x01(\tR\vtopicFilter\x12\x18\n" +
	"\ahandler\x18\x04 \x01(\tR\ahandler\x12&\n" +
	"\x05retry\x18\x05 \x01(\v2\x10.w17.RetryPolicyR\x05retry:b\n" +
	"\x11event_subscribers\x12\x1c.google.protobuf.FileOptions\x18ԇ\x03 \x01(\v2\x15.w17.EventSubscribersR\x10eventSubscribersB3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_event_subscribers_proto_rawDescOnce sync.Once
	file_w17_event_subscribers_proto_rawDescData []byte
)

func file_w17_event_subscribers_proto_rawDescGZIP() []byte {
	file_w17_event_subscribers_proto_rawDescOnce.Do(func() {
		file_w17_event_subscribers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_event_subscribers_proto_rawDesc), len(file_w17_event_subscribers_proto_rawDesc)))
	})
	return file_w17_event_subscribers_proto_rawDescData
}

var file_w17_event_subscribers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_w17_event_subscribers_proto_goTypes = []any{
	(*EventSubscribers)(nil),         // 0: w17.EventSubscribers
	(*Subscription)(nil),             // 1: w17.Subscription
	(*RetryPolicy)(nil),              // 2: w17.RetryPolicy
	(*descriptorpb.FileOptions)(nil), // 3: google.protobuf.FileOptions
}
var file_w17_event_subscribers_proto_depIdxs = []int32{
	1, // 0: w17.EventSubscribers.subscriptions:type_name -> w17.Subscription
	2, // 1: w17.Subscription.retry:type_name -> w17.RetryPolicy
	3, // 2: w17.event_subscribers:extendee -> google.protobuf.FileOptions
	0, // 3: w17.event_subscribers:type_name -> w17.EventSubscribers
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_w17_event_subscribers_proto_init() }
func file_w17_event_subscribers_proto_init() {
	if File_w17_event_subscribers_proto != nil {
		return
	}
	file_w17_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_event_subscribers_proto_rawDesc), len(file_w17_event_subscribers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_w17_event_subscribers_proto_goTypes,
		DependencyIndexes: file_w17_event_subscribers_proto_depIdxs,
		MessageInfos:      file_w17_event_subscribers_proto_msgTypes,
		ExtensionInfos:    file_w17_event_subscribers_proto_extTypes,
	}.Build()
	File_w17_event_subscribers_proto = out.File
	file_w17_event_subscribers_proto_goTypes = nil
	file_w17_event_subscribers_proto_depIdxs = nil
}
