// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17/rest.proto

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenType (REV-146) — discriminator for the credential-scheme
// router. Gateway classifies the request's Authorization header
// at request time and picks an auth method whose `token_types`
// covers the classified scheme.
//
// v1 set is deliberately small: BEARER + BASIC cover the two
// schemes already nailed down by HTTP RFC 7235; ANY is the
// escape hatch for everything else (X-API-Key headers, session
// cookies, custom proprietary schemes). COOKIE and API_KEY are
// parked — both need configurable name (which cookie? which
// header?) and the right shape for that deserves a separate
// decision pulled by a real fixture.
type TokenType int32

const (
	TokenType_TOKEN_TYPE_UNSPECIFIED TokenType = 0
	// BEARER — Authorization: Bearer <opaque-token>. The standard
	// JWT / opaque-token shape; gateway classifies any request
	// whose Authorization scheme is "Bearer" (case-insensitive)
	// as this type.
	TokenType_TOKEN_TYPE_BEARER TokenType = 1
	// BASIC — Authorization: Basic <base64(user:pass)>. The
	// standard HTTP Basic shape; gateway classifies any request
	// whose Authorization scheme is "Basic" (case-insensitive)
	// as this type.
	TokenType_TOKEN_TYPE_BASIC TokenType = 2
	// ANY — catch-all. Matches any request the scheme classifier
	// didn't pick a specific type for (custom Authorization
	// schemes, missing Authorization header but the method body
	// sniffs another carrier itself such as a cookie or
	// X-API-Key). Use sparingly — the type-routing optimisation
	// disappears for ANY-typed methods since they get invoked
	// for every non-scheme-specific request.
	TokenType_TOKEN_TYPE_ANY TokenType = 3
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "TOKEN_TYPE_BEARER",
		2: "TOKEN_TYPE_BASIC",
		3: "TOKEN_TYPE_ANY",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED": 0,
		"TOKEN_TYPE_BEARER":      1,
		"TOKEN_TYPE_BASIC":       2,
		"TOKEN_TYPE_ANY":         3,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_rest_proto_enumTypes[0].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_w17_rest_proto_enumTypes[0]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{0}
}

// FieldSource picks which HTTP slot the FieldBinding pulls
// from. Auth-context magic ("/users/me/...") deliberately
// isn't here — auth-bound endpoints look like every other
// auth-required endpoint, with the user_id arriving via gRPC
// metadata (REV-017's auth middleware).
type FieldSource int32

const (
	FieldSource_FIELD_SOURCE_UNSPECIFIED FieldSource = 0
	FieldSource_PATH_VAR                 FieldSource = 1
	FieldSource_QUERY_PARAM              FieldSource = 2
	FieldSource_HEADER                   FieldSource = 3
	// FILE_PART — Slice B of the upload feature. The binding
	// pulls bytes from a `multipart/form-data` part of the
	// configured name and routes them through the gateway's
	// streaming upload handler. Target field MUST be typed
	// UPLOADED_FILE / UPLOADED_IMAGE (parser rejects other
	// types). Endpoint MUST set `multipart: true` (parser
	// rejects FILE_PART on non-multipart endpoints).
	// `http_name` defaults to the leaf segment of `ref` —
	// the form-part name the gateway looks for.
	FieldSource_FILE_PART FieldSource = 4
)

// Enum value maps for FieldSource.
var (
	FieldSource_name = map[int32]string{
		0: "FIELD_SOURCE_UNSPECIFIED",
		1: "PATH_VAR",
		2: "QUERY_PARAM",
		3: "HEADER",
		4: "FILE_PART",
	}
	FieldSource_value = map[string]int32{
		"FIELD_SOURCE_UNSPECIFIED": 0,
		"PATH_VAR":                 1,
		"QUERY_PARAM":              2,
		"HEADER":                   3,
		"FILE_PART":                4,
	}
)

func (x FieldSource) Enum() *FieldSource {
	p := new(FieldSource)
	*p = x
	return p
}

func (x FieldSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldSource) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_rest_proto_enumTypes[1].Descriptor()
}

func (FieldSource) Type() protoreflect.EnumType {
	return &file_w17_rest_proto_enumTypes[1]
}

func (x FieldSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldSource.Descriptor instead.
func (FieldSource) EnumDescriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{1}
}

// URLForm picks how the gateway renders URLs for UPLOADED_*
// response fields covered by this DownloadEndpoint. Required
// on every DownloadEndpoint — the parser refuses UNSPECIFIED
// so authors don't accidentally ship the wrong shape.
type URLForm int32

const (
	URLForm_URL_FORM_UNSPECIFIED URLForm = 0 // parse error
	URLForm_URL_FORM_RELATIVE    URLForm = 1
	URLForm_URL_FORM_ABSOLUTE    URLForm = 2
)

// Enum value maps for URLForm.
var (
	URLForm_name = map[int32]string{
		0: "URL_FORM_UNSPECIFIED",
		1: "URL_FORM_RELATIVE",
		2: "URL_FORM_ABSOLUTE",
	}
	URLForm_value = map[string]int32{
		"URL_FORM_UNSPECIFIED": 0,
		"URL_FORM_RELATIVE":    1,
		"URL_FORM_ABSOLUTE":    2,
	}
)

func (x URLForm) Enum() *URLForm {
	p := new(URLForm)
	*p = x
	return p
}

func (x URLForm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (URLForm) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_rest_proto_enumTypes[2].Descriptor()
}

func (URLForm) Type() protoreflect.EnumType {
	return &file_w17_rest_proto_enumTypes[2]
}

func (x URLForm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use URLForm.Descriptor instead.
func (URLForm) EnumDescriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{2}
}

// ContentDisposition picks the value of the
// Content-Disposition response header on download endpoints.
type ContentDisposition int32

const (
	ContentDisposition_CONTENT_DISPOSITION_UNSPECIFIED ContentDisposition = 0 // → INLINE
	ContentDisposition_CONTENT_DISPOSITION_INLINE      ContentDisposition = 1
	ContentDisposition_CONTENT_DISPOSITION_ATTACHMENT  ContentDisposition = 2
)

// Enum value maps for ContentDisposition.
var (
	ContentDisposition_name = map[int32]string{
		0: "CONTENT_DISPOSITION_UNSPECIFIED",
		1: "CONTENT_DISPOSITION_INLINE",
		2: "CONTENT_DISPOSITION_ATTACHMENT",
	}
	ContentDisposition_value = map[string]int32{
		"CONTENT_DISPOSITION_UNSPECIFIED": 0,
		"CONTENT_DISPOSITION_INLINE":      1,
		"CONTENT_DISPOSITION_ATTACHMENT":  2,
	}
)

func (x ContentDisposition) Enum() *ContentDisposition {
	p := new(ContentDisposition)
	*p = x
	return p
}

func (x ContentDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_rest_proto_enumTypes[3].Descriptor()
}

func (ContentDisposition) Type() protoreflect.EnumType {
	return &file_w17_rest_proto_enumTypes[3]
}

func (x ContentDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentDisposition.Descriptor instead.
func (ContentDisposition) EnumDescriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{3}
}

// HttpMethod enumerates the HTTP verbs the gateway emits.
// Adding a verb here must extend the gateway generator's
// route emit; today the five most common are wired. PATCH-as-
// merge / PATCH-as-jsonpatch semantics are the caller's
// responsibility.
type HttpMethod int32

const (
	HttpMethod_HTTP_METHOD_UNSPECIFIED HttpMethod = 0
	HttpMethod_GET                     HttpMethod = 1
	HttpMethod_POST                    HttpMethod = 2
	HttpMethod_PUT                     HttpMethod = 3
	HttpMethod_DELETE                  HttpMethod = 4
	HttpMethod_PATCH                   HttpMethod = 5
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "GET",
		2: "POST",
		3: "PUT",
		4: "DELETE",
		5: "PATCH",
	}
	HttpMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"GET":                     1,
		"POST":                    2,
		"PUT":                     3,
		"DELETE":                  4,
		"PATCH":                   5,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_rest_proto_enumTypes[4].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_w17_rest_proto_enumTypes[4]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{4}
}

// StreamTransport selects the HTTP-side streaming shape for a
// streaming gRPC method. UNSPECIFIED triggers auto-derivation
// from the gRPC streaming kind; the other two are explicit
// picks.
type StreamTransport int32

const (
	StreamTransport_STREAM_TRANSPORT_UNSPECIFIED StreamTransport = 0
	StreamTransport_STREAM_TRANSPORT_SSE         StreamTransport = 1
	StreamTransport_STREAM_TRANSPORT_WS          StreamTransport = 2
)

// Enum value maps for StreamTransport.
var (
	StreamTransport_name = map[int32]string{
		0: "STREAM_TRANSPORT_UNSPECIFIED",
		1: "STREAM_TRANSPORT_SSE",
		2: "STREAM_TRANSPORT_WS",
	}
	StreamTransport_value = map[string]int32{
		"STREAM_TRANSPORT_UNSPECIFIED": 0,
		"STREAM_TRANSPORT_SSE":         1,
		"STREAM_TRANSPORT_WS":          2,
	}
)

func (x StreamTransport) Enum() *StreamTransport {
	p := new(StreamTransport)
	*p = x
	return p
}

func (x StreamTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_w17_rest_proto_enumTypes[5].Descriptor()
}

func (StreamTransport) Type() protoreflect.EnumType {
	return &file_w17_rest_proto_enumTypes[5]
}

func (x StreamTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamTransport.Descriptor instead.
func (StreamTransport) EnumDescriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{5}
}

// RestApi declares one REST surface — one logical API exposed
// at one prefix, with its own identity (name + version), its
// own auth method, and a tree of grouped endpoints / streams.
//
// Multiple `rest_*.proto` files in the same domain produce
// multiple surfaces; each surface gets its own gateway mux at
// codegen time (or its own gateway binary, depending on deploy
// config — to be decided when we ship the multi-surface
// gateway main).
type RestApi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name of the surface — "public" / "admin" /
	// "partner" / "internal". Surfaces in tooling
	// (catalog / OpenAPI summary) and in error diagnostics. Must
	// be a snake_case identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of this surface — "v1" / "v2" / "2026-05-07". Free-
	// form string; surfaces in OpenAPI's `info.version`. Used
	// alongside `name` to disambiguate surfaces in catalog
	// output. Convention is to keep one surface per major
	// version: `rest_v1.proto` + `rest_v2.proto` rather than
	// mixing.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// URL prefix prepended to every group's prefix (and thus
	// every endpoint's path). Convention: `/api/<version>` —
	// e.g. "/api/v1". Empty = no prefix; URLs start at the
	// group's prefix.
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Human-readable description of the API surface. Surfaces
	// verbatim in OpenAPI `info.description`. Empty = no
	// description block; OpenAPI still emits.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// REV-146 — authentication methods for this surface. Each
	// entry references one RPC (by `<module>.<Service>.<Method>`
	// ref) and declares which credential token types it handles.
	// Empty list = surface has no auth middleware; endpoints on
	// such a surface still emit handler code but skip the auth
	// call entirely.
	//
	// Dispatch is by token type (Bearer / Basic / catch-all). The
	// gateway peeks the request's Authorization scheme, picks the
	// first `auth_methods[]` entry whose `token_types` covers the
	// classified scheme, and calls that method. Same-type
	// fall-through is allowed (two Bearer-handling methods → try
	// in declaration order, first success wins); cross-type
	// fall-through never happens (the whole point of the scheme
	// peek is to not invoke a Basic backend when the credential is
	// clearly Bearer). When the classified scheme matches no
	// method (including no ANY-typed catch-all), the request
	// returns 401 without invoking any backend.
	//
	// The named methods must:
	//   - take a request type with at least one field that holds
	//     the bearer header (validated at parse time via the same
	//     path-template binding rules as endpoints), and
	//   - return a response type with a `repeated string
	//     permissions` field whenever any model or endpoint on
	//     this surface has effective ACL (validated at parse time).
	//
	// The auth methods themselves are implicitly excluded from the
	// auth middleware (otherwise the call would recurse).
	AuthMethods []*AuthMethod `protobuf:"bytes,5,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	// Logical sub-groupings of endpoints — typically one group
	// per resource family ("users", "tasks", …) with its own
	// sub-prefix. Empty list = empty surface (parser warns; the
	// file still produces a mux but it has zero routes).
	Groups []*RestGroup `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	// REV-020 — HTTP→gRPC metadata propagation across every
	// endpoint of this surface. Tracing / correlation IDs /
	// baggage. Headers DO NOT appear on request msgs; storage
	// handlers read them via `metadata.FromIncomingContext`.
	// Empty (uninitialized) = use W3C tracing defaults
	// (X-Request-Id, traceparent, tracestate, baggage). Set
	// `extend_defaults: true` to ADD to the default set rather
	// than override it.
	MetadataPropagation *MetadataPropagation `protobuf:"bytes,7,opt,name=metadata_propagation,json=metadataPropagation,proto3" json:"metadata_propagation,omitempty"`
	// REV-149 — i18n default locale for this REST surface. Empty
	// = "en". Must be one of the project's lock-declared
	// `languages[]` (parser-enforced). When set, the gateway:
	//   - auto-installs `Accept-Language → w17-language` into
	//     metadata_propagation.header_renames (unless the author
	//     has already declared an explicit Accept-Language entry,
	//     in which case the author's wins),
	//   - stamps `w17-language: <default_language>` on every
	//     outgoing metadata BEFORE the header rule fires, so
	//     missing / empty Accept-Language falls back to this
	//     default rather than gettext's compile-time "en".
	//
	// Surfaces with different default_language values can coexist
	// in the same domain binary (e.g. `rest_public.proto` →
	// "cs", `rest_admin.proto` → "en") — the matched surface
	// dictates the default for each request.
	DefaultLanguage string `protobuf:"bytes,8,opt,name=default_language,json=defaultLanguage,proto3" json:"default_language,omitempty"`
	// Plugin REST presets opted into this surface. A plugin's
	// `presets.rest` bundle (its endpoint groups — paths, verbs,
	// exclude_auth) is OFF by default: activating a plugin never
	// auto-publishes routes onto your surface. List the plugin here to
	// opt in — the analogue of Django's `include("auth.urls")`. Each
	// entry names the plugin's ACTIVATION name in this domain (its
	// `registered_as`, e.g. "auth"); `mount` optionally relocates the
	// plugin's group prefixes (final = prefix + mount + group.prefix +
	// endpoint.path). Empty = no plugin routes (the default).
	//
	// Note: this controls only the plugin's PUBLISHED routes. The
	// plugin's `auth_methods` (the bearer/gating middleware) and
	// `forward_headers` are injected automatically whenever the plugin
	// is active — they restrict / plumb, they don't expose, so they are
	// not gated by an include. Individual plugin methods can instead be
	// wired by hand as ordinary `groups[].endpoints[]` (by ref) with no
	// include at all.
	//
	// Spec: docs/decisions/plugin-surfaces-opt-in.md.
	Include       []*PluginInclude `protobuf:"bytes,9,rep,name=include,proto3" json:"include,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestApi) Reset() {
	*x = RestApi{}
	mi := &file_w17_rest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestApi) ProtoMessage() {}

func (x *RestApi) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestApi.ProtoReflect.Descriptor instead.
func (*RestApi) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{0}
}

func (x *RestApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestApi) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RestApi) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RestApi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestApi) GetAuthMethods() []*AuthMethod {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

func (x *RestApi) GetGroups() []*RestGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *RestApi) GetMetadataPropagation() *MetadataPropagation {
	if x != nil {
		return x.MetadataPropagation
	}
	return nil
}

func (x *RestApi) GetDefaultLanguage() string {
	if x != nil {
		return x.DefaultLanguage
	}
	return ""
}

func (x *RestApi) GetInclude() []*PluginInclude {
	if x != nil {
		return x.Include
	}
	return nil
}

// PluginInclude opts one plugin's REST preset into a surface. `plugin`
// is the plugin's activation name in this domain (`registered_as`);
// `mount` is an optional URL sub-path prepended to every included
// group prefix (empty = no remount). Spec:
// docs/decisions/plugin-surfaces-opt-in.md.
type PluginInclude struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Mount         string                 `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInclude) Reset() {
	*x = PluginInclude{}
	mi := &file_w17_rest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInclude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInclude) ProtoMessage() {}

func (x *PluginInclude) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInclude.ProtoReflect.Descriptor instead.
func (*PluginInclude) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInclude) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *PluginInclude) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

// AuthMethod (REV-146) — one entry of `RestApi.auth_methods[]`.
// Pairs a method ref with the credential token types the method
// claims to handle. Gateway dispatches per request by peeking
// the Authorization scheme + matching against declared token
// types.
type AuthMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the gRPC method, "<module>.<Service>.<Method>".
	// Same resolution rules as `RestEndpoint.ref` — domain-scoped,
	// cross-domain refs are a parse-time error.
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Token types this method handles. Required (empty list is a
	// parse-time error — declaring an auth method without saying
	// what credentials it accepts is meaningless). Repeating ANY
	// alongside other types is allowed but redundant; the parser
	// emits a warning when ANY coexists with a scheme-specific
	// type on the same method.
	TokenTypes    []TokenType `protobuf:"varint,2,rep,packed,name=token_types,json=tokenTypes,proto3,enum=w17.TokenType" json:"token_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMethod) Reset() {
	*x = AuthMethod{}
	mi := &file_w17_rest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMethod) ProtoMessage() {}

func (x *AuthMethod) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMethod.ProtoReflect.Descriptor instead.
func (*AuthMethod) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMethod) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *AuthMethod) GetTokenTypes() []TokenType {
	if x != nil {
		return x.TokenTypes
	}
	return nil
}

// MetadataPropagation declares which HTTP request headers
// the gateway forwards as gRPC metadata to the backend
// handlers. Headers do not surface on any request message —
// storage handlers read them via `metadata.FromIncomingContext`
// or generated typed accessors.
//
// Forwarding rule: each listed header value lands as gRPC
// metadata under the key `<lowercase>(<header-name>, X- prefix
// stripped)`. `X-Request-Id` → `request-id`; `traceparent` →
// `traceparent`. Multi-valued HTTP headers fan out as
// metadata's per-key list.
//
// Defaults (when this message is unset OR `headers` is empty):
//
//	X-Request-Id, traceparent, tracestate, baggage
//
// W3C trace-context (traceparent / tracestate) + correlation
// (X-Request-Id) + baggage (W3C baggage spec) form the
// distributed-tracing baseline every observability tool
// expects, so the default propagates them out-of-the-box.
type MetadataPropagation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit list of HTTP header names to forward. When set,
	// replaces the W3C default set (unless `extend_defaults`
	// is true). Header names are matched case-insensitively at
	// runtime.
	Headers []string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	// When true, the W3C defaults stay in effect AND `headers`
	// is added on top. When false (default), `headers` (if
	// non-empty) replaces the defaults entirely.
	ExtendDefaults bool `protobuf:"varint,2,opt,name=extend_defaults,json=extendDefaults,proto3" json:"extend_defaults,omitempty"`
	// REV-149 — propagate an HTTP header into a DIFFERENT-named
	// gRPC metadata key. The `headers[]` form above forwards a
	// header verbatim (lowercased, X- prefix stripped); this
	// form is for cases where the HTTP-side and gRPC-side names
	// diverge by convention.
	//
	// Typical use: i18n ships an auto-installed
	// `Accept-Language → w17-language` entry whenever a REST
	// surface declares `default_language`, so the FE talks
	// standard HTTP while the backend reads a w17-namespaced
	// metadata key. Authors can also declare custom mappings
	// (e.g. `X-User-Locale → w17-language`, `X-Tenant-ID →
	// w17-tenant`).
	//
	// Multiple HTTP headers mapping to the same metadata key:
	// last entry wins at runtime (the gateway processes
	// header_renames[] in declaration order, overwriting).
	// Auto-installed entries land BEFORE author entries so the
	// author wins by default.
	HeaderRenames []*HeaderRename `protobuf:"bytes,3,rep,name=header_renames,json=headerRenames,proto3" json:"header_renames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataPropagation) Reset() {
	*x = MetadataPropagation{}
	mi := &file_w17_rest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataPropagation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataPropagation) ProtoMessage() {}

func (x *MetadataPropagation) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataPropagation.ProtoReflect.Descriptor instead.
func (*MetadataPropagation) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataPropagation) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MetadataPropagation) GetExtendDefaults() bool {
	if x != nil {
		return x.ExtendDefaults
	}
	return false
}

func (x *MetadataPropagation) GetHeaderRenames() []*HeaderRename {
	if x != nil {
		return x.HeaderRenames
	}
	return nil
}

// HeaderRename (REV-149) — one HTTP→metadata renaming entry of
// `MetadataPropagation.header_renames[]`. Headers absent on the
// request produce no metadata entry (no empty-string stamping).
// Multi-valued HTTP headers fan out as the metadata key's per-
// value list (matching the verbatim-headers semantic).
type HeaderRename struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP header name. Matched case-insensitively at runtime;
	// the canonical case as declared here is what surfaces in
	// OpenAPI / documentation. Required.
	Http string `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	// Target gRPC metadata key. Lowercase ASCII per gRPC
	// convention (mixed-case keys are silently lowercased by the
	// gRPC library, so the rename loses information when the key
	// varies in case). Required.
	Metadata      string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderRename) Reset() {
	*x = HeaderRename{}
	mi := &file_w17_rest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderRename) ProtoMessage() {}

func (x *HeaderRename) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderRename.ProtoReflect.Descriptor instead.
func (*HeaderRename) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{4}
}

func (x *HeaderRename) GetHttp() string {
	if x != nil {
		return x.Http
	}
	return ""
}

func (x *HeaderRename) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// RestGroup buckets endpoints + streams under a shared sub-
// prefix and surfaces as one OpenAPI tag. Mental model: one
// FastAPI APIRouter / Django app urls.py / Spring
// RouterFunction module.
type RestGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL sub-prefix prepended to every endpoint / stream path
	// in this group. Composes with `RestApi.prefix`:
	//
	//	final URL = <api.prefix> + <group.prefix> + <endpoint.path>
	//
	// Convention is to start with `/` (e.g. "/users", "/tasks");
	// empty is allowed when the group sits at the api root.
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Group description — surfaces verbatim as the OpenAPI tag
	// description for every endpoint in this group. Empty = no
	// description (OpenAPI still emits the tag from the group's
	// prefix).
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Unary endpoints — gRPC methods whose stream qualifier is
	// unary on both sides. Streaming methods placed here are a
	// parse-time error (use `streams:` instead).
	Endpoints []*RestEndpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Streaming endpoints — gRPC methods with at least one
	// streaming qualifier (server-stream / client-stream / bidi).
	// Unary methods placed here are a parse-time error.
	Streams []*RestStream `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	// Download endpoints — read-only HTTP routes that stream
	// stored uploaded blobs (UPLOADED_FILE / UPLOADED_IMAGE
	// fields) directly from the gateway with full HTTP cache
	// semantics (Range / ETag / 304 / Cache-Control /
	// Content-Disposition). Replaces the need for nginx in
	// front of the service for static-asset serving.
	Downloads []*DownloadEndpoint `protobuf:"bytes,5,rep,name=downloads,proto3" json:"downloads,omitempty"`
	// Explicit group identifier — the token the generated client
	// facade exposes (session.<name>.…) and the OpenAPI / AsyncAPI
	// tag use. Empty = derived from `prefix` (camelCase of the
	// prefix segments, e.g. "/task-docs" → "taskDocs"). Set this to
	// override the derived name (e.g. a prefix that slugs badly, or
	// two groups that should share one facade).
	Name          string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestGroup) Reset() {
	*x = RestGroup{}
	mi := &file_w17_rest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestGroup) ProtoMessage() {}

func (x *RestGroup) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestGroup.ProtoReflect.Descriptor instead.
func (*RestGroup) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{5}
}

func (x *RestGroup) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RestGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestGroup) GetEndpoints() []*RestEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RestGroup) GetStreams() []*RestStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *RestGroup) GetDownloads() []*DownloadEndpoint {
	if x != nil {
		return x.Downloads
	}
	return nil
}

func (x *RestGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RestEndpoint binds one unary gRPC method to an HTTP route.
//
// Default body shape: the WHOLE request message is the JSON
// body, MINUS every field bound elsewhere (path template,
// `fields[]`, `query_expand`). The body shortcut `body:
// "<fieldname>"` (REV-020) overrides this — the body becomes
// that one field's contents, unwrapped to top-level JSON.
// Path templates always auto-bind top-level fields whose name
// matches the `{token}`; explicit `fields[]` is the escape
// hatch for non-trivial routing (nested-message fields,
// renames, headers, query params under a different name).
type RestEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the gRPC method, "<module>.<Service>.<Method>".
	// Module is the proto module (matching FK ref shape from
	// REV-015). Resolution is domain-scoped: a `rest.proto` in
	// `proto/domains/<domain>/` may only reference methods
	// declared under the same domain. Cross-domain refs are a
	// parse-time error — cross-domain orchestration belongs in
	// a business facade (which is itself addressed via a ref).
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// HTTP verb. Required.
	Method HttpMethod `protobuf:"varint,2,opt,name=method,proto3,enum=w17.HttpMethod" json:"method,omitempty"`
	// URL template, group-relative. Supports `{name}` placeholders
	// resolved against top-level fields on the referenced
	// method's request message; e.g. `/{user_id}` matches
	// `GET <prefix>/<group>/42` and binds `user_id = 42`.
	// Required, must start with `/`.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Skip the auth middleware for this endpoint even when
	// `RestApi.auth_methods[]` is populated. Use for sign-in /
	// health / metrics endpoints. Default false.
	ExcludeAuth bool `protobuf:"varint,4,opt,name=exclude_auth,json=excludeAuth,proto3" json:"exclude_auth,omitempty"`
	// Response-message field names (proto names — snake_case as
	// declared in the .proto) the gateway clears before
	// marshaling JSON. Hides internal-only fields from REST
	// clients while keeping them on the gRPC contract for admin
	// tools / internal services. Streaming endpoints (i.e.
	// `RestStream`, not this message) don't honor this field.
	ResponseOmitFields []string `protobuf:"bytes,8,rep,name=response_omit_fields,json=responseOmitFields,proto3" json:"response_omit_fields,omitempty"`
	// REV-020 — explicit field-to-HTTP-slot routing. Each
	// entry pulls a request-msg field from a non-body source
	// (path / query / header). Fields not listed here keep
	// their default behavior: top-level fields whose name
	// matches a path template token bind from the path; other
	// top-level scalars decode from the query string; the
	// remainder lands in the JSON body.
	//
	// The `fields[]` list is the escape hatch for non-trivial
	// cases — nested message fields routed to query, headers
	// delivering business-relevant values (idempotency keys,
	// optimistic-concurrency etags), explicit renames where
	// the URL key differs from the proto field name.
	Fields []*FieldBinding `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	// REV-020 — body shape:
	//
	//	""            (default) the JSON body is the whole
	//	              request msg, minus every field bound
	//	              elsewhere via path template / `fields[]`
	//	              / `query_expand`. OpenAPI emits the
	//	              reduced schema; generated body decoder
	//	              only populates the residual fields.
	//
	//	"*"           explicit synonym of "" (whole-msg minus
	//	              routed-out fields).
	//
	//	"<fieldname>" the body IS the contents of `<fieldname>`,
	//	              unwrapped to top-level JSON. The field
	//	              must exist on the request msg and be a
	//	              message-typed or repeated field (scalars
	//	              as bare-JSON bodies are bizarre and
	//	              rejected at parse time). Other fields
	//	              must all be routed via path / query /
	//	              header (otherwise they have nowhere to
	//	              land).
	Body string `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	// REV-020 — submessage-to-query expansion shortcut. Each
	// entry names a request-msg field; every leaf scalar
	// reachable below that field becomes a query parameter at
	// its leaf-segment name. Use for paginated lists where the
	// request msg groups filter / paging fields into nested
	// messages but the URL still wants them flat (`?status=...&
	// page=2&limit=20`). Composes with `fields[]` for selective
	// overrides / renames.
	//
	// Listed submessages are excluded from the body.
	QueryExpand []string `protobuf:"bytes,11,rep,name=query_expand,json=queryExpand,proto3" json:"query_expand,omitempty"`
	// Slice B of the upload feature — flips the gateway
	// handler into multipart/form-data mode. When true, the
	// generated handler:
	//
	//   - Parses the request as `multipart/form-data` instead
	//     of JSON.
	//   - Streams every FILE_PART-bound part to a tmp file
	//     under the configured connection's bucket root,
	//     hashing during write.
	//   - On successful read of all parts, atomically moves
	//     the tmp file to its final hash-derived sub-bucket
	//     path and populates the request msg's
	//     UPLOADED_FILE / UPLOADED_IMAGE field with the
	//     resolved storage handle.
	//   - JSON-bearing parts (named via `body: "<field>"`)
	//     decode as JSON into the matching submessage; other
	//     bindings (HEADER, PATH_VAR, QUERY_PARAM) keep their
	//     existing behaviour.
	//
	// Required when any FILE_PART binding is present;
	// forbidden otherwise (multipart=true with no FILE_PART
	// is a meaningless toggle, parser rejects).
	Multipart bool `protobuf:"varint,12,opt,name=multipart,proto3" json:"multipart,omitempty"`
	// REV-148 — cursor-style pagination opt-in. When set with
	// `enabled = true`, the generated REST handler encodes the
	// original request into a base64-url-safe cursor and
	// returns a `w17.Paging` envelope (which the response
	// message must declare explicitly — codegen errors if
	// missing). Storage layer stays paging-agnostic; the
	// keyset WHERE clause + ORDER BY boundaries are derived
	// by the codegen from the storage method's DQL ORDER BY.
	//
	// Spec: docs/specs/gateway/cursor-paging.md
	Paged *PagedConfig `protobuf:"bytes,13,opt,name=paged,proto3" json:"paged,omitempty"`
	// REV-149 — route an HTTP slot (path token / query param /
	// header) into a gRPC metadata key instead of into a
	// request-msg field. The sibling of `fields[]` (which
	// routes into a msg field): same source enumeration
	// (PATH_VAR / QUERY_PARAM / HEADER; FILE_PART is rejected
	// — bytes don't fit in metadata), different target.
	//
	// Typical use:
	//   - URL-driven locale: `/api/{lang}/...` →
	//     w17-language metadata (overrides Accept-Language).
	//   - Idempotency keys: `Idempotency-Key` header →
	//     idempotency-key metadata where the storage tier reads
	//     it for upsert dedup.
	//   - Tenant override: `?tenant=X` query → w17-tenant
	//     metadata where REV-147 scopes auto-stamp it onto
	//     mutations.
	//
	// The msg-field routing (`fields[]`) and the metadata
	// routing here are orthogonal — same field never appears in
	// both because the value lands in a different place. Empty
	// metadata key is a parse-time error.
	MetadataBindings []*MetadataBinding `protobuf:"bytes,14,rep,name=metadata_bindings,json=metadataBindings,proto3" json:"metadata_bindings,omitempty"`
	// raw_body_field — name (proto snake_case) of a `bytes` field on
	// the request message that receives the VERBATIM HTTP request body,
	// with NO JSON→proto transcode. The exact wire bytes land in the
	// field unchanged, which is what byte-identical signature checks
	// (e.g. GitHub's X-Hub-Signature-256 HMAC) require — a re-marshaled
	// body would not match the upstream's MAC.
	//
	// Mutually exclusive with `body` (field 10): a raw-body endpoint
	// consumes the whole request body into this one field, so it can't
	// also map the body onto a sub-message. Other request fields still
	// bind from path / query / header via `fields[]` (FieldBinding) and
	// from headers via `metadata_bindings[]` as usual. Empty = normal
	// JSON body handling.
	//
	// Parse-time checks: the named field must exist on the request
	// message and be of `bytes` type; `body` must be unset.
	RawBodyField string `protobuf:"bytes,15,opt,name=raw_body_field,json=rawBodyField,proto3" json:"raw_body_field,omitempty"`
	// Explicit operation name — the human-readable operation the
	// generated client facade exposes (session.<group>.<operation_id>)
	// and the OpenAPI operationId derive from. Empty = derived from
	// the method name (lowerCamel, group-noun-stripped in the facade).
	// Set this to resolve a within-group naming collision, or to give
	// an operation a friendlier name than its gRPC method.
	OperationId   string `protobuf:"bytes,16,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestEndpoint) Reset() {
	*x = RestEndpoint{}
	mi := &file_w17_rest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestEndpoint) ProtoMessage() {}

func (x *RestEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestEndpoint.ProtoReflect.Descriptor instead.
func (*RestEndpoint) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{6}
}

func (x *RestEndpoint) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *RestEndpoint) GetMethod() HttpMethod {
	if x != nil {
		return x.Method
	}
	return HttpMethod_HTTP_METHOD_UNSPECIFIED
}

func (x *RestEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestEndpoint) GetExcludeAuth() bool {
	if x != nil {
		return x.ExcludeAuth
	}
	return false
}

func (x *RestEndpoint) GetResponseOmitFields() []string {
	if x != nil {
		return x.ResponseOmitFields
	}
	return nil
}

func (x *RestEndpoint) GetFields() []*FieldBinding {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RestEndpoint) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RestEndpoint) GetQueryExpand() []string {
	if x != nil {
		return x.QueryExpand
	}
	return nil
}

func (x *RestEndpoint) GetMultipart() bool {
	if x != nil {
		return x.Multipart
	}
	return false
}

func (x *RestEndpoint) GetPaged() *PagedConfig {
	if x != nil {
		return x.Paged
	}
	return nil
}

func (x *RestEndpoint) GetMetadataBindings() []*MetadataBinding {
	if x != nil {
		return x.MetadataBindings
	}
	return nil
}

func (x *RestEndpoint) GetRawBodyField() string {
	if x != nil {
		return x.RawBodyField
	}
	return ""
}

func (x *RestEndpoint) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// MetadataBinding (REV-149) — one HTTP-slot → gRPC-metadata
// routing entry. Sibling of `FieldBinding` (REV-020) which
// targets a request-msg field; this one targets a metadata key.
// Field-binding semantic for source resolution (PATH_VAR /
// QUERY_PARAM / HEADER) is shared verbatim; FILE_PART is
// rejected at parse time (multipart bytes don't fit in metadata).
type MetadataBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP-side identifier — path template token, query parameter
	// key, or header name. Empty defaults to the value of
	// `metadata` (use the same name on both sides). Path bindings
	// additionally require the URL template to declare a matching
	// `{token}`. Header names are matched case-insensitively at
	// runtime.
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Where the value is sourced from. PATH_VAR / QUERY_PARAM /
	// HEADER are valid; FIELD_SOURCE_UNSPECIFIED and FILE_PART
	// are parse-time errors.
	From FieldSource `protobuf:"varint,2,opt,name=from,proto3,enum=w17.FieldSource" json:"from,omitempty"`
	// Target gRPC metadata key. Lowercase ASCII per gRPC
	// convention. Required (empty = parse error).
	Metadata      string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataBinding) Reset() {
	*x = MetadataBinding{}
	mi := &file_w17_rest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataBinding) ProtoMessage() {}

func (x *MetadataBinding) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataBinding.ProtoReflect.Descriptor instead.
func (*MetadataBinding) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataBinding) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *MetadataBinding) GetFrom() FieldSource {
	if x != nil {
		return x.From
	}
	return FieldSource_FIELD_SOURCE_UNSPECIFIED
}

func (x *MetadataBinding) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// PagedConfig configures cursor-based pagination on one
// REST endpoint (REV-148). Every field has a sensible
// default; the boolean sugar form `paged: true` in the
// registry decompiles to `PagedConfig{ enabled: true }`
// with defaults applied.
type PagedConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Master switch. When false (or PagedConfig left zero-
	// valued), the endpoint behaves identically to a non-
	// paged REST endpoint.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Query parameter name carrying the opaque cursor token.
	// Default "cursor". Configurable per-endpoint so an API
	// with its own established convention (e.g. "after",
	// "page_token") can match it.
	CursorParam string `protobuf:"bytes,2,opt,name=cursor_param,json=cursorParam,proto3" json:"cursor_param,omitempty"`
	// Query parameter name carrying the requested page size.
	// Default "limit". Configurable per-endpoint for the same
	// reason as cursor_param.
	LimitParam string `protobuf:"bytes,3,opt,name=limit_param,json=limitParam,proto3" json:"limit_param,omitempty"`
	// Page size used when the request omits the limit query
	// parameter (and the first page is being fetched).
	// Default 20.
	DefaultLimit uint32 `protobuf:"varint,4,opt,name=default_limit,json=defaultLimit,proto3" json:"default_limit,omitempty"`
	// Hard cap on page size. Requested limits above this are
	// silently clamped to this value before the storage call.
	// Default 100.
	MaxLimit      uint32 `protobuf:"varint,5,opt,name=max_limit,json=maxLimit,proto3" json:"max_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagedConfig) Reset() {
	*x = PagedConfig{}
	mi := &file_w17_rest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagedConfig) ProtoMessage() {}

func (x *PagedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagedConfig.ProtoReflect.Descriptor instead.
func (*PagedConfig) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{8}
}

func (x *PagedConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagedConfig) GetCursorParam() string {
	if x != nil {
		return x.CursorParam
	}
	return ""
}

func (x *PagedConfig) GetLimitParam() string {
	if x != nil {
		return x.LimitParam
	}
	return ""
}

func (x *PagedConfig) GetDefaultLimit() uint32 {
	if x != nil {
		return x.DefaultLimit
	}
	return 0
}

func (x *PagedConfig) GetMaxLimit() uint32 {
	if x != nil {
		return x.MaxLimit
	}
	return 0
}

// FieldBinding routes one request-msg field to a non-body
// HTTP slot (REV-020). Fields not in any binding keep default
// behavior — body-bound for non-GET/DELETE verbs, ignored for
// GET/DELETE.
type FieldBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted path on the request message naming the field to
	// route. Single segment (`status`) for a top-level field;
	// dotted (`filters.status`, `paging.limit`) for nested
	// message fields. Must resolve to a real field at parse
	// time; the leaf segment must be a scalar (path / query /
	// header all carry string-shaped values; nested messages
	// can't bind directly).
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Where the value is sourced from on the HTTP side.
	From FieldSource `protobuf:"varint,2,opt,name=from,proto3,enum=w17.FieldSource" json:"from,omitempty"`
	// HTTP-side identifier — path template token, query
	// parameter key, or header name. Empty defaults to the
	// leaf segment of `ref`. Path bindings additionally
	// require the URL template to declare a matching `{token}`.
	// Header names are matched case-insensitively at runtime.
	HttpName      string `protobuf:"bytes,3,opt,name=http_name,json=httpName,proto3" json:"http_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldBinding) Reset() {
	*x = FieldBinding{}
	mi := &file_w17_rest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldBinding) ProtoMessage() {}

func (x *FieldBinding) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldBinding.ProtoReflect.Descriptor instead.
func (*FieldBinding) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{9}
}

func (x *FieldBinding) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *FieldBinding) GetFrom() FieldSource {
	if x != nil {
		return x.From
	}
	return FieldSource_FIELD_SOURCE_UNSPECIFIED
}

func (x *FieldBinding) GetHttpName() string {
	if x != nil {
		return x.HttpName
	}
	return ""
}

// RestStream binds one streaming gRPC method to an HTTP
// streaming route. Transport (SSE vs WS) auto-derives from the
// gRPC streaming kind; `transport_override` flips when the
// default doesn't match the consumer.
type RestStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference, same shape as RestEndpoint.ref.
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// URL template, group-relative. Path-template binding
	// semantics match RestEndpoint.path.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Auto-derivation table:
	//
	//	gRPC server-stream  → SSE (text/event-stream, GET-shaped)
	//	gRPC client-stream  → WS  (browsers can't natively
	//	                           upload-stream over HTTP)
	//	gRPC bidi-stream    → WS
	//
	// Override only when the consumer needs the non-default — e.g.
	// a server-stream RPC where the browser also needs to send
	// "abort" frames (force WS) or a client/bidi RPC where the
	// server only ever sends one message (force… well, today
	// there's no SSE-with-uplink option, so this is mostly a
	// forward-compat slot for future transports).
	//
	// Forcing SSE on a non-server-stream method is a parse-time
	// error — SSE has no client-uplink primitive in the spec.
	TransportOverride StreamTransport `protobuf:"varint,3,opt,name=transport_override,json=transportOverride,proto3,enum=w17.StreamTransport" json:"transport_override,omitempty"`
	// Skip the auth middleware for this stream even when
	// `RestApi.auth_methods[]` is populated. Same semantic as
	// RestEndpoint.exclude_auth.
	ExcludeAuth bool `protobuf:"varint,4,opt,name=exclude_auth,json=excludeAuth,proto3" json:"exclude_auth,omitempty"`
	// Required headers — same semantic as
	// RestEndpoint.required_headers.
	RequiredHeaders []string `protobuf:"bytes,6,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty"`
	// Explicit operation name — same semantic as
	// RestEndpoint.operation_id, for streaming operations.
	OperationId   string `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestStream) Reset() {
	*x = RestStream{}
	mi := &file_w17_rest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestStream) ProtoMessage() {}

func (x *RestStream) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestStream.ProtoReflect.Descriptor instead.
func (*RestStream) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{10}
}

func (x *RestStream) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *RestStream) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestStream) GetTransportOverride() StreamTransport {
	if x != nil {
		return x.TransportOverride
	}
	return StreamTransport_STREAM_TRANSPORT_UNSPECIFIED
}

func (x *RestStream) GetExcludeAuth() bool {
	if x != nil {
		return x.ExcludeAuth
	}
	return false
}

func (x *RestStream) GetRequiredHeaders() []string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *RestStream) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// DownloadEndpoint binds a static download route under the
// REST surface to a set of UPLOADED_* fields declared on
// request / response messages elsewhere in the registry.
//
// At runtime the gateway streams the stored blob directly
// from its kvfs.Driver — no proxy hop, no nginx in front.
//
//	final URL = <api.prefix> + <group.prefix> + <download.path>
//	              + <field.bucket_path> + <sub_bucket> + <object_key>
//
// `<field.bucket_path>` is the Slice A `(w17.field).upload.bucket_path`
// declared on the resolved UPLOADED_* field; `<sub_bucket>` and
// `<object_key>` are the same shape the upload handler stored.
type DownloadEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL prefix under which the resolved fields' blobs serve.
	// Composes with the api + group prefixes. Required, must
	// start with `/`, no trailing slash, no `{token}` placeholders.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Field selector — Django-style include/exclude over
	// fully-qualified UPLOADED_* field refs.
	//
	// Glob syntax (single-segment wildcard, no `**`):
	//
	//	"*"                       — every UPLOADED_* field in the surface
	//	"<module>.*"              — every UPLOADED_* field in <module>
	//	"<module>.<Msg>.*"        — every UPLOADED_* field on <Msg>
	//	"<module>.<Msg>.<field>"  — exact field
	//
	// `<module>` is the last segment of the proto package
	// (matches REST endpoint ref shape). Globs resolve at parse
	// time to a concrete set of fields. `exclude` subtracts from
	// `include`. Empty `include` is a parse error (an endpoint
	// serving zero fields is a footgun, not a valid config).
	// Globs that resolve to zero fields are also a parse error
	// (typo guard).
	Include []string `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Exclude []string `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	// Skip the auth middleware for this download even when the
	// surface declares `auth_methods[]`. Same semantic as
	// RestEndpoint.exclude_auth.
	ExcludeAuth bool `protobuf:"varint,4,opt,name=exclude_auth,json=excludeAuth,proto3" json:"exclude_auth,omitempty"`
	// Verbatim Cache-Control header value. Empty = no header
	// emitted (browser falls back to heuristic caching). Common
	// picks: "public, max-age=31536000, immutable" for content-
	// addressed (sha256-keyed) objects since the URL changes
	// when content changes; "no-store" for sensitive blobs.
	CacheControl string `protobuf:"bytes,6,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	// Content-Disposition picker. INLINE (default) renders the
	// body in-browser; ATTACHMENT triggers a save-as dialog with
	// the object_key as filename. Per-endpoint, not per-field —
	// split into multiple endpoints if you need both.
	ContentDisposition ContentDisposition `protobuf:"varint,7,opt,name=content_disposition,json=contentDisposition,proto3,enum=w17.ContentDisposition" json:"content_disposition,omitempty"`
	// ETag emission toggle. Default is enabled (the object_key
	// IS the sha256 hex of content, so the strong ETag is free).
	// Disable only when the storage backend rewrites bytes under
	// a stable key (none of today's drivers do).
	DisableEtag bool `protobuf:"varint,8,opt,name=disable_etag,json=disableEtag,proto3" json:"disable_etag,omitempty"`
	// Range-request toggle. Default is enabled (i.e. honour
	// `Range: bytes=…`). Disable for endpoints whose backend
	// can't serve partial reads efficiently — none today.
	DisableRange bool `protobuf:"varint,9,opt,name=disable_range,json=disableRange,proto3" json:"disable_range,omitempty"`
	// Required: how URLs to objects under this download prefix
	// are rendered when a REST endpoint returns one of the
	// resolved UPLOADED_* fields in its response. The parser
	// refuses URL_FORM_UNSPECIFIED so the choice is always
	// explicit at declaration time.
	//
	//	RELATIVE — `<prefix>/<bucket>/<key>` only; the FE
	//	           composes the absolute URL itself (typical
	//	           when FE + BE share the same host).
	//	ABSOLUTE — `<scheme>://<host><prefix>/<bucket>/<key>`;
	//	           the gateway prepends a host read from
	//	           `<ENV_PREFIX>_PUBLIC_HOST` at boot. Picks
	//	           this when FE runs on a different domain
	//	           (CORS deploys, mobile clients, CDN-fronted).
	UrlForm       URLForm `protobuf:"varint,10,opt,name=url_form,json=urlForm,proto3,enum=w17.URLForm" json:"url_form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadEndpoint) Reset() {
	*x = DownloadEndpoint{}
	mi := &file_w17_rest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadEndpoint) ProtoMessage() {}

func (x *DownloadEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadEndpoint.ProtoReflect.Descriptor instead.
func (*DownloadEndpoint) Descriptor() ([]byte, []int) {
	return file_w17_rest_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadEndpoint) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *DownloadEndpoint) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *DownloadEndpoint) GetExcludeAuth() bool {
	if x != nil {
		return x.ExcludeAuth
	}
	return false
}

func (x *DownloadEndpoint) GetCacheControl() string {
	if x != nil {
		return x.CacheControl
	}
	return ""
}

func (x *DownloadEndpoint) GetContentDisposition() ContentDisposition {
	if x != nil {
		return x.ContentDisposition
	}
	return ContentDisposition_CONTENT_DISPOSITION_UNSPECIFIED
}

func (x *DownloadEndpoint) GetDisableEtag() bool {
	if x != nil {
		return x.DisableEtag
	}
	return false
}

func (x *DownloadEndpoint) GetDisableRange() bool {
	if x != nil {
		return x.DisableRange
	}
	return false
}

func (x *DownloadEndpoint) GetUrlForm() URLForm {
	if x != nil {
		return x.UrlForm
	}
	return URLForm_URL_FORM_UNSPECIFIED
}

var file_w17_rest_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*RestApi)(nil),
		Field:         50110,
		Name:          "w17.rest_api",
		Tag:           "bytes,50110,opt,name=rest_api",
		Filename:      "w17/rest.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// (w17.rest_api) — file-level option declaring this file as
	// a REST surface registry. The author wires which gRPC
	// methods are exposed at which URLs by referencing them via
	// string `ref` paths. The file declares ZERO messages — it's
	// a sentinel, similar to `w17.proto` cascade files (REV-004).
	//
	// optional w17.RestApi rest_api = 50110;
	E_RestApi = &file_w17_rest_proto_extTypes[0]
)

var File_w17_rest_proto protoreflect.FileDescriptor

const file_w17_rest_proto_rawDesc = "" +
	"\n" +
	"\x0ew17/rest.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\"\xf3\x02\n" +
	"\aRestApi\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\fauth_methods\x18\x05 \x03(\v2\x0f.w17.AuthMethodR\vauthMethods\x12&\n" +
	"\x06groups\x18\x06 \x03(\v2\x0e.w17.RestGroupR\x06groups\x12K\n" +
	"\x14metadata_propagation\x18\a \x01(\v2\x18.w17.MetadataPropagationR\x13metadataPropagation\x12)\n" +
	"\x10default_language\x18\b \x01(\tR\x0fdefaultLanguage\x12,\n" +
	"\ainclude\x18\t \x03(\v2\x12.w17.PluginIncludeR\ainclude\"=\n" +
	"\rPluginInclude\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x14\n" +
	"\x05mount\x18\x02 \x01(\tR\x05mount\"O\n" +
	"\n" +
	"AuthMethod\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12/\n" +
	"\vtoken_types\x18\x02 \x03(\x0e2\x0e.w17.TokenTypeR\n" +
	"tokenTypes\"\x92\x01\n" +
	"\x13MetadataPropagation\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\tR\aheaders\x12'\n" +
	"\x0fextend_defaults\x18\x02 \x01(\bR\x0eextendDefaults\x128\n" +
	"\x0eheader_renames\x18\x03 \x03(\v2\x11.w17.HeaderRenameR\rheaderRenames\">\n" +
	"\fHeaderRename\x12\x12\n" +
	"\x04http\x18\x01 \x01(\tR\x04http\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"\xea\x01\n" +
	"\tRestGroup\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12/\n" +
	"\tendpoints\x18\x03 \x03(\v2\x11.w17.RestEndpointR\tendpoints\x12)\n" +
	"\astreams\x18\x04 \x03(\v2\x0f.w17.RestStreamR\astreams\x123\n" +
	"\tdownloads\x18\x05 \x03(\v2\x15.w17.DownloadEndpointR\tdownloads\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\xf9\x03\n" +
	"\fRestEndpoint\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12'\n" +
	"\x06method\x18\x02 \x01(\x0e2\x0f.w17.HttpMethodR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\fexclude_auth\x18\x04 \x01(\bR\vexcludeAuth\x120\n" +
	"\x14response_omit_fields\x18\b \x03(\tR\x12responseOmitFields\x12)\n" +
	"\x06fields\x18\t \x03(\v2\x11.w17.FieldBindingR\x06fields\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\x12!\n" +
	"\fquery_expand\x18\v \x03(\tR\vqueryExpand\x12\x1c\n" +
	"\tmultipart\x18\f \x01(\bR\tmultipart\x12&\n" +
	"\x05paged\x18\r \x01(\v2\x10.w17.PagedConfigR\x05paged\x12A\n" +
	"\x11metadata_bindings\x18\x0e \x03(\v2\x14.w17.MetadataBindingR\x10metadataBindings\x12$\n" +
	"\x0eraw_body_field\x18\x0f \x01(\tR\frawBodyField\x12!\n" +
	"\foperation_id\x18\x10 \x01(\tR\voperationIdJ\x04\b\x05\x10\x06R\vauth_scopes\"e\n" +
	"\x0fMetadataBinding\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12$\n" +
	"\x04from\x18\x02 \x01(\x0e2\x10.w17.FieldSourceR\x04from\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"\xad\x01\n" +
	"\vPagedConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fcursor_param\x18\x02 \x01(\tR\vcursorParam\x12\x1f\n" +
	"\vlimit_param\x18\x03 \x01(\tR\n" +
	"limitParam\x12#\n" +
	"\rdefault_limit\x18\x04 \x01(\rR\fdefaultLimit\x12\x1b\n" +
	"\tmax_limit\x18\x05 \x01(\rR\bmaxLimit\"c\n" +
	"\fFieldBinding\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12$\n" +
	"\x04from\x18\x02 \x01(\x0e2\x10.w17.FieldSourceR\x04from\x12\x1b\n" +
	"\thttp_name\x18\x03 \x01(\tR\bhttpName\"\xfb\x01\n" +
	"\n" +
	"RestStream\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12C\n" +
	"\x12transport_override\x18\x03 \x01(\x0e2\x14.w17.StreamTransportR\x11transportOverride\x12!\n" +
	"\fexclude_auth\x18\x04 \x01(\bR\vexcludeAuth\x12)\n" +
	"\x10required_headers\x18\x06 \x03(\tR\x0frequiredHeaders\x12!\n" +
	"\foperation_id\x18\a \x01(\tR\voperationIdJ\x04\b\x05\x10\x06R\vauth_scopes\"\xf0\x02\n" +
	"\x10DownloadEndpoint\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\ainclude\x18\x02 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12!\n" +
	"\fexclude_auth\x18\x04 \x01(\bR\vexcludeAuth\x12#\n" +
	"\rcache_control\x18\x06 \x01(\tR\fcacheControl\x12H\n" +
	"\x13content_disposition\x18\a \x01(\x0e2\x17.w17.ContentDispositionR\x12contentDisposition\x12!\n" +
	"\fdisable_etag\x18\b \x01(\bR\vdisableEtag\x12#\n" +
	"\rdisable_range\x18\t \x01(\bR\fdisableRange\x12'\n" +
	"\burl_form\x18\n" +
	" \x01(\x0e2\f.w17.URLFormR\aurlFormJ\x04\b\x05\x10\x06R\vauth_scopes*h\n" +
	"\tTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOKEN_TYPE_BEARER\x10\x01\x12\x14\n" +
	"\x10TOKEN_TYPE_BASIC\x10\x02\x12\x12\n" +
	"\x0eTOKEN_TYPE_ANY\x10\x03*e\n" +
	"\vFieldSource\x12\x1c\n" +
	"\x18FIELD_SOURCE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPATH_VAR\x10\x01\x12\x0f\n" +
	"\vQUERY_PARAM\x10\x02\x12\n" +
	"\n" +
	"\x06HEADER\x10\x03\x12\r\n" +
	"\tFILE_PART\x10\x04*Q\n" +
	"\aURLForm\x12\x18\n" +
	"\x14URL_FORM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11URL_FORM_RELATIVE\x10\x01\x12\x15\n" +
	"\x11URL_FORM_ABSOLUTE\x10\x02*}\n" +
	"\x12ContentDisposition\x12#\n" +
	"\x1fCONTENT_DISPOSITION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONTENT_DISPOSITION_INLINE\x10\x01\x12\"\n" +
	"\x1eCONTENT_DISPOSITION_ATTACHMENT\x10\x02*\\\n" +
	"\n" +
	"HttpMethod\x12\x1b\n" +
	"\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04POST\x10\x02\x12\a\n" +
	"\x03PUT\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\x12\t\n" +
	"\x05PATCH\x10\x05*f\n" +
	"\x0fStreamTransport\x12 \n" +
	"\x1cSTREAM_TRANSPORT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STREAM_TRANSPORT_SSE\x10\x01\x12\x17\n" +
	"\x13STREAM_TRANSPORT_WS\x10\x02:G\n" +
	"\brest_api\x12\x1c.google.protobuf.FileOptions\x18\xbe\x87\x03 \x01(\v2\f.w17.RestApiR\arestApiB3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_rest_proto_rawDescOnce sync.Once
	file_w17_rest_proto_rawDescData []byte
)

func file_w17_rest_proto_rawDescGZIP() []byte {
	file_w17_rest_proto_rawDescOnce.Do(func() {
		file_w17_rest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_rest_proto_rawDesc), len(file_w17_rest_proto_rawDesc)))
	})
	return file_w17_rest_proto_rawDescData
}

var file_w17_rest_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_w17_rest_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_w17_rest_proto_goTypes = []any{
	(TokenType)(0),                   // 0: w17.TokenType
	(FieldSource)(0),                 // 1: w17.FieldSource
	(URLForm)(0),                     // 2: w17.URLForm
	(ContentDisposition)(0),          // 3: w17.ContentDisposition
	(HttpMethod)(0),                  // 4: w17.HttpMethod
	(StreamTransport)(0),             // 5: w17.StreamTransport
	(*RestApi)(nil),                  // 6: w17.RestApi
	(*PluginInclude)(nil),            // 7: w17.PluginInclude
	(*AuthMethod)(nil),               // 8: w17.AuthMethod
	(*MetadataPropagation)(nil),      // 9: w17.MetadataPropagation
	(*HeaderRename)(nil),             // 10: w17.HeaderRename
	(*RestGroup)(nil),                // 11: w17.RestGroup
	(*RestEndpoint)(nil),             // 12: w17.RestEndpoint
	(*MetadataBinding)(nil),          // 13: w17.MetadataBinding
	(*PagedConfig)(nil),              // 14: w17.PagedConfig
	(*FieldBinding)(nil),             // 15: w17.FieldBinding
	(*RestStream)(nil),               // 16: w17.RestStream
	(*DownloadEndpoint)(nil),         // 17: w17.DownloadEndpoint
	(*descriptorpb.FileOptions)(nil), // 18: google.protobuf.FileOptions
}
var file_w17_rest_proto_depIdxs = []int32{
	8,  // 0: w17.RestApi.auth_methods:type_name -> w17.AuthMethod
	11, // 1: w17.RestApi.groups:type_name -> w17.RestGroup
	9,  // 2: w17.RestApi.metadata_propagation:type_name -> w17.MetadataPropagation
	7,  // 3: w17.RestApi.include:type_name -> w17.PluginInclude
	0,  // 4: w17.AuthMethod.token_types:type_name -> w17.TokenType
	10, // 5: w17.MetadataPropagation.header_renames:type_name -> w17.HeaderRename
	12, // 6: w17.RestGroup.endpoints:type_name -> w17.RestEndpoint
	16, // 7: w17.RestGroup.streams:type_name -> w17.RestStream
	17, // 8: w17.RestGroup.downloads:type_name -> w17.DownloadEndpoint
	4,  // 9: w17.RestEndpoint.method:type_name -> w17.HttpMethod
	15, // 10: w17.RestEndpoint.fields:type_name -> w17.FieldBinding
	14, // 11: w17.RestEndpoint.paged:type_name -> w17.PagedConfig
	13, // 12: w17.RestEndpoint.metadata_bindings:type_name -> w17.MetadataBinding
	1,  // 13: w17.MetadataBinding.from:type_name -> w17.FieldSource
	1,  // 14: w17.FieldBinding.from:type_name -> w17.FieldSource
	5,  // 15: w17.RestStream.transport_override:type_name -> w17.StreamTransport
	3,  // 16: w17.DownloadEndpoint.content_disposition:type_name -> w17.ContentDisposition
	2,  // 17: w17.DownloadEndpoint.url_form:type_name -> w17.URLForm
	18, // 18: w17.rest_api:extendee -> google.protobuf.FileOptions
	6,  // 19: w17.rest_api:type_name -> w17.RestApi
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	19, // [19:20] is the sub-list for extension type_name
	18, // [18:19] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_w17_rest_proto_init() }
func file_w17_rest_proto_init() {
	if File_w17_rest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_rest_proto_rawDesc), len(file_w17_rest_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_w17_rest_proto_goTypes,
		DependencyIndexes: file_w17_rest_proto_depIdxs,
		EnumInfos:         file_w17_rest_proto_enumTypes,
		MessageInfos:      file_w17_rest_proto_msgTypes,
		ExtensionInfos:    file_w17_rest_proto_extTypes,
	}.Build()
	File_w17_rest_proto = out.File
	file_w17_rest_proto_goTypes = nil
	file_w17_rest_proto_depIdxs = nil
}
