// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17/rpc.proto

package w17pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcApi declares one gRPC gateway surface — the public set of
// re-declared services the gateway exposes over HTTP/2. The
// picked methods themselves are marked inline via `(w17.rpc)`;
// this message carries only the surface-level metadata + knobs.
type RpcApi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name of the surface — "public" / "partner" /
	// "internal". Surfaces in tooling + diagnostics. Must be a
	// snake_case identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of this surface — "v1" / "v2". Free-form string;
	// also the default version segment of the generated public
	// proto package (`<domain>.gateway.<version>`) when non-empty.
	// Empty = "v1".
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Human-readable description of the gRPC surface. Surfaces in
	// tooling. Empty = no description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Enable gRPC server reflection on the emitted gateway server.
	// Default false — a technical public API typically wants
	// reflection on so clients (grpcurl, generated stubs) can
	// discover the surface, but it stays an explicit opt-in so an
	// internal-only surface can keep its shape unadvertised.
	Reflection bool `protobuf:"varint,4,opt,name=reflection,proto3" json:"reflection,omitempty"`
	// Logical groupings of the public surface — mirrors
	// `RestApi.groups` (REV-017). Each group's `name` is a public
	// gRPC service in the emitted `w17.lock.rpc.proto`; its `refs`
	// name the backend methods that service wraps. The picked
	// methods carry the gateway-tier concerns (event emit, auth,
	// ACL cascade) verbatim. Empty `groups` + no inline `(w17.rpc)`
	// marks = empty surface (the gateway emit produces nothing).
	//
	// Inline `(w17.rpc)` / `(w17.rpc_service)` marks still work and
	// desugar into a synthesized group named after the method's
	// (override-or-original) backend service — both paths converge
	// on the same internal model.
	Groups        []*RpcGroup `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcApi) Reset() {
	*x = RpcApi{}
	mi := &file_w17_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcApi) ProtoMessage() {}

func (x *RpcApi) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcApi.ProtoReflect.Descriptor instead.
func (*RpcApi) Descriptor() ([]byte, []int) {
	return file_w17_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RpcApi) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RpcApi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RpcApi) GetReflection() bool {
	if x != nil {
		return x.Reflection
	}
	return false
}

func (x *RpcApi) GetGroups() []*RpcGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// RpcGroup buckets backend methods under one public gRPC service
// — the gRPC sibling of `RestGroup` (REV-017). Where REST groups
// surface as a URL sub-prefix + OpenAPI tag, an rpc group's
// `name` IS the public `service` name emitted into
// `w17.lock.rpc.proto`. Methods drawn from several backend
// services may be regrouped under one public service name.
type RpcGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public gRPC service name this group emits into
	// `w17.lock.rpc.proto`. Must be a PascalCase identifier; carried
	// verbatim (no suffix added/stripped). gRPC requires method
	// names unique per service — two refs resolving to the same
	// method name under one group is a parse-time error.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description — surfaces as the leading comment
	// on the emitted public service. Empty = no comment.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Backend methods this public service wraps, by `ref`. A ref is
	// either a whole service (all its methods) or a single method:
	//
	//	"console.initiatives.InitiativeQuery"               — whole service
	//	"console.initiatives.SnapshotMutation.PushSnapshot" — one method
	//
	// `<module>` is the proto module (last package segment), matching
	// the FK / REST `ref` shape (REV-015 / REV-017). Resolution is
	// domain-scoped; a cross-domain ref is a parse-time error. The
	// request/response message types are reused verbatim from the
	// backend (imported into the lock, never redefined).
	//
	// Refs (not inline `service X { rpc … }` definitions) because a
	// message can be the input/output of several RPCs across
	// services, so a method-by-message definition is not
	// deterministic about which backend service it wraps. A ref is
	// unambiguous.
	Refs          []string `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcGroup) Reset() {
	*x = RpcGroup{}
	mi := &file_w17_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGroup) ProtoMessage() {}

func (x *RpcGroup) ProtoReflect() protoreflect.Message {
	mi := &file_w17_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGroup.ProtoReflect.Descriptor instead.
func (*RpcGroup) Descriptor() ([]byte, []int) {
	return file_w17_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RpcGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RpcGroup) GetRefs() []string {
	if x != nil {
		return x.Refs
	}
	return nil
}

var file_w17_rpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50111,
		Name:          "w17.rpc",
		Tag:           "varint,50111,opt,name=rpc",
		Filename:      "w17/rpc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50112,
		Name:          "w17.rpc_service",
		Tag:           "bytes,50112,opt,name=rpc_service",
		Filename:      "w17/rpc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*RpcApi)(nil),
		Field:         50113,
		Name:          "w17.rpc_api",
		Tag:           "bytes,50113,opt,name=rpc_api",
		Filename:      "w17/rpc.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// (w17.rpc) — expose this RPC over the generated gRPC gateway.
	// The method is re-declared in the emitted `grpcapi.proto`
	// under a public service (its original service name by
	// default, or `(w17.rpc_service)` when set), reusing the
	// backend request/response message types. Streaming
	// qualifiers (server / client / bidi) carry over verbatim and
	// are forwarded natively. Sibling-scalar shape mirrors
	// `(w17.mcp)` (REV-018): a bare bool pick + a separate string
	// override, rather than a message option.
	//
	// optional bool rpc = 50111;
	E_Rpc = &file_w17_rpc_proto_extTypes[0]
	// (w17.rpc_service) — override the PUBLIC service name this
	// method lands under in the emitted `grpcapi.proto`. Empty =
	// inherit the method's original gRPC service name. Use to
	// regroup methods drawn from several backend services under
	// one public service, or to give a backend service a cleaner
	// public name. The method name itself is always carried 1:1
	// (no rename). Must be a PascalCase identifier; the parser
	// appends/strips no suffix.
	//
	// optional string rpc_service = 50112;
	E_RpcService = &file_w17_rpc_proto_extTypes[1]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// (w17.rpc_api) — file-level option declaring this file as an
	// rpc (gRPC gateway) surface registry. A sentinel carrying the
	// surface's identity + knobs; the per-method `(w17.rpc)` flags
	// do the picking. The file declares ZERO messages, like
	// `(w17.rest_api)` (REV-017) and `(w17.mcp_api)` (REV-018).
	//
	// One rpc surface per parse (one generated `grpcapi.proto`);
	// two files carrying `(w17.rpc_api)` is a hard error.
	//
	// optional w17.RpcApi rpc_api = 50113;
	E_RpcApi = &file_w17_rpc_proto_extTypes[2]
)

var File_w17_rpc_proto protoreflect.FileDescriptor

const file_w17_rpc_proto_rawDesc = "" +
	"\n" +
	"\rw17/rpc.proto\x12\x03w17\x1a google/protobuf/descriptor.proto\"\xb3\x01\n" +
	"\x06RpcApi\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"reflection\x18\x04 \x01(\bR\n" +
	"reflection\x12%\n" +
	"\x06groups\x18\x06 \x03(\v2\r.w17.RpcGroupR\x06groupsJ\x04\b\x05\x10\x06R\fauth_methods\"T\n" +
	"\bRpcGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04refs\x18\x03 \x03(\tR\x04refs:2\n" +
	"\x03rpc\x12\x1e.google.protobuf.MethodOptions\x18\xbf\x87\x03 \x01(\bR\x03rpc:A\n" +
	"\vrpc_service\x12\x1e.google.protobuf.MethodOptions\x18\xc0\x87\x03 \x01(\tR\n" +
	"rpcService:D\n" +
	"\arpc_api\x12\x1c.google.protobuf.FileOptions\x18\xc1\x87\x03 \x01(\v2\v.w17.RpcApiR\x06rpcApiB3Z1github.com/wandering-compiler/sdk/go/pb/w17;w17pbb\x06proto3"

var (
	file_w17_rpc_proto_rawDescOnce sync.Once
	file_w17_rpc_proto_rawDescData []byte
)

func file_w17_rpc_proto_rawDescGZIP() []byte {
	file_w17_rpc_proto_rawDescOnce.Do(func() {
		file_w17_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_rpc_proto_rawDesc), len(file_w17_rpc_proto_rawDesc)))
	})
	return file_w17_rpc_proto_rawDescData
}

var file_w17_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_w17_rpc_proto_goTypes = []any{
	(*RpcApi)(nil),                     // 0: w17.RpcApi
	(*RpcGroup)(nil),                   // 1: w17.RpcGroup
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
	(*descriptorpb.FileOptions)(nil),   // 3: google.protobuf.FileOptions
}
var file_w17_rpc_proto_depIdxs = []int32{
	1, // 0: w17.RpcApi.groups:type_name -> w17.RpcGroup
	2, // 1: w17.rpc:extendee -> google.protobuf.MethodOptions
	2, // 2: w17.rpc_service:extendee -> google.protobuf.MethodOptions
	3, // 3: w17.rpc_api:extendee -> google.protobuf.FileOptions
	0, // 4: w17.rpc_api:type_name -> w17.RpcApi
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_w17_rpc_proto_init() }
func file_w17_rpc_proto_init() {
	if File_w17_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_rpc_proto_rawDesc), len(file_w17_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_w17_rpc_proto_goTypes,
		DependencyIndexes: file_w17_rpc_proto_depIdxs,
		MessageInfos:      file_w17_rpc_proto_msgTypes,
		ExtensionInfos:    file_w17_rpc_proto_extTypes,
	}.Build()
	File_w17_rpc_proto = out.File
	file_w17_rpc_proto_goTypes = nil
	file_w17_rpc_proto_depIdxs = nil
}
