package migrate

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"google.golang.org/protobuf/encoding/protojson"

	applyplanpb "github.com/wandering-compiler/sdk/go/pb/applyplan"
)

// The dev schema, written down.
//
// A dev database is RECONCILED to the current schema rather than walked
// forward through a history: the planner diffs what the models say against
// what the store holds and applies the difference. That is why a project in
// development needs no migration series at all, and why its stores carry no
// ledger — there is nothing to be a ledger OF.
//
// Planning is a compiler concern and happens on the console. Applying needs
// the database. Between them sits the same gap fixtures have: a compose stack
// whose Postgres appears seconds before the services do, with no console in
// reach. So the plan is rendered at generate time and executed at start-up,
// exactly as a rendered fixture is.
//
// What this REPLACES is `db/init/<domain>/01_schema.sql` and the initdb mount
// that ran it. Not because the SQL was wrong — it is the same planner's output
// — but because of when it ran: the postgres entrypoint runs an initdb
// directory ONLY on a fresh volume, so a schema change never reached a
// database that already existed. On the console that surfaced twice as
// `invalid credentials` and a dead invite endpoint, from a column and a table
// the running database had never been given.

// devPlanFile is the artefact's name under the schema directory.
const devPlanFile = "dev-plan.json"

// WriteDevPlan writes the rendered plan to `<root>/dev-plan.json`.
func WriteDevPlan(root string, plan *applyplanpb.DevApplyPlan) error {
	if plan == nil {
		return fmt.Errorf("WriteDevPlan: nil plan")
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", root, err)
	}
	raw, err := protojson.MarshalOptions{UseProtoNames: true}.Marshal(plan)
	if err != nil {
		return fmt.Errorf("marshal dev plan: %w", err)
	}
	// Same deterministic re-encoding the rendered fixtures get, for the same
	// reason: this is a generated file that lands in a diff, and protojson
	// varies its whitespace between processes on purpose.
	buf, err := stableJSON(raw)
	if err != nil {
		return fmt.Errorf("marshal dev plan: %w", err)
	}
	return os.WriteFile(filepath.Join(root, devPlanFile), append(buf, '\n'), 0o644)
}

// WriteDevPlanDDL writes each connection's schema body beside the plan as
// `<root>/<connection>.ddl`, for READING.
//
// Two renderings of one plan, written by one function from one value, so they
// cannot disagree. The JSON is what the binary executes; this is what a person
// reviews in a diff and what the corpus gates assert emitted DDL against — the
// role `db/init/<domain>/01_schema.sql` used to play, minus the part where the
// postgres entrypoint also RAN it.
//
// It carries a header saying so, and the extension is `.ddl` rather than
// `.sql` for the same reason: a file full of CREATE TABLE named `.sql` is one
// somebody eventually pipes into psql, and that is the second path into a
// database this whole change exists to remove. `.ddl` also stays honest for a
// KV connection, whose plan is a list of keyspace declarations and was never
// SQL at all — the old db/init emitted nothing for those, so there was no name
// to get wrong.
func WriteDevPlanDDL(root string, plan *applyplanpb.DevApplyPlan) error {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", root, err)
	}
	for _, m := range plan.GetMigrations() {
		conn := m.GetConnection()
		if conn == "" {
			conn = "default"
		}
		if err := checkSeedSegments(conn, conn); err != nil {
			return fmt.Errorf("WriteDevPlanSQL: %w", err)
		}
		body := "-- Generated by w17. DO NOT EDIT, and DO NOT RUN.\n" +
			"--\n" +
			"-- This is the DEV schema plan for connection " + conn + ", rendered for\n" +
			"-- READING: it is what a reviewer reads in a diff and what the corpus gates\n" +
			"-- assert the compiler's emitted DDL against.\n" +
			"--\n" +
			"-- The executable copy is dev-plan.json beside it, applied by\n" +
			"-- `<binary> schema apply`. Running THIS file by hand puts a schema into a\n" +
			"-- database by a second path, which is the thing that made a bootstrap\n" +
			"-- nobody recorded possible in the first place.\n\n" +
			m.GetUpSql() + "\n"
		if post := m.GetUpSqlPostTx(); post != "" {
			body += "\n-- Non-transactional skirt (the apply folds this in).\n" + post + "\n"
		}
		if err := os.WriteFile(filepath.Join(root, conn+".ddl"), []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// LoadDevPlan reads the rendered plan from fsys.
//
// A missing artefact is an ERROR rather than an empty plan. "No schema to
// apply" and "the render step never ran" are the same silence otherwise, and
// the second one leaves a database with no tables and a stack that fails
// somewhere further along with a message about neither.
func LoadDevPlan(fsys fs.FS) (*applyplanpb.DevApplyPlan, error) {
	body, err := fs.ReadFile(fsys, devPlanFile)
	if err != nil {
		return nil, err
	}
	var plan applyplanpb.DevApplyPlan
	if err := protojson.Unmarshal(body, &plan); err != nil {
		return nil, fmt.Errorf("parse %s: %w", devPlanFile, err)
	}
	return &plan, nil
}
