// PUBLIC APPLY CONTRACT — the flattened dev-apply plan the thin client
// executes against its LOCAL stores. Homed under a dedicated `w17apply/`
// namespace (separate from the compiler-internal migrator plan) so the public
// client imports ONLY this irpb-free shape, never the IR-laden
// `w17.migrator.plan.Plan`.
//
// Public-split boundary (docs/specs/w17ctl/public-split-architecture.md §8.1):
// the dev DB lifecycle plans server-side (the engine.Plan diff engine is a
// COMPILER concern) and applies client-side. The server flattens its typed
// `planpb.Plan` — whose `Migration.connection` is a `w17.common.ir.Connection`
// and whose `Migration.plan` carries the full IR-typed op list — down to this
// minimal {connection-name, up_sql, up_sql_post_tx} form. So the apply client
// (moved into w17ctl's own module) needs NO compiler IR pb: it decodes
// THIS, runs the SQL, done. Carried as the opaque `bytes` of
// `CodegenService.Plan`'s `PlanIRResponse.plan` (the response field stays
// bytes; only the payload type changed planpb.Plan → DevApplyPlan).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: w17apply/dev_plan.proto

package applyplanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DevApplyPlan is the ordered per-connection migration body set the dev
// diff-apply executes locally. Empty-diff connections are omitted by the
// server-side flatten (same as the engine omits no-op buckets).
type DevApplyPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*DevMigration        `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevApplyPlan) Reset() {
	*x = DevApplyPlan{}
	mi := &file_w17apply_dev_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevApplyPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevApplyPlan) ProtoMessage() {}

func (x *DevApplyPlan) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_dev_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevApplyPlan.ProtoReflect.Descriptor instead.
func (*DevApplyPlan) Descriptor() ([]byte, []int) {
	return file_w17apply_dev_plan_proto_rawDescGZIP(), []int{0}
}

func (x *DevApplyPlan) GetMigrations() []*DevMigration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

// DevMigration is one connection's apply payload, flattened from
// `w17.migrator.plan.Migration` to drop every IR-typed field.
type DevMigration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection is the target connection NAME (planpb.Migration.connection.name).
	// Empty = the default bucket the client's Applier factory resolves to the
	// project's main connection.
	Connection string `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	// UpSql is the transactional apply body (planpb.Migration.up_sql).
	UpSql string `protobuf:"bytes,2,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	// UpSqlPostTx is the non-transactional skirt (planpb.Migration.up_sql_post_tx).
	// The client folds it into up_sql with CONCURRENTLY stripped so it runs
	// inside the dev transaction; empty for the common case.
	UpSqlPostTx   string `protobuf:"bytes,3,opt,name=up_sql_post_tx,json=upSqlPostTx,proto3" json:"up_sql_post_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevMigration) Reset() {
	*x = DevMigration{}
	mi := &file_w17apply_dev_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevMigration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevMigration) ProtoMessage() {}

func (x *DevMigration) ProtoReflect() protoreflect.Message {
	mi := &file_w17apply_dev_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevMigration.ProtoReflect.Descriptor instead.
func (*DevMigration) Descriptor() ([]byte, []int) {
	return file_w17apply_dev_plan_proto_rawDescGZIP(), []int{1}
}

func (x *DevMigration) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *DevMigration) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *DevMigration) GetUpSqlPostTx() string {
	if x != nil {
		return x.UpSqlPostTx
	}
	return ""
}

var File_w17apply_dev_plan_proto protoreflect.FileDescriptor

const file_w17apply_dev_plan_proto_rawDesc = "" +
	"\n" +
	"\x17w17apply/dev_plan.proto\x12\tw17.apply\"G\n" +
	"\fDevApplyPlan\x127\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x17.w17.apply.DevMigrationR\n" +
	"migrations\"j\n" +
	"\fDevMigration\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\x12\x15\n" +
	"\x06up_sql\x18\x02 \x01(\tR\x05upSql\x12#\n" +
	"\x0eup_sql_post_tx\x18\x03 \x01(\tR\vupSqlPostTxB?Z=github.com/wandering-compiler/sdk/go/pb/applyplan;applyplanpbb\x06proto3"

var (
	file_w17apply_dev_plan_proto_rawDescOnce sync.Once
	file_w17apply_dev_plan_proto_rawDescData []byte
)

func file_w17apply_dev_plan_proto_rawDescGZIP() []byte {
	file_w17apply_dev_plan_proto_rawDescOnce.Do(func() {
		file_w17apply_dev_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17apply_dev_plan_proto_rawDesc), len(file_w17apply_dev_plan_proto_rawDesc)))
	})
	return file_w17apply_dev_plan_proto_rawDescData
}

var file_w17apply_dev_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_w17apply_dev_plan_proto_goTypes = []any{
	(*DevApplyPlan)(nil), // 0: w17.apply.DevApplyPlan
	(*DevMigration)(nil), // 1: w17.apply.DevMigration
}
var file_w17apply_dev_plan_proto_depIdxs = []int32{
	1, // 0: w17.apply.DevApplyPlan.migrations:type_name -> w17.apply.DevMigration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_w17apply_dev_plan_proto_init() }
func file_w17apply_dev_plan_proto_init() {
	if File_w17apply_dev_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17apply_dev_plan_proto_rawDesc), len(file_w17apply_dev_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_w17apply_dev_plan_proto_goTypes,
		DependencyIndexes: file_w17apply_dev_plan_proto_depIdxs,
		MessageInfos:      file_w17apply_dev_plan_proto_msgTypes,
	}.Build()
	File_w17apply_dev_plan_proto = out.File
	file_w17apply_dev_plan_proto_goTypes = nil
	file_w17apply_dev_plan_proto_depIdxs = nil
}
