// PUBLIC REGISTRY CONTRACT — the flattened, irpb-free authoring face of the
// console's MigrationRegistry that the thin client (w17ctl's own module) uses
// to PUSH a project's schema / fixtures and READ its migration history. Homed
// under the dedicated `w17registry/` namespace (the authoring side; the deploy
// side is `w17apply/`) so the public client imports ONLY this irpb-free shape,
// never the compiler's IR-laden private pb (the MigrationRegistry, IR,
// fixtures, and migration-plan packages).
//
// Public-split boundary (docs/specs/w17ctl/public-split-architecture.md §8,
// Block 3): the client never handles the STRUCTURE of the IR, the migration
// plan, the review findings, or a fixture body. It ships OPAQUE bytes (the
// compiled-IR blob from CompileIR; a fixture's raw JSON) and gets back flat
// string fields. The server (which owns the registry state + the migrator
// planner + the schema-aware fixture validator) does all the structured work:
//   - PushSchema decodes the IR, runs the planner (create / update resolved
//     server-side from whether a schema is already stored), stores migrations,
//     and flattens the result + any review findings to plain strings.
//   - PushFixture validates the raw JSON against the project's STORED schema
//     server-side (table/column/pk-arity resolution) — the client holds no
//     schema, no fixtures package, no IR.
// So the client carries none of registrypb / irpb / fixturespb / planpb.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: w17registry/registry.proto

package w17registrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectRegistry_RegisterProject_FullMethodName  = "/w17.registry.ProjectRegistry/RegisterProject"
	ProjectRegistry_ListMigrations_FullMethodName   = "/w17.registry.ProjectRegistry/ListMigrations"
	ProjectRegistry_PushSchema_FullMethodName       = "/w17.registry.ProjectRegistry/PushSchema"
	ProjectRegistry_PushRawMigration_FullMethodName = "/w17.registry.ProjectRegistry/PushRawMigration"
	ProjectRegistry_PushFixture_FullMethodName      = "/w17.registry.ProjectRegistry/PushFixture"
)

// ProjectRegistryClient is the client API for ProjectRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProjectRegistry is the console-served, irpb-free authoring face of the
// MigrationRegistry the thin client needs. (The full MigrationRegistry —
// IR-typed CreateSchema / UpdateSchema / GetSchema / RecordApplied / the
// fixture read RPCs — stays private; reads ride the public MigrationFetch /
// FixtureFetch contracts in w17apply/.)
type ProjectRegistryClient interface {
	// RegisterProject creates (or returns the existing) registry project for a
	// human name. Idempotent on name — `w17ctl init` calls it.
	RegisterProject(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*RegisterProjectResponse, error)
	// ListMigrations returns the project's stored migration history (flattened
	// to irpb-free strings) in apply order, optionally filtered by connection /
	// cursor. Unary — the client materialises the whole list anyway (browse +
	// lock-pin). `w17ctl migrate list` + the push lock-pin fallback call it.
	ListMigrations(ctx context.Context, in *ListMigrationsRequest, opts ...grpc.CallOption) (*ListMigrationsResponse, error)
	// PushSchema decodes the uploaded compiled IR, runs the migrator's planner,
	// and stores the resulting migrations. The create-vs-update decision is
	// resolved SERVER-side from `mode` (AUTO probes whether a schema is already
	// stored); on unresolved planner findings nothing is stored and the flat
	// findings come back so the client can print them. `w17ctl push` +
	// `w17ctl migrate generate` call it.
	PushSchema(ctx context.Context, in *PushSchemaRequest, opts ...grpc.CallOption) (*PushSchemaResponse, error)
	// PushRawMigration stores a hand-authored YAML data-migration body,
	// bypassing the schema-driven planner (the TRANSFORM_FIELD escape hatch).
	// Console validates + signs + stores. `w17ctl migrate migration` calls it.
	PushRawMigration(ctx context.Context, in *PushRawMigrationRequest, opts ...grpc.CallOption) (*PushRawMigrationResponse, error)
	// PushFixture stores (or replaces) a fixture body for (project, domain,
	// name). The raw JSON is validated SERVER-side against the project's stored
	// schema (table / column / pk-arity) before storing — the client ships the
	// bytes verbatim, holds no schema / fixtures logic. `w17ctl push` calls it.
	PushFixture(ctx context.Context, in *PushFixtureRequest, opts ...grpc.CallOption) (*PushFixtureResponse, error)
}

type projectRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectRegistryClient(cc grpc.ClientConnInterface) ProjectRegistryClient {
	return &projectRegistryClient{cc}
}

func (c *projectRegistryClient) RegisterProject(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*RegisterProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterProjectResponse)
	err := c.cc.Invoke(ctx, ProjectRegistry_RegisterProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectRegistryClient) ListMigrations(ctx context.Context, in *ListMigrationsRequest, opts ...grpc.CallOption) (*ListMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMigrationsResponse)
	err := c.cc.Invoke(ctx, ProjectRegistry_ListMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectRegistryClient) PushSchema(ctx context.Context, in *PushSchemaRequest, opts ...grpc.CallOption) (*PushSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushSchemaResponse)
	err := c.cc.Invoke(ctx, ProjectRegistry_PushSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectRegistryClient) PushRawMigration(ctx context.Context, in *PushRawMigrationRequest, opts ...grpc.CallOption) (*PushRawMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushRawMigrationResponse)
	err := c.cc.Invoke(ctx, ProjectRegistry_PushRawMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectRegistryClient) PushFixture(ctx context.Context, in *PushFixtureRequest, opts ...grpc.CallOption) (*PushFixtureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushFixtureResponse)
	err := c.cc.Invoke(ctx, ProjectRegistry_PushFixture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectRegistryServer is the server API for ProjectRegistry service.
// All implementations must embed UnimplementedProjectRegistryServer
// for forward compatibility.
//
// ProjectRegistry is the console-served, irpb-free authoring face of the
// MigrationRegistry the thin client needs. (The full MigrationRegistry —
// IR-typed CreateSchema / UpdateSchema / GetSchema / RecordApplied / the
// fixture read RPCs — stays private; reads ride the public MigrationFetch /
// FixtureFetch contracts in w17apply/.)
type ProjectRegistryServer interface {
	// RegisterProject creates (or returns the existing) registry project for a
	// human name. Idempotent on name — `w17ctl init` calls it.
	RegisterProject(context.Context, *RegisterProjectRequest) (*RegisterProjectResponse, error)
	// ListMigrations returns the project's stored migration history (flattened
	// to irpb-free strings) in apply order, optionally filtered by connection /
	// cursor. Unary — the client materialises the whole list anyway (browse +
	// lock-pin). `w17ctl migrate list` + the push lock-pin fallback call it.
	ListMigrations(context.Context, *ListMigrationsRequest) (*ListMigrationsResponse, error)
	// PushSchema decodes the uploaded compiled IR, runs the migrator's planner,
	// and stores the resulting migrations. The create-vs-update decision is
	// resolved SERVER-side from `mode` (AUTO probes whether a schema is already
	// stored); on unresolved planner findings nothing is stored and the flat
	// findings come back so the client can print them. `w17ctl push` +
	// `w17ctl migrate generate` call it.
	PushSchema(context.Context, *PushSchemaRequest) (*PushSchemaResponse, error)
	// PushRawMigration stores a hand-authored YAML data-migration body,
	// bypassing the schema-driven planner (the TRANSFORM_FIELD escape hatch).
	// Console validates + signs + stores. `w17ctl migrate migration` calls it.
	PushRawMigration(context.Context, *PushRawMigrationRequest) (*PushRawMigrationResponse, error)
	// PushFixture stores (or replaces) a fixture body for (project, domain,
	// name). The raw JSON is validated SERVER-side against the project's stored
	// schema (table / column / pk-arity) before storing — the client ships the
	// bytes verbatim, holds no schema / fixtures logic. `w17ctl push` calls it.
	PushFixture(context.Context, *PushFixtureRequest) (*PushFixtureResponse, error)
	mustEmbedUnimplementedProjectRegistryServer()
}

// UnimplementedProjectRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectRegistryServer struct{}

func (UnimplementedProjectRegistryServer) RegisterProject(context.Context, *RegisterProjectRequest) (*RegisterProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProject not implemented")
}
func (UnimplementedProjectRegistryServer) ListMigrations(context.Context, *ListMigrationsRequest) (*ListMigrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMigrations not implemented")
}
func (UnimplementedProjectRegistryServer) PushSchema(context.Context, *PushSchemaRequest) (*PushSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushSchema not implemented")
}
func (UnimplementedProjectRegistryServer) PushRawMigration(context.Context, *PushRawMigrationRequest) (*PushRawMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushRawMigration not implemented")
}
func (UnimplementedProjectRegistryServer) PushFixture(context.Context, *PushFixtureRequest) (*PushFixtureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushFixture not implemented")
}
func (UnimplementedProjectRegistryServer) mustEmbedUnimplementedProjectRegistryServer() {}
func (UnimplementedProjectRegistryServer) testEmbeddedByValue()                         {}

// UnsafeProjectRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectRegistryServer will
// result in compilation errors.
type UnsafeProjectRegistryServer interface {
	mustEmbedUnimplementedProjectRegistryServer()
}

func RegisterProjectRegistryServer(s grpc.ServiceRegistrar, srv ProjectRegistryServer) {
	// If the following call pancis, it indicates UnimplementedProjectRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectRegistry_ServiceDesc, srv)
}

func _ProjectRegistry_RegisterProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectRegistryServer).RegisterProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectRegistry_RegisterProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectRegistryServer).RegisterProject(ctx, req.(*RegisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectRegistry_ListMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectRegistryServer).ListMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectRegistry_ListMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectRegistryServer).ListMigrations(ctx, req.(*ListMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectRegistry_PushSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectRegistryServer).PushSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectRegistry_PushSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectRegistryServer).PushSchema(ctx, req.(*PushSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectRegistry_PushRawMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRawMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectRegistryServer).PushRawMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectRegistry_PushRawMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectRegistryServer).PushRawMigration(ctx, req.(*PushRawMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectRegistry_PushFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushFixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectRegistryServer).PushFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectRegistry_PushFixture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectRegistryServer).PushFixture(ctx, req.(*PushFixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectRegistry_ServiceDesc is the grpc.ServiceDesc for ProjectRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "w17.registry.ProjectRegistry",
	HandlerType: (*ProjectRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProject",
			Handler:    _ProjectRegistry_RegisterProject_Handler,
		},
		{
			MethodName: "ListMigrations",
			Handler:    _ProjectRegistry_ListMigrations_Handler,
		},
		{
			MethodName: "PushSchema",
			Handler:    _ProjectRegistry_PushSchema_Handler,
		},
		{
			MethodName: "PushRawMigration",
			Handler:    _ProjectRegistry_PushRawMigration_Handler,
		},
		{
			MethodName: "PushFixture",
			Handler:    _ProjectRegistry_PushFixture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "w17registry/registry.proto",
}
