// PUBLIC REGISTRY CONTRACT — the flattened, irpb-free authoring face of the
// console's MigrationRegistry that the thin client (w17ctl's own module) uses
// to PUSH a project's schema / fixtures and READ its migration history. Homed
// under the dedicated `w17registry/` namespace (the authoring side; the deploy
// side is `w17apply/`) so the public client imports ONLY this irpb-free shape,
// never the compiler's IR-laden private pb (the MigrationRegistry, IR,
// fixtures, and migration-plan packages).
//
// Public-split boundary (docs/specs/w17ctl/public-split-architecture.md §8,
// Block 3): the client never handles the STRUCTURE of the IR, the migration
// plan, the review findings, or a fixture body. It ships OPAQUE bytes (the
// compiled-IR blob from CompileIR; a fixture's raw JSON) and gets back flat
// string fields. The server (which owns the registry state + the migrator
// planner + the schema-aware fixture validator) does all the structured work:
//   - PushSchema decodes the IR, runs the planner (create / update resolved
//     server-side from whether a schema is already stored), stores migrations,
//     and flattens the result + any review findings to plain strings.
//   - PushFixture validates the raw JSON against the project's STORED schema
//     server-side (table/column/pk-arity resolution) — the client holds no
//     schema, no fixtures package, no IR.
// So the client carries none of registrypb / irpb / fixturespb / planpb.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: w17registry/registry.proto

package w17registrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushMode selects the create/update behaviour. AUTO is the default `push` /
// `migrate generate` shape — the server probes whether a schema is already
// stored and resolves to create (first push) or update (revision).
type PushMode int32

const (
	PushMode_PUSH_MODE_AUTO   PushMode = 0
	PushMode_PUSH_MODE_CREATE PushMode = 1
	PushMode_PUSH_MODE_UPDATE PushMode = 2
)

// Enum value maps for PushMode.
var (
	PushMode_name = map[int32]string{
		0: "PUSH_MODE_AUTO",
		1: "PUSH_MODE_CREATE",
		2: "PUSH_MODE_UPDATE",
	}
	PushMode_value = map[string]int32{
		"PUSH_MODE_AUTO":   0,
		"PUSH_MODE_CREATE": 1,
		"PUSH_MODE_UPDATE": 2,
	}
)

func (x PushMode) Enum() *PushMode {
	p := new(PushMode)
	*p = x
	return p
}

func (x PushMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushMode) Descriptor() protoreflect.EnumDescriptor {
	return file_w17registry_registry_proto_enumTypes[0].Descriptor()
}

func (PushMode) Type() protoreflect.EnumType {
	return &file_w17registry_registry_proto_enumTypes[0]
}

func (x PushMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushMode.Descriptor instead.
func (PushMode) EnumDescriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{0}
}

// ResetHistoryPolicy selects what becomes of the migrations the reset leaves
// behind. The two lifecycle processes that need this RPC differ ONLY here —
// recreate forgets them, squash keeps them mapped.
type ResetHistoryPolicy int32

const (
	ResetHistoryPolicy_RESET_HISTORY_POLICY_UNSPECIFIED ResetHistoryPolicy = 0
	// DISCARD — recreate. The migrations are deleted and the project is left
	// with no schema, so the next push takes the bootstrap (create) path and
	// derives one initial migration.
	//
	// Dev / POC only: it forgets history that a deployed database still
	// believes in, which is why the caller must also reset that database.
	ResetHistoryPolicy_RESET_HISTORY_POLICY_DISCARD ResetHistoryPolicy = 1
	// SUPERSEDE — squash. The migrations stay queryable and MAPPED, so a
	// deployment that applied the old set is recognised as already at the new
	// baseline. The collapsed rows stay listable via a `superseded_by`
	// back-pointer while leaving the apply plan, and the baseline the next
	// push derives names them so a live deployment can record it without
	// running its DDL.
	ResetHistoryPolicy_RESET_HISTORY_POLICY_SUPERSEDE ResetHistoryPolicy = 2
)

// Enum value maps for ResetHistoryPolicy.
var (
	ResetHistoryPolicy_name = map[int32]string{
		0: "RESET_HISTORY_POLICY_UNSPECIFIED",
		1: "RESET_HISTORY_POLICY_DISCARD",
		2: "RESET_HISTORY_POLICY_SUPERSEDE",
	}
	ResetHistoryPolicy_value = map[string]int32{
		"RESET_HISTORY_POLICY_UNSPECIFIED": 0,
		"RESET_HISTORY_POLICY_DISCARD":     1,
		"RESET_HISTORY_POLICY_SUPERSEDE":   2,
	}
)

func (x ResetHistoryPolicy) Enum() *ResetHistoryPolicy {
	p := new(ResetHistoryPolicy)
	*p = x
	return p
}

func (x ResetHistoryPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResetHistoryPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_w17registry_registry_proto_enumTypes[1].Descriptor()
}

func (ResetHistoryPolicy) Type() protoreflect.EnumType {
	return &file_w17registry_registry_proto_enumTypes[1]
}

func (x ResetHistoryPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResetHistoryPolicy.Descriptor instead.
func (ResetHistoryPolicy) EnumDescriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{1}
}

// HistoryVerdict mirrors the registry's own three-valued answer.
//
// UNKNOWN is deliberately not an error value. A project that has migrations
// but no revision records — every project pushed before revisions existed —
// answers this way, and it says "no evidence", not "bad evidence". A caller
// that treats it as drift would refuse work on every legacy project; a caller
// that treats it as consistent would re-sign a history nothing can vouch for.
// Both are wrong, which is why the third value exists rather than a bool.
type HistoryVerdict int32

const (
	HistoryVerdict_HISTORY_VERDICT_UNKNOWN    HistoryVerdict = 0
	HistoryVerdict_HISTORY_VERDICT_CONSISTENT HistoryVerdict = 1
	HistoryVerdict_HISTORY_VERDICT_DRIFTED    HistoryVerdict = 2
)

// Enum value maps for HistoryVerdict.
var (
	HistoryVerdict_name = map[int32]string{
		0: "HISTORY_VERDICT_UNKNOWN",
		1: "HISTORY_VERDICT_CONSISTENT",
		2: "HISTORY_VERDICT_DRIFTED",
	}
	HistoryVerdict_value = map[string]int32{
		"HISTORY_VERDICT_UNKNOWN":    0,
		"HISTORY_VERDICT_CONSISTENT": 1,
		"HISTORY_VERDICT_DRIFTED":    2,
	}
)

func (x HistoryVerdict) Enum() *HistoryVerdict {
	p := new(HistoryVerdict)
	*p = x
	return p
}

func (x HistoryVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_w17registry_registry_proto_enumTypes[2].Descriptor()
}

func (HistoryVerdict) Type() protoreflect.EnumType {
	return &file_w17registry_registry_proto_enumTypes[2]
}

func (x HistoryVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryVerdict.Descriptor instead.
func (HistoryVerdict) EnumDescriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{2}
}

// Migration is one stored migration flattened from the registry's IR-laden
// `registrypb.Migration` to the irpb-free string fields the client reads
// (listing + lock-pin). Bodies are NOT carried here — the apply path fetches
// executable SQL over the separate MigrationFetch contract.
type Migration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connection    string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	ContentSha256 string                 `protobuf:"bytes,3,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_w17registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Migration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *Migration) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

type RegisterProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the human project name; the server returns its stable project_id.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProjectRequest) Reset() {
	*x = RegisterProjectRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProjectRequest) ProtoMessage() {}

func (x *RegisterProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProjectRequest.ProtoReflect.Descriptor instead.
func (*RegisterProjectRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProjectResponse) Reset() {
	*x = RegisterProjectResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProjectResponse) ProtoMessage() {}

func (x *RegisterProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProjectResponse.ProtoReflect.Descriptor instead.
func (*RegisterProjectResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterProjectResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListMigrationsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// connection scopes the list; empty = every connection interleaved by
	// stored order.
	Connection string `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// from_migration_id is a strict-after pagination cursor; empty = from start.
	FromMigrationId string `protobuf:"bytes,3,opt,name=from_migration_id,json=fromMigrationId,proto3" json:"from_migration_id,omitempty"`
	// up_to_migration_id is the upper bound; empty = no upper bound.
	UpToMigrationId string `protobuf:"bytes,4,opt,name=up_to_migration_id,json=upToMigrationId,proto3" json:"up_to_migration_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMigrationsRequest) Reset() {
	*x = ListMigrationsRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsRequest) ProtoMessage() {}

func (x *ListMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsRequest.ProtoReflect.Descriptor instead.
func (*ListMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ListMigrationsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListMigrationsRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *ListMigrationsRequest) GetFromMigrationId() string {
	if x != nil {
		return x.FromMigrationId
	}
	return ""
}

func (x *ListMigrationsRequest) GetUpToMigrationId() string {
	if x != nil {
		return x.UpToMigrationId
	}
	return ""
}

type ListMigrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*Migration           `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsResponse) Reset() {
	*x = ListMigrationsResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsResponse) ProtoMessage() {}

func (x *ListMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsResponse.ProtoReflect.Descriptor instead.
func (*ListMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ListMigrationsResponse) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

type PushSchemaRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// ir is the opaque compiled-IR blob (the bytes CompileIR returned). The
	// server decodes it with its own irpb.Schema — the client never does.
	Ir   []byte   `protobuf:"bytes,2,opt,name=ir,proto3" json:"ir,omitempty"`
	Mode PushMode `protobuf:"varint,3,opt,name=mode,proto3,enum=w17.registry.PushMode" json:"mode,omitempty"`
	// force_initial (AUTO only) forces create — a fresh project can't be
	// silently treated as a revision. Ignored for explicit CREATE / UPDATE.
	ForceInitial bool `protobuf:"varint,4,opt,name=force_initial,json=forceInitial,proto3" json:"force_initial,omitempty"`
	// decide carries raw `--decide` flag strings — OPAQUE to the dumb client
	// (it never parses them; closure 0 stays). The server parses the decide
	// grammar (`<table>.<col>[:<axis>]=<strategy>` / `=custom:<path>`) against
	// the plan's NEEDS_CONFIRM findings and re-plans with the resolutions, so a
	// decidable finding no longer blocks the push.
	Decide []string `protobuf:"bytes,5,rep,name=decide,proto3" json:"decide,omitempty"`
	// decide_custom_sql maps a `custom:<path>` referenced in `decide` to its SQL
	// body. The client reads the local file (the console can't see the client
	// filesystem) and ships the body here; the server's decide loader resolves
	// `custom:<path>` from this map instead of the filesystem.
	DecideCustomSql map[string]string `protobuf:"bytes,6,rep,name=decide_custom_sql,json=decideCustomSql,proto3" json:"decide_custom_sql,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// initiative_id names the change request this push belongs to — the console
	// initiative id (a UUID), which the client resolves the same way
	// `w17ctl initiative current` does: from the current git branch.
	//
	// This is the bridge freeze-a-CR needs (see
	// docs/decisions/squash-supersede-and-adopt.md). The registry already records one revision per push; stamping the
	// initiative onto that row is what makes "which migrations belong to change
	// request X" answerable, and a range with EDGES is the only kind a squash
	// may act on — a date window or a push count would quietly collapse another
	// CR's work.
	//
	// Empty is legal and means "belongs to no initiative": every push made
	// before this field existed reads that way, as does one made outside a git
	// repo or against a console whose initiative is not materialized. Those
	// migrations are simply not in any CR's range, which is the truth.
	InitiativeId  string `protobuf:"bytes,7,opt,name=initiative_id,json=initiativeId,proto3" json:"initiative_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSchemaRequest) Reset() {
	*x = PushSchemaRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSchemaRequest) ProtoMessage() {}

func (x *PushSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSchemaRequest.ProtoReflect.Descriptor instead.
func (*PushSchemaRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{5}
}

func (x *PushSchemaRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PushSchemaRequest) GetIr() []byte {
	if x != nil {
		return x.Ir
	}
	return nil
}

func (x *PushSchemaRequest) GetMode() PushMode {
	if x != nil {
		return x.Mode
	}
	return PushMode_PUSH_MODE_AUTO
}

func (x *PushSchemaRequest) GetForceInitial() bool {
	if x != nil {
		return x.ForceInitial
	}
	return false
}

func (x *PushSchemaRequest) GetDecide() []string {
	if x != nil {
		return x.Decide
	}
	return nil
}

func (x *PushSchemaRequest) GetDecideCustomSql() map[string]string {
	if x != nil {
		return x.DecideCustomSql
	}
	return nil
}

func (x *PushSchemaRequest) GetInitiativeId() string {
	if x != nil {
		return x.InitiativeId
	}
	return ""
}

type PushSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// migrations stored by this push (one per affected connection), apply order.
	// Empty when findings is non-empty (nothing stored).
	Migrations []*Migration `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	// findings the planner couldn't auto-resolve — flattened from
	// planpb.ReviewFinding to plain strings. Non-empty = nothing stored; the
	// client prints them + retries.
	Findings []*Finding `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	// resolved_mode reports the create-vs-update the server actually applied
	// (AUTO resolves to CREATE or UPDATE server-side) so the client can label
	// the push "initial schema" vs "schema revision".
	ResolvedMode  PushMode `protobuf:"varint,3,opt,name=resolved_mode,json=resolvedMode,proto3,enum=w17.registry.PushMode" json:"resolved_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSchemaResponse) Reset() {
	*x = PushSchemaResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSchemaResponse) ProtoMessage() {}

func (x *PushSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSchemaResponse.ProtoReflect.Descriptor instead.
func (*PushSchemaResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{6}
}

func (x *PushSchemaResponse) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *PushSchemaResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *PushSchemaResponse) GetResolvedMode() PushMode {
	if x != nil {
		return x.ResolvedMode
	}
	return PushMode_PUSH_MODE_AUTO
}

// Finding is one unresolved planner decision, flattened from
// planpb.ReviewFinding (+ its ColumnRef) to the plain fields the client prints.
type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ColumnName    string                 `protobuf:"bytes,2,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	FieldNumber   int32                  `protobuf:"varint,3,opt,name=field_number,json=fieldNumber,proto3" json:"field_number,omitempty"`
	Axis          string                 `protobuf:"bytes,4,opt,name=axis,proto3" json:"axis,omitempty"`
	Rationale     string                 `protobuf:"bytes,5,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_w17registry_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{7}
}

func (x *Finding) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Finding) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *Finding) GetFieldNumber() int32 {
	if x != nil {
		return x.FieldNumber
	}
	return 0
}

func (x *Finding) GetAxis() string {
	if x != nil {
		return x.Axis
	}
	return ""
}

func (x *Finding) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type PushRawMigrationRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProjectId  string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Connection string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// yaml_body is the hand-authored lib/datamigrate.Migration YAML; the server
	// validates + signs + stores it.
	YamlBody string `protobuf:"bytes,3,opt,name=yaml_body,json=yamlBody,proto3" json:"yaml_body,omitempty"`
	// initiative_id — see PushSchemaRequest. A hand-authored data migration
	// belongs to a change request exactly like a schema diff does; leaving it
	// unstamped would hide it from the range a freeze collapses.
	InitiativeId  string `protobuf:"bytes,4,opt,name=initiative_id,json=initiativeId,proto3" json:"initiative_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRawMigrationRequest) Reset() {
	*x = PushRawMigrationRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRawMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRawMigrationRequest) ProtoMessage() {}

func (x *PushRawMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRawMigrationRequest.ProtoReflect.Descriptor instead.
func (*PushRawMigrationRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{8}
}

func (x *PushRawMigrationRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PushRawMigrationRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *PushRawMigrationRequest) GetYamlBody() string {
	if x != nil {
		return x.YamlBody
	}
	return ""
}

func (x *PushRawMigrationRequest) GetInitiativeId() string {
	if x != nil {
		return x.InitiativeId
	}
	return ""
}

type PushRawMigrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// migration is the stored result (server-assigned id + content_sha256).
	Migration     *Migration `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRawMigrationResponse) Reset() {
	*x = PushRawMigrationResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRawMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRawMigrationResponse) ProtoMessage() {}

func (x *PushRawMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRawMigrationResponse.ProtoReflect.Descriptor instead.
func (*PushRawMigrationResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{9}
}

func (x *PushRawMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type PushFixtureRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Domain    string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// json is the fixture's raw canonical JSON body. The server decodes +
	// validates it against the stored schema before storing.
	Json          []byte `protobuf:"bytes,4,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFixtureRequest) Reset() {
	*x = PushFixtureRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFixtureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFixtureRequest) ProtoMessage() {}

func (x *PushFixtureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFixtureRequest.ProtoReflect.Descriptor instead.
func (*PushFixtureRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{10}
}

func (x *PushFixtureRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PushFixtureRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PushFixtureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PushFixtureRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type PushFixtureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content_sha256 of the stored body (audit / round-trip).
	ContentSha256 string `protobuf:"bytes,1,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	// row_count is the number of rows in the stored fixture (log hint).
	RowCount      int32 `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFixtureResponse) Reset() {
	*x = PushFixtureResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFixtureResponse) ProtoMessage() {}

func (x *PushFixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFixtureResponse.ProtoReflect.Descriptor instead.
func (*PushFixtureResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{11}
}

func (x *PushFixtureResponse) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *PushFixtureResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

type ReleaseProjectToOrgRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Empty WITHDRAWS a pending offer.
	TargetOrgId   string `protobuf:"bytes,2,opt,name=target_org_id,json=targetOrgId,proto3" json:"target_org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProjectToOrgRequest) Reset() {
	*x = ReleaseProjectToOrgRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProjectToOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProjectToOrgRequest) ProtoMessage() {}

func (x *ReleaseProjectToOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProjectToOrgRequest.ProtoReflect.Descriptor instead.
func (*ReleaseProjectToOrgRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseProjectToOrgRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReleaseProjectToOrgRequest) GetTargetOrgId() string {
	if x != nil {
		return x.TargetOrgId
	}
	return ""
}

type ReleaseProjectToOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetOrgId   string                 `protobuf:"bytes,1,opt,name=target_org_id,json=targetOrgId,proto3" json:"target_org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProjectToOrgResponse) Reset() {
	*x = ReleaseProjectToOrgResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProjectToOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProjectToOrgResponse) ProtoMessage() {}

func (x *ReleaseProjectToOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProjectToOrgResponse.ProtoReflect.Descriptor instead.
func (*ReleaseProjectToOrgResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseProjectToOrgResponse) GetTargetOrgId() string {
	if x != nil {
		return x.TargetOrgId
	}
	return ""
}

type ClaimProjectRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Empty keeps the current name; supply one to resolve a reported collision.
	NewProjectName string `protobuf:"bytes,2,opt,name=new_project_name,json=newProjectName,proto3" json:"new_project_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimProjectRequest) Reset() {
	*x = ClaimProjectRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimProjectRequest) ProtoMessage() {}

func (x *ClaimProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimProjectRequest.ProtoReflect.Descriptor instead.
func (*ClaimProjectRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{14}
}

func (x *ClaimProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ClaimProjectRequest) GetNewProjectName() string {
	if x != nil {
		return x.NewProjectName
	}
	return ""
}

type ClaimProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name the project ended up with, to write back into the lock.
	ProjectName   string `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimProjectResponse) Reset() {
	*x = ClaimProjectResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimProjectResponse) ProtoMessage() {}

func (x *ClaimProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimProjectResponse.ProtoReflect.Descriptor instead.
func (*ClaimProjectResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{15}
}

func (x *ClaimProjectResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type ResetHistoryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. UNSPECIFIED is refused — a destructive call must name what it
	// intends rather than inherit it from a zero value.
	Policy ResetHistoryPolicy `protobuf:"varint,2,opt,name=policy,proto3,enum=w17.registry.ResetHistoryPolicy" json:"policy,omitempty"`
	// Required for DISCARD. The server refuses without it.
	AcknowledgeDataLoss bool `protobuf:"varint,3,opt,name=acknowledge_data_loss,json=acknowledgeDataLoss,proto3" json:"acknowledge_data_loss,omitempty"`
	// initiative_id names the change request this freeze is collapsing —
	// SUPERSEDE only; the server refuses it on DISCARD rather than ignoring it.
	//
	// It is an ASSERTION, not a narrowing: the server refuses unless every live
	// migration belongs to that change request, naming the ones that do not and
	// the change request each belongs to. What it buys is edges — a squash run
	// while another CR's migrations happen to sit in the history collapses those
	// too, and without this nothing says so.
	//
	// Empty keeps the unconditional whole-history collapse.
	InitiativeId  string `protobuf:"bytes,4,opt,name=initiative_id,json=initiativeId,proto3" json:"initiative_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetHistoryRequest) Reset() {
	*x = ResetHistoryRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetHistoryRequest) ProtoMessage() {}

func (x *ResetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetHistoryRequest.ProtoReflect.Descriptor instead.
func (*ResetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ResetHistoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ResetHistoryRequest) GetPolicy() ResetHistoryPolicy {
	if x != nil {
		return x.Policy
	}
	return ResetHistoryPolicy_RESET_HISTORY_POLICY_UNSPECIFIED
}

func (x *ResetHistoryRequest) GetAcknowledgeDataLoss() bool {
	if x != nil {
		return x.AcknowledgeDataLoss
	}
	return false
}

func (x *ResetHistoryRequest) GetInitiativeId() string {
	if x != nil {
		return x.InitiativeId
	}
	return ""
}

type ImportProjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceProjectId string                 `protobuf:"bytes,1,opt,name=source_project_id,json=sourceProjectId,proto3" json:"source_project_id,omitempty"`
	TargetProjectId string                 `protobuf:"bytes,2,opt,name=target_project_id,json=targetProjectId,proto3" json:"target_project_id,omitempty"`
	// initiative_id stamps the revision the import records, so the imported
	// range belongs to a change request like any other push.
	InitiativeId  string `protobuf:"bytes,3,opt,name=initiative_id,json=initiativeId,proto3" json:"initiative_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProjectRequest) Reset() {
	*x = ImportProjectRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProjectRequest) ProtoMessage() {}

func (x *ImportProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProjectRequest.ProtoReflect.Descriptor instead.
func (*ImportProjectRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{17}
}

func (x *ImportProjectRequest) GetSourceProjectId() string {
	if x != nil {
		return x.SourceProjectId
	}
	return ""
}

func (x *ImportProjectRequest) GetTargetProjectId() string {
	if x != nil {
		return x.TargetProjectId
	}
	return ""
}

func (x *ImportProjectRequest) GetInitiativeId() string {
	if x != nil {
		return x.InitiativeId
	}
	return ""
}

type ImportProjectResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MigrationsImported int32                  `protobuf:"varint,1,opt,name=migrations_imported,json=migrationsImported,proto3" json:"migrations_imported,omitempty"`
	TablesImported     int32                  `protobuf:"varint,2,opt,name=tables_imported,json=tablesImported,proto3" json:"tables_imported,omitempty"`
	FixturesImported   int32                  `protobuf:"varint,3,opt,name=fixtures_imported,json=fixturesImported,proto3" json:"fixtures_imported,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ImportProjectResponse) Reset() {
	*x = ImportProjectResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProjectResponse) ProtoMessage() {}

func (x *ImportProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProjectResponse.ProtoReflect.Descriptor instead.
func (*ImportProjectResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{18}
}

func (x *ImportProjectResponse) GetMigrationsImported() int32 {
	if x != nil {
		return x.MigrationsImported
	}
	return 0
}

func (x *ImportProjectResponse) GetTablesImported() int32 {
	if x != nil {
		return x.TablesImported
	}
	return 0
}

func (x *ImportProjectResponse) GetFixturesImported() int32 {
	if x != nil {
		return x.FixturesImported
	}
	return 0
}

type VerifyHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyHistoryRequest) Reset() {
	*x = VerifyHistoryRequest{}
	mi := &file_w17registry_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyHistoryRequest) ProtoMessage() {}

func (x *VerifyHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyHistoryRequest.ProtoReflect.Descriptor instead.
func (*VerifyHistoryRequest) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyHistoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type VerifyHistoryResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Verdict HistoryVerdict         `protobuf:"varint,1,opt,name=verdict,proto3,enum=w17.registry.HistoryVerdict" json:"verdict,omitempty"`
	// detail says what disagrees, and is set only for DRIFTED — it names the
	// migration or the count that does not line up, because "your history
	// drifted" without the row is not actionable.
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// recorded_revisions is how many pushes are on record. Zero alongside
	// UNKNOWN is the legacy shape; zero alongside CONSISTENT is a project
	// nobody has pushed to yet.
	RecordedRevisions int32 `protobuf:"varint,3,opt,name=recorded_revisions,json=recordedRevisions,proto3" json:"recorded_revisions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyHistoryResponse) Reset() {
	*x = VerifyHistoryResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyHistoryResponse) ProtoMessage() {}

func (x *VerifyHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyHistoryResponse.ProtoReflect.Descriptor instead.
func (*VerifyHistoryResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyHistoryResponse) GetVerdict() HistoryVerdict {
	if x != nil {
		return x.Verdict
	}
	return HistoryVerdict_HISTORY_VERDICT_UNKNOWN
}

func (x *VerifyHistoryResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *VerifyHistoryResponse) GetRecordedRevisions() int32 {
	if x != nil {
		return x.RecordedRevisions
	}
	return 0
}

type ResetHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// migrations_dropped counts every dropped migration, across connections.
	MigrationsDropped int32 `protobuf:"varint,1,opt,name=migrations_dropped,json=migrationsDropped,proto3" json:"migrations_dropped,omitempty"`
	// raw_migrations_dropped counts the hand-authored raw data migrations among
	// them. These CANNOT be re-derived from the schema (their bodies are
	// author-owned), so the client prints this rather than letting the operator
	// discover it afterwards.
	RawMigrationsDropped int32 `protobuf:"varint,2,opt,name=raw_migrations_dropped,json=rawMigrationsDropped,proto3" json:"raw_migrations_dropped,omitempty"`
	// raw_migration_ids names those bodies, so the message can list them
	// instead of only counting them.
	RawMigrationIds []string `protobuf:"bytes,3,rep,name=raw_migration_ids,json=rawMigrationIds,proto3" json:"raw_migration_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetHistoryResponse) Reset() {
	*x = ResetHistoryResponse{}
	mi := &file_w17registry_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetHistoryResponse) ProtoMessage() {}

func (x *ResetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_w17registry_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetHistoryResponse.ProtoReflect.Descriptor instead.
func (*ResetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_w17registry_registry_proto_rawDescGZIP(), []int{21}
}

func (x *ResetHistoryResponse) GetMigrationsDropped() int32 {
	if x != nil {
		return x.MigrationsDropped
	}
	return 0
}

func (x *ResetHistoryResponse) GetRawMigrationsDropped() int32 {
	if x != nil {
		return x.RawMigrationsDropped
	}
	return 0
}

func (x *ResetHistoryResponse) GetRawMigrationIds() []string {
	if x != nil {
		return x.RawMigrationIds
	}
	return nil
}

var File_w17registry_registry_proto protoreflect.FileDescriptor

const file_w17registry_registry_proto_rawDesc = "" +
	"\n" +
	"\x1aw17registry/registry.proto\x12\fw17.registry\"b\n" +
	"\tMigration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12%\n" +
	"\x0econtent_sha256\x18\x03 \x01(\tR\rcontentSha256\",\n" +
	"\x16RegisterProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x17RegisterProjectResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\xaf\x01\n" +
	"\x15ListMigrationsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12*\n" +
	"\x11from_migration_id\x18\x03 \x01(\tR\x0ffromMigrationId\x12+\n" +
	"\x12up_to_migration_id\x18\x04 \x01(\tR\x0fupToMigrationId\"Q\n" +
	"\x16ListMigrationsResponse\x127\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x17.w17.registry.MigrationR\n" +
	"migrations\"\xf6\x02\n" +
	"\x11PushSchemaRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x0e\n" +
	"\x02ir\x18\x02 \x01(\fR\x02ir\x12*\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x16.w17.registry.PushModeR\x04mode\x12#\n" +
	"\rforce_initial\x18\x04 \x01(\bR\fforceInitial\x12\x16\n" +
	"\x06decide\x18\x05 \x03(\tR\x06decide\x12`\n" +
	"\x11decide_custom_sql\x18\x06 \x03(\v24.w17.registry.PushSchemaRequest.DecideCustomSqlEntryR\x0fdecideCustomSql\x12#\n" +
	"\rinitiative_id\x18\a \x01(\tR\finitiativeId\x1aB\n" +
	"\x14DecideCustomSqlEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x12PushSchemaResponse\x127\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x17.w17.registry.MigrationR\n" +
	"migrations\x121\n" +
	"\bfindings\x18\x02 \x03(\v2\x15.w17.registry.FindingR\bfindings\x12;\n" +
	"\rresolved_mode\x18\x03 \x01(\x0e2\x16.w17.registry.PushModeR\fresolvedMode\"\x9e\x01\n" +
	"\aFinding\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vcolumn_name\x18\x02 \x01(\tR\n" +
	"columnName\x12!\n" +
	"\ffield_number\x18\x03 \x01(\x05R\vfieldNumber\x12\x12\n" +
	"\x04axis\x18\x04 \x01(\tR\x04axis\x12\x1c\n" +
	"\trationale\x18\x05 \x01(\tR\trationale\"\x9a\x01\n" +
	"\x17PushRawMigrationRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12\x1b\n" +
	"\tyaml_body\x18\x03 \x01(\tR\byamlBody\x12#\n" +
	"\rinitiative_id\x18\x04 \x01(\tR\finitiativeId\"Q\n" +
	"\x18PushRawMigrationResponse\x125\n" +
	"\tmigration\x18\x01 \x01(\v2\x17.w17.registry.MigrationR\tmigration\"s\n" +
	"\x12PushFixtureRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04json\x18\x04 \x01(\fR\x04json\"Y\n" +
	"\x13PushFixtureResponse\x12%\n" +
	"\x0econtent_sha256\x18\x01 \x01(\tR\rcontentSha256\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x05R\browCount\"_\n" +
	"\x1aReleaseProjectToOrgRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\"\n" +
	"\rtarget_org_id\x18\x02 \x01(\tR\vtargetOrgId\"A\n" +
	"\x1bReleaseProjectToOrgResponse\x12\"\n" +
	"\rtarget_org_id\x18\x01 \x01(\tR\vtargetOrgId\"^\n" +
	"\x13ClaimProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x10new_project_name\x18\x02 \x01(\tR\x0enewProjectName\"9\n" +
	"\x14ClaimProjectResponse\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\"\xc7\x01\n" +
	"\x13ResetHistoryRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x128\n" +
	"\x06policy\x18\x02 \x01(\x0e2 .w17.registry.ResetHistoryPolicyR\x06policy\x122\n" +
	"\x15acknowledge_data_loss\x18\x03 \x01(\bR\x13acknowledgeDataLoss\x12#\n" +
	"\rinitiative_id\x18\x04 \x01(\tR\finitiativeId\"\x93\x01\n" +
	"\x14ImportProjectRequest\x12*\n" +
	"\x11source_project_id\x18\x01 \x01(\tR\x0fsourceProjectId\x12*\n" +
	"\x11target_project_id\x18\x02 \x01(\tR\x0ftargetProjectId\x12#\n" +
	"\rinitiative_id\x18\x03 \x01(\tR\finitiativeId\"\x9e\x01\n" +
	"\x15ImportProjectResponse\x12/\n" +
	"\x13migrations_imported\x18\x01 \x01(\x05R\x12migrationsImported\x12'\n" +
	"\x0ftables_imported\x18\x02 \x01(\x05R\x0etablesImported\x12+\n" +
	"\x11fixtures_imported\x18\x03 \x01(\x05R\x10fixturesImported\"5\n" +
	"\x14VerifyHistoryRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x96\x01\n" +
	"\x15VerifyHistoryResponse\x126\n" +
	"\averdict\x18\x01 \x01(\x0e2\x1c.w17.registry.HistoryVerdictR\averdict\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12-\n" +
	"\x12recorded_revisions\x18\x03 \x01(\x05R\x11recordedRevisions\"\xa7\x01\n" +
	"\x14ResetHistoryResponse\x12-\n" +
	"\x12migrations_dropped\x18\x01 \x01(\x05R\x11migrationsDropped\x124\n" +
	"\x16raw_migrations_dropped\x18\x02 \x01(\x05R\x14rawMigrationsDropped\x12*\n" +
	"\x11raw_migration_ids\x18\x03 \x03(\tR\x0frawMigrationIds*J\n" +
	"\bPushMode\x12\x12\n" +
	"\x0ePUSH_MODE_AUTO\x10\x00\x12\x14\n" +
	"\x10PUSH_MODE_CREATE\x10\x01\x12\x14\n" +
	"\x10PUSH_MODE_UPDATE\x10\x02*\x80\x01\n" +
	"\x12ResetHistoryPolicy\x12$\n" +
	" RESET_HISTORY_POLICY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cRESET_HISTORY_POLICY_DISCARD\x10\x01\x12\"\n" +
	"\x1eRESET_HISTORY_POLICY_SUPERSEDE\x10\x02*j\n" +
	"\x0eHistoryVerdict\x12\x1b\n" +
	"\x17HISTORY_VERDICT_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aHISTORY_VERDICT_CONSISTENT\x10\x01\x12\x1b\n" +
	"\x17HISTORY_VERDICT_DRIFTED\x10\x022\xa4\a\n" +
	"\x0fProjectRegistry\x12^\n" +
	"\x0fRegisterProject\x12$.w17.registry.RegisterProjectRequest\x1a%.w17.registry.RegisterProjectResponse\x12[\n" +
	"\x0eListMigrations\x12#.w17.registry.ListMigrationsRequest\x1a$.w17.registry.ListMigrationsResponse\x12O\n" +
	"\n" +
	"PushSchema\x12\x1f.w17.registry.PushSchemaRequest\x1a .w17.registry.PushSchemaResponse\x12a\n" +
	"\x10PushRawMigration\x12%.w17.registry.PushRawMigrationRequest\x1a&.w17.registry.PushRawMigrationResponse\x12R\n" +
	"\vPushFixture\x12 .w17.registry.PushFixtureRequest\x1a!.w17.registry.PushFixtureResponse\x12j\n" +
	"\x13ReleaseProjectToOrg\x12(.w17.registry.ReleaseProjectToOrgRequest\x1a).w17.registry.ReleaseProjectToOrgResponse\x12U\n" +
	"\fClaimProject\x12!.w17.registry.ClaimProjectRequest\x1a\".w17.registry.ClaimProjectResponse\x12U\n" +
	"\fResetHistory\x12!.w17.registry.ResetHistoryRequest\x1a\".w17.registry.ResetHistoryResponse\x12X\n" +
	"\rVerifyHistory\x12\".w17.registry.VerifyHistoryRequest\x1a#.w17.registry.VerifyHistoryResponse\x12X\n" +
	"\rImportProject\x12\".w17.registry.ImportProjectRequest\x1a#.w17.registry.ImportProjectResponseBCZAgithub.com/wandering-compiler/sdk/go/pb/w17registry;w17registrypbb\x06proto3"

var (
	file_w17registry_registry_proto_rawDescOnce sync.Once
	file_w17registry_registry_proto_rawDescData []byte
)

func file_w17registry_registry_proto_rawDescGZIP() []byte {
	file_w17registry_registry_proto_rawDescOnce.Do(func() {
		file_w17registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17registry_registry_proto_rawDesc), len(file_w17registry_registry_proto_rawDesc)))
	})
	return file_w17registry_registry_proto_rawDescData
}

var file_w17registry_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_w17registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_w17registry_registry_proto_goTypes = []any{
	(PushMode)(0),                       // 0: w17.registry.PushMode
	(ResetHistoryPolicy)(0),             // 1: w17.registry.ResetHistoryPolicy
	(HistoryVerdict)(0),                 // 2: w17.registry.HistoryVerdict
	(*Migration)(nil),                   // 3: w17.registry.Migration
	(*RegisterProjectRequest)(nil),      // 4: w17.registry.RegisterProjectRequest
	(*RegisterProjectResponse)(nil),     // 5: w17.registry.RegisterProjectResponse
	(*ListMigrationsRequest)(nil),       // 6: w17.registry.ListMigrationsRequest
	(*ListMigrationsResponse)(nil),      // 7: w17.registry.ListMigrationsResponse
	(*PushSchemaRequest)(nil),           // 8: w17.registry.PushSchemaRequest
	(*PushSchemaResponse)(nil),          // 9: w17.registry.PushSchemaResponse
	(*Finding)(nil),                     // 10: w17.registry.Finding
	(*PushRawMigrationRequest)(nil),     // 11: w17.registry.PushRawMigrationRequest
	(*PushRawMigrationResponse)(nil),    // 12: w17.registry.PushRawMigrationResponse
	(*PushFixtureRequest)(nil),          // 13: w17.registry.PushFixtureRequest
	(*PushFixtureResponse)(nil),         // 14: w17.registry.PushFixtureResponse
	(*ReleaseProjectToOrgRequest)(nil),  // 15: w17.registry.ReleaseProjectToOrgRequest
	(*ReleaseProjectToOrgResponse)(nil), // 16: w17.registry.ReleaseProjectToOrgResponse
	(*ClaimProjectRequest)(nil),         // 17: w17.registry.ClaimProjectRequest
	(*ClaimProjectResponse)(nil),        // 18: w17.registry.ClaimProjectResponse
	(*ResetHistoryRequest)(nil),         // 19: w17.registry.ResetHistoryRequest
	(*ImportProjectRequest)(nil),        // 20: w17.registry.ImportProjectRequest
	(*ImportProjectResponse)(nil),       // 21: w17.registry.ImportProjectResponse
	(*VerifyHistoryRequest)(nil),        // 22: w17.registry.VerifyHistoryRequest
	(*VerifyHistoryResponse)(nil),       // 23: w17.registry.VerifyHistoryResponse
	(*ResetHistoryResponse)(nil),        // 24: w17.registry.ResetHistoryResponse
	nil,                                 // 25: w17.registry.PushSchemaRequest.DecideCustomSqlEntry
}
var file_w17registry_registry_proto_depIdxs = []int32{
	3,  // 0: w17.registry.ListMigrationsResponse.migrations:type_name -> w17.registry.Migration
	0,  // 1: w17.registry.PushSchemaRequest.mode:type_name -> w17.registry.PushMode
	25, // 2: w17.registry.PushSchemaRequest.decide_custom_sql:type_name -> w17.registry.PushSchemaRequest.DecideCustomSqlEntry
	3,  // 3: w17.registry.PushSchemaResponse.migrations:type_name -> w17.registry.Migration
	10, // 4: w17.registry.PushSchemaResponse.findings:type_name -> w17.registry.Finding
	0,  // 5: w17.registry.PushSchemaResponse.resolved_mode:type_name -> w17.registry.PushMode
	3,  // 6: w17.registry.PushRawMigrationResponse.migration:type_name -> w17.registry.Migration
	1,  // 7: w17.registry.ResetHistoryRequest.policy:type_name -> w17.registry.ResetHistoryPolicy
	2,  // 8: w17.registry.VerifyHistoryResponse.verdict:type_name -> w17.registry.HistoryVerdict
	4,  // 9: w17.registry.ProjectRegistry.RegisterProject:input_type -> w17.registry.RegisterProjectRequest
	6,  // 10: w17.registry.ProjectRegistry.ListMigrations:input_type -> w17.registry.ListMigrationsRequest
	8,  // 11: w17.registry.ProjectRegistry.PushSchema:input_type -> w17.registry.PushSchemaRequest
	11, // 12: w17.registry.ProjectRegistry.PushRawMigration:input_type -> w17.registry.PushRawMigrationRequest
	13, // 13: w17.registry.ProjectRegistry.PushFixture:input_type -> w17.registry.PushFixtureRequest
	15, // 14: w17.registry.ProjectRegistry.ReleaseProjectToOrg:input_type -> w17.registry.ReleaseProjectToOrgRequest
	17, // 15: w17.registry.ProjectRegistry.ClaimProject:input_type -> w17.registry.ClaimProjectRequest
	19, // 16: w17.registry.ProjectRegistry.ResetHistory:input_type -> w17.registry.ResetHistoryRequest
	22, // 17: w17.registry.ProjectRegistry.VerifyHistory:input_type -> w17.registry.VerifyHistoryRequest
	20, // 18: w17.registry.ProjectRegistry.ImportProject:input_type -> w17.registry.ImportProjectRequest
	5,  // 19: w17.registry.ProjectRegistry.RegisterProject:output_type -> w17.registry.RegisterProjectResponse
	7,  // 20: w17.registry.ProjectRegistry.ListMigrations:output_type -> w17.registry.ListMigrationsResponse
	9,  // 21: w17.registry.ProjectRegistry.PushSchema:output_type -> w17.registry.PushSchemaResponse
	12, // 22: w17.registry.ProjectRegistry.PushRawMigration:output_type -> w17.registry.PushRawMigrationResponse
	14, // 23: w17.registry.ProjectRegistry.PushFixture:output_type -> w17.registry.PushFixtureResponse
	16, // 24: w17.registry.ProjectRegistry.ReleaseProjectToOrg:output_type -> w17.registry.ReleaseProjectToOrgResponse
	18, // 25: w17.registry.ProjectRegistry.ClaimProject:output_type -> w17.registry.ClaimProjectResponse
	24, // 26: w17.registry.ProjectRegistry.ResetHistory:output_type -> w17.registry.ResetHistoryResponse
	23, // 27: w17.registry.ProjectRegistry.VerifyHistory:output_type -> w17.registry.VerifyHistoryResponse
	21, // 28: w17.registry.ProjectRegistry.ImportProject:output_type -> w17.registry.ImportProjectResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_w17registry_registry_proto_init() }
func file_w17registry_registry_proto_init() {
	if File_w17registry_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17registry_registry_proto_rawDesc), len(file_w17registry_registry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_w17registry_registry_proto_goTypes,
		DependencyIndexes: file_w17registry_registry_proto_depIdxs,
		EnumInfos:         file_w17registry_registry_proto_enumTypes,
		MessageInfos:      file_w17registry_registry_proto_msgTypes,
	}.Build()
	File_w17registry_registry_proto = out.File
	file_w17registry_registry_proto_goTypes = nil
	file_w17registry_registry_proto_depIdxs = nil
}
