// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: w17/pg/module.proto

package pgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PgModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain-level custom_types registry. Author registers PG types
	// specific to this domain (e.g. road_segment for routing domain,
	// customer_address_format for billing). Project-wide types live in
	// (w17.pg.project) instead.
	//
	// Aliases must be unique within the domain (collision = compile
	// error). Domain alias must not collide with a project-level alias
	// (that's also a compile error — no shadowing).
	CustomTypes []*CustomType `protobuf:"bytes,1,rep,name=custom_types,json=customTypes,proto3" json:"custom_types,omitempty"`
	// REV-024 (F1, 2026-05-09) — domain-level custom_functions
	// registry. Author registers PG functions / operators that DQL
	// queries reference (pgvector `<->`, postgis `ST_*`, custom
	// plpgsql functions). DQL typecheck consults this set after
	// builtins; unknown name = "function not found" diag.
	//
	// Names must be unique within domain; cannot collide with
	// builtin function names or with project-level entries
	// (compile error, no shadowing).
	CustomFunctions []*CustomFunction `protobuf:"bytes,2,rep,name=custom_functions,json=customFunctions,proto3" json:"custom_functions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PgModule) Reset() {
	*x = PgModule{}
	mi := &file_w17_pg_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgModule) ProtoMessage() {}

func (x *PgModule) ProtoReflect() protoreflect.Message {
	mi := &file_w17_pg_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgModule.ProtoReflect.Descriptor instead.
func (*PgModule) Descriptor() ([]byte, []int) {
	return file_w17_pg_module_proto_rawDescGZIP(), []int{0}
}

func (x *PgModule) GetCustomTypes() []*CustomType {
	if x != nil {
		return x.CustomTypes
	}
	return nil
}

func (x *PgModule) GetCustomFunctions() []*CustomFunction {
	if x != nil {
		return x.CustomFunctions
	}
	return nil
}

// CustomType — one registered custom PG type. Author writes it once at
// module or project level; field-level (w17.pg.field).custom_type
// references it by `alias` only.
//
// The IR / engine treat this as the single source of truth for:
//   - the SQL type keyword to emit (`sql_type`)
//   - extensions required by this type (`required_extensions` —
//     manifest-aggregated)
//   - conversion paths to / from other types (`convertible_to /
//     convertible_from`) used by D33 engine USING-clause rendering
type CustomType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alias the field-level (w17.pg.field).custom_type references. Must
	// be a valid identifier, unique within the resolved registry (project
	// + domain merge), and must not collide with native PG type keywords
	// (text / integer / jsonb / …) or with reserved D14 sem names.
	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	// The raw PG SQL type expression — appears verbatim in CREATE TABLE
	// column clause and in ALTER TABLE … TYPE statements.
	// Examples: "HSTORE", "vector(1536)", "geometry(LineString,4326)",
	// "my_custom_domain".
	SqlType string `protobuf:"bytes,2,opt,name=sql_type,json=sqlType,proto3" json:"sql_type,omitempty"`
	// Postgres extensions that must exist before this type is usable.
	// Manifest aggregates extensions from every CustomType actually
	// referenced by the migration. The platform / deploy client takes
	// care of `CREATE EXTENSION IF NOT EXISTS` pre-apply — compiler does
	// not emit those statements into migration bodies.
	RequiredExtensions []string `protobuf:"bytes,3,rep,name=required_extensions,json=requiredExtensions,proto3" json:"required_extensions,omitempty"`
	// Outbound conversions: types this CustomType can be CAST TO using
	// the supplied template. Each entry's `type` is either another
	// registered alias or a native PG type keyword.
	ConvertibleTo []*Conversion `protobuf:"bytes,4,rep,name=convertible_to,json=convertibleTo,proto3" json:"convertible_to,omitempty"`
	// Inbound conversions: types that can be CAST INTO this CustomType
	// using the supplied template. Symmetric helper to convertible_to —
	// engine looks up either side at migration time.
	ConvertibleFrom []*Conversion `protobuf:"bytes,5,rep,name=convertible_from,json=convertibleFrom,proto3" json:"convertible_from,omitempty"`
	// Free-text description for manifest / docs / review UI.
	Description   string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomType) Reset() {
	*x = CustomType{}
	mi := &file_w17_pg_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomType) ProtoMessage() {}

func (x *CustomType) ProtoReflect() protoreflect.Message {
	mi := &file_w17_pg_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomType.ProtoReflect.Descriptor instead.
func (*CustomType) Descriptor() ([]byte, []int) {
	return file_w17_pg_module_proto_rawDescGZIP(), []int{1}
}

func (x *CustomType) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CustomType) GetSqlType() string {
	if x != nil {
		return x.SqlType
	}
	return ""
}

func (x *CustomType) GetRequiredExtensions() []string {
	if x != nil {
		return x.RequiredExtensions
	}
	return nil
}

func (x *CustomType) GetConvertibleTo() []*Conversion {
	if x != nil {
		return x.ConvertibleTo
	}
	return nil
}

func (x *CustomType) GetConvertibleFrom() []*Conversion {
	if x != nil {
		return x.ConvertibleFrom
	}
	return nil
}

func (x *CustomType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CustomFunction — one registered PG function / operator that DQL
// queries reference. Author registers at project or domain level;
// DQL typecheck merges all registries and consults them after the
// builtin set. REV-024 (F1, 2026-05-09).
//
// MVP scope: name + extensions only. Typecheck accepts ANY arg shape
// for registered names (permissive — runtime PG surfaces signature
// mismatches). Future iteration may add typed signature info
// (min_args / max_args / arg_categories / returns / is_aggregate)
// alongside, when fixtures demand static checks.
type CustomFunction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Function name as referenced from DQL — case-insensitive lookup
	// matches the builtin convention. Examples: "ST_GeomFromText",
	// "vector_to_array", "<->" (operator-as-function — invalid as
	// function name today; reserved for future operator registration).
	//
	// Must be unique within the resolved registry (project + domain
	// merge), and must not collide with a builtin function name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Postgres extensions that must exist before this function /
	// operator is callable. Aggregates into Manifest.RequiredExtensions
	// when any DQL query references this function. Same shape as
	// CustomType.required_extensions.
	RequiredExtensions []string `protobuf:"bytes,2,rep,name=required_extensions,json=requiredExtensions,proto3" json:"required_extensions,omitempty"`
	// Free-text description for manifest / docs / review UI.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Whether this custom function is an AGGREGATE (e.g. string_agg,
	// array_agg, bool_and). The DQL typechecker treats custom functions
	// permissively (runtime PG enforces the signature), but a few rules need
	// to know aggregate-ness — notably the (w17.db.lock) shape guard, since
	// PostgreSQL rejects FOR UPDATE combined with an aggregate (F16-1-2).
	IsAggregate   bool `protobuf:"varint,4,opt,name=is_aggregate,json=isAggregate,proto3" json:"is_aggregate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomFunction) Reset() {
	*x = CustomFunction{}
	mi := &file_w17_pg_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFunction) ProtoMessage() {}

func (x *CustomFunction) ProtoReflect() protoreflect.Message {
	mi := &file_w17_pg_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFunction.ProtoReflect.Descriptor instead.
func (*CustomFunction) Descriptor() ([]byte, []int) {
	return file_w17_pg_module_proto_rawDescGZIP(), []int{2}
}

func (x *CustomFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomFunction) GetRequiredExtensions() []string {
	if x != nil {
		return x.RequiredExtensions
	}
	return nil
}

func (x *CustomFunction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomFunction) GetIsAggregate() bool {
	if x != nil {
		return x.IsAggregate
	}
	return false
}

// Conversion — one cast / transformation entry inside CustomType's
// `convertible_to` or `convertible_from` lists.
//
// The `cast` template is a Go text/template (matches D33 `using:`
// templates) with these placeholders:
//
//	{{.Col}}   — column name (post-rename)
//	{{.Table}} — table name (no namespace qualifier)
//
// Examples:
//
//	"{{.Col}}::vector(3072)"                    — simple :: cast
//	"to_tsvector('simple', {{.Col}})"           — function-based
//	"ST_GeomFromText({{.Col}})"                 — extension function
//	"({{.Col}}::real[] || array_fill(0::real, ARRAY[1536]))::vector(3072)"
//	                                            — chained transformation
type Conversion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target / source type. Either:
	//   - another CustomType alias ("road_vector" / "default_vector")
	//   - a native PG type keyword ("jsonb" / "text" / "integer")
	//
	// Native types bypass registry lookup (no alias matching).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// USING-clause template (Go text/template syntax). Required when
	// engine generates an ALTER COLUMN TYPE statement; rendered with
	// {{.Col}} + {{.Table}} context.
	Cast string `protobuf:"bytes,2,opt,name=cast,proto3" json:"cast,omitempty"`
	// Human-readable rationale shown in D35 risk analysis when this
	// conversion is used (e.g. "PG implicit cast preserves all values"
	// or "Pads with zeros to new dimension; lossy if author meant
	// re-inference").
	Rationale     string `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversion) Reset() {
	*x = Conversion{}
	mi := &file_w17_pg_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversion) ProtoMessage() {}

func (x *Conversion) ProtoReflect() protoreflect.Message {
	mi := &file_w17_pg_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversion.ProtoReflect.Descriptor instead.
func (*Conversion) Descriptor() ([]byte, []int) {
	return file_w17_pg_module_proto_rawDescGZIP(), []int{3}
}

func (x *Conversion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Conversion) GetCast() string {
	if x != nil {
		return x.Cast
	}
	return ""
}

func (x *Conversion) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

var file_w17_pg_module_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*PgModule)(nil),
		Field:         51100,
		Name:          "w17.pg.module",
		Tag:           "bytes,51100,opt,name=module",
		Filename:      "w17/pg/module.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional w17.pg.PgModule module = 51100;
	E_Module = &file_w17_pg_module_proto_extTypes[0]
)

var File_w17_pg_module_proto protoreflect.FileDescriptor

const file_w17_pg_module_proto_rawDesc = "" +
	"\n" +
	"\x13w17/pg/module.proto\x12\x06w17.pg\x1a google/protobuf/descriptor.proto\"\x84\x01\n" +
	"\bPgModule\x125\n" +
	"\fcustom_types\x18\x01 \x03(\v2\x12.w17.pg.CustomTypeR\vcustomTypes\x12A\n" +
	"\x10custom_functions\x18\x02 \x03(\v2\x16.w17.pg.CustomFunctionR\x0fcustomFunctions\"\x8a\x02\n" +
	"\n" +
	"CustomType\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x19\n" +
	"\bsql_type\x18\x02 \x01(\tR\asqlType\x12/\n" +
	"\x13required_extensions\x18\x03 \x03(\tR\x12requiredExtensions\x129\n" +
	"\x0econvertible_to\x18\x04 \x03(\v2\x12.w17.pg.ConversionR\rconvertibleTo\x12=\n" +
	"\x10convertible_from\x18\x05 \x03(\v2\x12.w17.pg.ConversionR\x0fconvertibleFrom\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x9a\x01\n" +
	"\x0eCustomFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x13required_extensions\x18\x02 \x03(\tR\x12requiredExtensions\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fis_aggregate\x18\x04 \x01(\bR\visAggregate\"R\n" +
	"\n" +
	"Conversion\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04cast\x18\x02 \x01(\tR\x04cast\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale:H\n" +
	"\x06module\x12\x1c.google.protobuf.FileOptions\x18\x9c\x8f\x03 \x01(\v2\x10.w17.pg.PgModuleR\x06moduleB5Z3github.com/wandering-compiler/sdk/go/pb/w17/pg;pgpbb\x06proto3"

var (
	file_w17_pg_module_proto_rawDescOnce sync.Once
	file_w17_pg_module_proto_rawDescData []byte
)

func file_w17_pg_module_proto_rawDescGZIP() []byte {
	file_w17_pg_module_proto_rawDescOnce.Do(func() {
		file_w17_pg_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_pg_module_proto_rawDesc), len(file_w17_pg_module_proto_rawDesc)))
	})
	return file_w17_pg_module_proto_rawDescData
}

var file_w17_pg_module_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_w17_pg_module_proto_goTypes = []any{
	(*PgModule)(nil),                 // 0: w17.pg.PgModule
	(*CustomType)(nil),               // 1: w17.pg.CustomType
	(*CustomFunction)(nil),           // 2: w17.pg.CustomFunction
	(*Conversion)(nil),               // 3: w17.pg.Conversion
	(*descriptorpb.FileOptions)(nil), // 4: google.protobuf.FileOptions
}
var file_w17_pg_module_proto_depIdxs = []int32{
	1, // 0: w17.pg.PgModule.custom_types:type_name -> w17.pg.CustomType
	2, // 1: w17.pg.PgModule.custom_functions:type_name -> w17.pg.CustomFunction
	3, // 2: w17.pg.CustomType.convertible_to:type_name -> w17.pg.Conversion
	3, // 3: w17.pg.CustomType.convertible_from:type_name -> w17.pg.Conversion
	4, // 4: w17.pg.module:extendee -> google.protobuf.FileOptions
	0, // 5: w17.pg.module:type_name -> w17.pg.PgModule
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	4, // [4:5] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_w17_pg_module_proto_init() }
func file_w17_pg_module_proto_init() {
	if File_w17_pg_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_pg_module_proto_rawDesc), len(file_w17_pg_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_w17_pg_module_proto_goTypes,
		DependencyIndexes: file_w17_pg_module_proto_depIdxs,
		MessageInfos:      file_w17_pg_module_proto_msgTypes,
		ExtensionInfos:    file_w17_pg_module_proto_extTypes,
	}.Build()
	File_w17_pg_module_proto = out.File
	file_w17_pg_module_proto_goTypes = nil
	file_w17_pg_module_proto_depIdxs = nil
}
