// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: w17/pg/project.proto

package pgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PgProject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project-wide custom_types registry — entries are visible to every
	// domain in the project. Domain-level (w17.pg.module).custom_types
	// EXTENDS this set; aliases must not collide between project and
	// domain registries (collision = compile error, no shadowing).
	//
	// Typical entries: common PG types every domain references (HSTORE,
	// CITEXT, MACADDR), shared vocabularies like embedding dimension
	// aliases (embedding_384, embedding_1536), shared geometry SRIDs.
	//
	// Domain-specific types (only one domain uses them) belong in the
	// domain's (w17.pg.module).custom_types instead — keeps project file
	// focused on cross-cutting concerns.
	CustomTypes []*CustomType `protobuf:"bytes,1,rep,name=custom_types,json=customTypes,proto3" json:"custom_types,omitempty"`
	// REV-024 (F1, 2026-05-09) — project-wide custom_functions
	// registry. Same shape + collision rules as
	// PgModule.custom_functions, but visible to every domain.
	// Typical entries: ST_* (postgis), pgvector helpers, shared
	// text-processing UDFs.
	//
	// Domain-specific functions (only one domain uses them) belong
	// in the domain's (w17.pg.module).custom_functions instead.
	CustomFunctions []*CustomFunction `protobuf:"bytes,2,rep,name=custom_functions,json=customFunctions,proto3" json:"custom_functions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PgProject) Reset() {
	*x = PgProject{}
	mi := &file_w17_pg_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgProject) ProtoMessage() {}

func (x *PgProject) ProtoReflect() protoreflect.Message {
	mi := &file_w17_pg_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgProject.ProtoReflect.Descriptor instead.
func (*PgProject) Descriptor() ([]byte, []int) {
	return file_w17_pg_project_proto_rawDescGZIP(), []int{0}
}

func (x *PgProject) GetCustomTypes() []*CustomType {
	if x != nil {
		return x.CustomTypes
	}
	return nil
}

func (x *PgProject) GetCustomFunctions() []*CustomFunction {
	if x != nil {
		return x.CustomFunctions
	}
	return nil
}

var file_w17_pg_project_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*PgProject)(nil),
		Field:         51200,
		Name:          "w17.pg.project",
		Tag:           "bytes,51200,opt,name=project",
		Filename:      "w17/pg/project.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional w17.pg.PgProject project = 51200;
	E_Project = &file_w17_pg_project_proto_extTypes[0]
)

var File_w17_pg_project_proto protoreflect.FileDescriptor

const file_w17_pg_project_proto_rawDesc = "" +
	"\n" +
	"\x14w17/pg/project.proto\x12\x06w17.pg\x1a google/protobuf/descriptor.proto\x1a\x13w17/pg/module.proto\"\x85\x01\n" +
	"\tPgProject\x125\n" +
	"\fcustom_types\x18\x01 \x03(\v2\x12.w17.pg.CustomTypeR\vcustomTypes\x12A\n" +
	"\x10custom_functions\x18\x02 \x03(\v2\x16.w17.pg.CustomFunctionR\x0fcustomFunctions:K\n" +
	"\aproject\x12\x1c.google.protobuf.FileOptions\x18\x80\x90\x03 \x01(\v2\x11.w17.pg.PgProjectR\aprojectB5Z3github.com/wandering-compiler/sdk/go/pb/w17/pg;pgpbb\x06proto3"

var (
	file_w17_pg_project_proto_rawDescOnce sync.Once
	file_w17_pg_project_proto_rawDescData []byte
)

func file_w17_pg_project_proto_rawDescGZIP() []byte {
	file_w17_pg_project_proto_rawDescOnce.Do(func() {
		file_w17_pg_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_w17_pg_project_proto_rawDesc), len(file_w17_pg_project_proto_rawDesc)))
	})
	return file_w17_pg_project_proto_rawDescData
}

var file_w17_pg_project_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_w17_pg_project_proto_goTypes = []any{
	(*PgProject)(nil),                // 0: w17.pg.PgProject
	(*CustomType)(nil),               // 1: w17.pg.CustomType
	(*CustomFunction)(nil),           // 2: w17.pg.CustomFunction
	(*descriptorpb.FileOptions)(nil), // 3: google.protobuf.FileOptions
}
var file_w17_pg_project_proto_depIdxs = []int32{
	1, // 0: w17.pg.PgProject.custom_types:type_name -> w17.pg.CustomType
	2, // 1: w17.pg.PgProject.custom_functions:type_name -> w17.pg.CustomFunction
	3, // 2: w17.pg.project:extendee -> google.protobuf.FileOptions
	0, // 3: w17.pg.project:type_name -> w17.pg.PgProject
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_w17_pg_project_proto_init() }
func file_w17_pg_project_proto_init() {
	if File_w17_pg_project_proto != nil {
		return
	}
	file_w17_pg_module_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_w17_pg_project_proto_rawDesc), len(file_w17_pg_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_w17_pg_project_proto_goTypes,
		DependencyIndexes: file_w17_pg_project_proto_depIdxs,
		MessageInfos:      file_w17_pg_project_proto_msgTypes,
		ExtensionInfos:    file_w17_pg_project_proto_extTypes,
	}.Build()
	File_w17_pg_project_proto = out.File
	file_w17_pg_project_proto_goTypes = nil
	file_w17_pg_project_proto_depIdxs = nil
}
